package net.minecraft;

public class class_3801 {
	public static enum class_3802 {
		AIR,
		LIQUID;
	}

	public static enum class_3803 {
		RAW_GENERATION,
		LOCAL_MODIFICATIONS,
		UNDERGROUND_STRUCTURES,
		SURFACE_STRUCTURES,
		UNDERGROUND_ORES,
		UNDERGROUND_DECORATION,
		VEGETAL_DECORATION,
		TOP_LAYER_MODIFICATION;
	}
}
