package net.minecraft.sound;

import net.minecraft.Bootstrap;
import net.minecraft.util.Identifier;

public class Sounds {
	public static final Sound AMBIENT_CAVE;
	public static final Sound BLOCK_ANVIL_BREAK;
	public static final Sound BLOCK_ANVIL_DESTROY;
	public static final Sound BLOCK_ANVIL_FALL;
	public static final Sound BLOCK_ANVIL_HIT;
	public static final Sound BLOCK_ANVIL_LAND;
	public static final Sound BLOCK_ANVIL_PLACE;
	public static final Sound BLOCK_ANVIL_STEP;
	public static final Sound BLOCK_ANVIL_USE;
	public static final Sound ENTITY_ARMORSTAND_BREAK;
	public static final Sound ENTITY_ARMORSTAND_FALL;
	public static final Sound ENTITY_ARMORSTAND_HIT;
	public static final Sound ENTITY_ARMORSTAND_PLACE;
	public static final Sound ITEM_ARMOR_EQUIP_CHAIN;
	public static final Sound ITEM_ARMOR_EQUIP_DIAMOND;
	public static final Sound ITEM_ARMOR_EQUIP_ELYTRA;
	public static final Sound ITEM_ARMOR_EQUIP_GENERIC;
	public static final Sound ITEM_ARMOR_EQUIP_GOLD;
	public static final Sound ITEM_ARMOR_EQUIP_IRON;
	public static final Sound ITEM_ARMOR_EQUIP_LEATHER;
	public static final Sound ENTITY_ARROW_HIT;
	public static final Sound ENTITY_ARROW_HIT_PLAYER;
	public static final Sound ENTITY_ARROW_SHOOT;
	public static final Sound ENTITY_BAT_AMBIENT;
	public static final Sound ENTITY_BAT_DEATH;
	public static final Sound ENTITY_BAT_HURT;
	public static final Sound ENTITY_BAT_LOOP;
	public static final Sound ENTITY_BAT_TAKEOFF;
	public static final Sound ENTITY_BLAZE_AMBIENT;
	public static final Sound ENTITY_BLAZE_BURN;
	public static final Sound ENTITY_BLAZE_DEATH;
	public static final Sound ENTITY_BLAZE_HURT;
	public static final Sound ENTITY_BLAZE_SHOOT;
	public static final Sound ENTITY_BOBBER_SPLASH;
	public static final Sound ENTITY_BOBBER_THROW;
	public static final Sound ITEM_BOTTLE_EMPTY;
	public static final Sound ITEM_BOTTLE_FILL;
	public static final Sound ITEM_BOTTLE_FILL_DRAGONBREATH;
	public static final Sound BLOCK_BREWING_STAND_BREW;
	public static final Sound ITEM_BUCKET_EMPTY;
	public static final Sound ITEM_BUCKET_EMPTY_LAVA;
	public static final Sound ITEM_BUCKET_FILL;
	public static final Sound ITEM_BUCKET_FILL_LAVA;
	public static final Sound ENTITY_CAT_AMBIENT;
	public static final Sound ENTITY_CAT_DEATH;
	public static final Sound ENTITY_CAT_HISS;
	public static final Sound ENTITY_CAT_HURT;
	public static final Sound ENTITY_CAT_PURR;
	public static final Sound ENTITY_CAT_PURREOW;
	public static final Sound BLOCK_CHEST_CLOSE;
	public static final Sound BLOCK_CHEST_LOCKED;
	public static final Sound BLOCK_CHEST_OPEN;
	public static final Sound ENTITY_CHICKEN_AMBIENT;
	public static final Sound ENTITY_CHICKEN_DEATH;
	public static final Sound ENTITY_CHICKEN_EGG;
	public static final Sound ENTITY_CHICKEN_HURT;
	public static final Sound ENTITY_CHICKEN_STEP;
	public static final Sound BLOCK_CHORUS_FLOWER_DEATH;
	public static final Sound BLOCK_CHORUS_FLOWER_GROW;
	public static final Sound ITEM_CHORUS_FRUIT_TELEPORT;
	public static final Sound BLOCK_CLOTH_BREAK;
	public static final Sound BLOCK_CLOTH_FALL;
	public static final Sound BLOCK_CLOTH_HIT;
	public static final Sound BLOCK_CLOTH_PLACE;
	public static final Sound BLOCK_CLOTH_STEP;
	public static final Sound BLOCK_COMPARATOR_CLICK;
	public static final Sound ENTITY_COW_AMBIENT;
	public static final Sound ENTITY_COW_DEATH;
	public static final Sound ENTITY_COW_HURT;
	public static final Sound ENTITY_COW_MILK;
	public static final Sound ENTITY_COW_STEP;
	public static final Sound ENTITY_CREEPER_DEATH;
	public static final Sound ENTITY_CREEPER_HURT;
	public static final Sound ENTITY_CREEPER_PRIMED;
	public static final Sound BLOCK_DISPENSER_DISPENSE;
	public static final Sound BLOCK_DISPENSER_FAIL;
	public static final Sound BLOCK_DISPENSER_LAUNCH;
	public static final Sound ENTITY_DONKEY_AMBIENT;
	public static final Sound ENTITY_DONKEY_ANGRY;
	public static final Sound ENTITY_DONKEY_CHEST;
	public static final Sound ENTITY_DONKEY_DEATH;
	public static final Sound ENTITY_DONKEY_HURT;
	public static final Sound ENTITY_EGG_THROW;
	public static final Sound ENTITY_ELDER_GUARDIAN_AMBIENT;
	public static final Sound ENTITY_ELDER_GUARDIAN_AMBIENT_LAND;
	public static final Sound ENTITY_ELDER_GUARDIAN_CURSE;
	public static final Sound ENTITY_ELDER_GUARDIAN_DEATH;
	public static final Sound ENTITY_ELDER_GUARDIAN_DEATH_LAND;
	public static final Sound ENTITY_ELDER_GUARDIAN_FLOP;
	public static final Sound ENTITY_ELDER_GUARDIAN_HURT;
	public static final Sound ENTITY_ELDER_GUARDIAN_HURT_LAND;
	public static final Sound ITEM_ELYTRA_FLYING;
	public static final Sound BLOCK_ENCHANTMENT_TABLE_USE;
	public static final Sound BLOCK_ENDERCHEST_CLOSE;
	public static final Sound BLOCK_ENDERCHEST_OPEN;
	public static final Sound ENTITY_ENDERDRAGON_AMBIENT;
	public static final Sound ENTITY_ENDERDRAGON_DEATH;
	public static final Sound ENTITY_ENDERDRAGON_FIREBALL_EXPLODE;
	public static final Sound ENTITY_ENDERDRAGON_FLAP;
	public static final Sound ENTITY_ENDERDRAGON_GROWL;
	public static final Sound ENTITY_ENDERDRAGON_HURT;
	public static final Sound ENTITY_ENDERDRAGON_SHOOT;
	public static final Sound ENTITY_ENDEREYE_LAUNCH;
	public static final Sound ENTITY_ENDERMEN_AMBIENT;
	public static final Sound ENTITY_ENDERMEN_DEATH;
	public static final Sound ENTITY_ENDERMEN_HURT;
	public static final Sound ENTITY_ENDERMEN_SCREAM;
	public static final Sound ENTITY_ENDERMEN_STARE;
	public static final Sound ENTITY_ENDERMEN_TELEPORT;
	public static final Sound ENTITY_ENDERMITE_AMBIENT;
	public static final Sound ENTITY_ENDERMITE_DEATH;
	public static final Sound ENTITY_ENDERMITE_HURT;
	public static final Sound ENTITY_ENDERMITE_STEP;
	public static final Sound ENTITY_ENDERPEARL_THROW;
	public static final Sound BLOCK_END_GATEWAY_SPAWN;
	public static final Sound ENTITY_EVOCATION_FANGS_ATTACK;
	public static final Sound ENTITY_EVOCATION_ILLAGER_AMBIENT;
	public static final Sound ENTITY_EVOCATION_ILLAGER_CAST_SPELL;
	public static final Sound ENTITY_EVOCATION_ILLAGER_DEATH;
	public static final Sound ENTITY_EVOCATION_ILLAGER_HURT;
	public static final Sound ENTITY_EVOCATION_ILLAGER_PREPARE_ATTACK;
	public static final Sound ENTITY_EVOCATION_ILLAGER_PREPARE_SUMMON;
	public static final Sound ENTITY_EVOCATION_ILLAGER_PREPARE_WOLOLO;
	public static final Sound ENTITY_EXPERIENCE_BOTTLE_THROW;
	public static final Sound ENTITY_EXPERIENCE_ORB_PICKUP;
	public static final Sound BLOCK_FENCE_GATE_CLOSE;
	public static final Sound BLOCK_FENCE_GATE_OPEN;
	public static final Sound ITEM_FIRECHARGE_USE;
	public static final Sound ENTITY_FIREWORK_BLAST;
	public static final Sound ENTITY_FIREWORK_BLAST_FAR;
	public static final Sound ENTITY_FIREWORK_LARGE_BLAST;
	public static final Sound ENTITY_FIREWORK_LARGE_BLAST_FAR;
	public static final Sound ENTITY_FIREWORK_LAUNCH;
	public static final Sound ENTITY_FIREWORK_SHOOT;
	public static final Sound ENTITY_FIREWORK_TWINKLE;
	public static final Sound ENTITY_FIREWORK_TWINKLE_FAR;
	public static final Sound BLOCK_FIRE_AMBIENT;
	public static final Sound BLOCK_FIRE_EXTINGUISH;
	public static final Sound ITEM_FLINTANDSTEEL_USE;
	public static final Sound BLOCK_FURNACE_FIRE_CRACKLE;
	public static final Sound ENTITY_GENERIC_BIG_FALL;
	public static final Sound ENTITY_GENERIC_BURN;
	public static final Sound ENTITY_GENERIC_DEATH;
	public static final Sound ENTITY_GENERIC_DRINK;
	public static final Sound ENTITY_GENERIC_EAT;
	public static final Sound ENTITY_GENERIC_EXPLODE;
	public static final Sound ENTITY_GENERIC_EXTINGUISH_FIRE;
	public static final Sound ENTITY_GENERIC_HURT;
	public static final Sound ENTITY_GENERIC_SMALL_FALL;
	public static final Sound ENTITY_GENERIC_SPLASH;
	public static final Sound ENTITY_GENERIC_SWIM;
	public static final Sound ENTITY_GHAST_AMBIENT;
	public static final Sound ENTITY_GHAST_DEATH;
	public static final Sound ENTITY_GHAST_HURT;
	public static final Sound ENTITY_GHAST_SCREAM;
	public static final Sound ENTITY_GHAST_SHOOT;
	public static final Sound ENTITY_GHAST_WARN;
	public static final Sound BLOCK_GLASS_BREAK;
	public static final Sound BLOCK_GLASS_FALL;
	public static final Sound BLOCK_GLASS_HIT;
	public static final Sound BLOCK_GLASS_PLACE;
	public static final Sound BLOCK_GLASS_STEP;
	public static final Sound BLOCK_GRASS_BREAK;
	public static final Sound BLOCK_GRASS_FALL;
	public static final Sound BLOCK_GRASS_HIT;
	public static final Sound BLOCK_GRASS_PLACE;
	public static final Sound BLOCK_GRASS_STEP;
	public static final Sound BLOCK_GRAVEL_BREAK;
	public static final Sound BLOCK_GRAVEL_FALL;
	public static final Sound BLOCK_GRAVEL_HIT;
	public static final Sound BLOCK_GRAVEL_PLACE;
	public static final Sound BLOCK_GRAVEL_STEP;
	public static final Sound ENTITY_GUARDIAN_AMBIENT;
	public static final Sound ENTITY_GUARDIAN_AMBIENT_LAND;
	public static final Sound ENTITY_GUARDIAN_ATTACK;
	public static final Sound ENTITY_GUARDIAN_DEATH;
	public static final Sound ENTITY_GUARDIAN_DEATH_LAND;
	public static final Sound ENTITY_GUARDIAN_FLOP;
	public static final Sound ENTITY_GUARDIAN_HURT;
	public static final Sound ENTITY_GUARDIAN_HURT_LAND;
	public static final Sound ITEM_HOE_TILL;
	public static final Sound ENTITY_HORSE_AMBIENT;
	public static final Sound ENTITY_HORSE_ANGRY;
	public static final Sound ENTITY_HORSE_ARMOR;
	public static final Sound ENTITY_HORSE_BREATHE;
	public static final Sound ENTITY_HORSE_DEATH;
	public static final Sound ENTITY_HORSE_EAT;
	public static final Sound ENTITY_HORSE_GALLOP;
	public static final Sound ENTITY_HORSE_HURT;
	public static final Sound ENTITY_HORSE_JUMP;
	public static final Sound ENTITY_HORSE_LAND;
	public static final Sound ENTITY_HORSE_SADDLE;
	public static final Sound ENTITY_HORSE_STEP;
	public static final Sound ENTITY_HORSE_STEP_WOOD;
	public static final Sound ENTITY_HOSTILE_BIG_FALL;
	public static final Sound ENTITY_HOSTILE_DEATH;
	public static final Sound ENTITY_HOSTILE_HURT;
	public static final Sound ENTITY_HOSTILE_SMALL_FALL;
	public static final Sound ENTITY_HOSTILE_SPLASH;
	public static final Sound ENTITY_HOSTILE_SWIM;
	public static final Sound ENTITY_HUSK_AMBIENT;
	public static final Sound ENTITY_HUSK_DEATH;
	public static final Sound ENTITY_HUSK_HURT;
	public static final Sound ENTITY_HUSK_STEP;
	public static final Sound ENTITY_IRONGOLEM_ATTACK;
	public static final Sound ENTITY_IRONGOLEM_DEATH;
	public static final Sound ENTITY_IRONGOLEM_HURT;
	public static final Sound ENTITY_IRONGOLEM_STEP;
	public static final Sound BLOCK_IRON_DOOR_CLOSE;
	public static final Sound BLOCK_IRON_DOOR_OPEN;
	public static final Sound BLOCK_IRON_TRAPDOOR_CLOSE;
	public static final Sound BLOCK_IRON_TRAPDOOR_OPEN;
	public static final Sound ENTITY_ITEMFRAME_ADD_ITEM;
	public static final Sound ENTITY_ITEMFRAME_BREAK;
	public static final Sound ENTITY_ITEMFRAME_PLACE;
	public static final Sound ENTITY_ITEMFRAME_REMOVE_ITEM;
	public static final Sound ENTITY_ITEMFRAME_ROTATE_ITEM;
	public static final Sound ENTITY_ITEM_BREAK;
	public static final Sound ENTITY_ITEM_PICKUP;
	public static final Sound BLOCK_LADDER_BREAK;
	public static final Sound BLOCK_LADDER_FALL;
	public static final Sound BLOCK_LADDER_HIT;
	public static final Sound BLOCK_LADDER_PLACE;
	public static final Sound BLOCK_LADDER_STEP;
	public static final Sound BLOCK_LAVA_AMBIENT;
	public static final Sound BLOCK_LAVA_EXTINGUISH;
	public static final Sound BLOCK_LAVA_POP;
	public static final Sound ENTITY_LEASHKNOT_BREAK;
	public static final Sound ENTITY_LEASHKNOT_PLACE;
	public static final Sound BLOCK_LEVER_CLICK;
	public static final Sound ENTITY_LIGHTNING_IMPACT;
	public static final Sound ENTITY_LIGHTNING_THUNDER;
	public static final Sound ENTITY_LINGERINGPOTION_THROW;
	public static final Sound ENTITY_LLAMA_AMBIENT;
	public static final Sound ENTITY_LLAMA_ANGRY;
	public static final Sound ENTITY_LLAMA_CHEST;
	public static final Sound ENTITY_LLAMA_DEATH;
	public static final Sound ENTITY_LLAMA_EAT;
	public static final Sound ENTITY_LLAMA_HURT;
	public static final Sound ENTITY_LLAMA_SPIT;
	public static final Sound ENTITY_LLAMA_STEP;
	public static final Sound ENTITY_LLAMA_SWAG;
	public static final Sound ENTITY_MAGMACUBE_DEATH;
	public static final Sound ENTITY_MAGMACUBE_HURT;
	public static final Sound ENTITY_MAGMACUBE_JUMP;
	public static final Sound ENTITY_MAGMACUBE_SQUISH;
	public static final Sound BLOCK_METAL_BREAK;
	public static final Sound BLOCK_METAL_FALL;
	public static final Sound BLOCK_METAL_HIT;
	public static final Sound BLOCK_METAL_PLACE;
	public static final Sound BLOCK_METAL_PRESSUREPLATE_CLICK_OFF;
	public static final Sound BLOCK_METAL_PRESSUREPLATE_CLICK_ON;
	public static final Sound BLOCK_METAL_STEP;
	public static final Sound ENTITY_MINECART_INSIDE;
	public static final Sound ENTITY_MINECART_RIDING;
	public static final Sound ENTITY_MOOSHROOM_SHEAR;
	public static final Sound ENTITY_MULE_AMBIENT;
	public static final Sound ENTITY_MULE_CHEST;
	public static final Sound ENTITY_MULE_DEATH;
	public static final Sound ENTITY_MULE_HURT;
	public static final Sound MUSIC_CREATIVE;
	public static final Sound MUSIC_CREDITS;
	public static final Sound MUSIC_DRAGON;
	public static final Sound MUSIC_END;
	public static final Sound MUSIC_GAME;
	public static final Sound MUSIC_MENU;
	public static final Sound MUSIC_NETHER;
	public static final Sound BLOCK_NOTE_BASEDRUM;
	public static final Sound BLOCK_NOTE_BASS;
	public static final Sound BLOCK_NOTE_HARP;
	public static final Sound BLOCK_NOTE_HAT;
	public static final Sound BLOCK_NOTE_PLING;
	public static final Sound BLOCK_NOTE_SNARE;
	public static final Sound ENTITY_PAINTING_BREAK;
	public static final Sound ENTITY_PAINTING_PLACE;
	public static final Sound ENTITY_PIG_AMBIENT;
	public static final Sound ENTITY_PIG_DEATH;
	public static final Sound ENTITY_PIG_HURT;
	public static final Sound ENTITY_PIG_SADDLE;
	public static final Sound ENTITY_PIG_STEP;
	public static final Sound BLOCK_PISTON_CONTRACT;
	public static final Sound BLOCK_PISTON_EXTEND;
	public static final Sound ENTITY_PLAYER_ATTACK_CRIT;
	public static final Sound ENTITY_PLAYER_ATTACK_KNOCKBACK;
	public static final Sound ENTITY_PLAYER_ATTACK_NODAMAGE;
	public static final Sound ENTITY_PLAYER_ATTACK_STRONG;
	public static final Sound ENTITY_PLAYER_ATTACK_SWEEP;
	public static final Sound ENTITY_PLAYER_ATTACK_WEAK;
	public static final Sound ENTITY_PLAYER_BIG_FALL;
	public static final Sound ENTITY_PLAYER_BREATH;
	public static final Sound ENTITY_PLAYER_BURP;
	public static final Sound ENTITY_PLAYER_DEATH;
	public static final Sound ENTITY_PLAYER_HURT;
	public static final Sound ENTITY_PLAYER_LEVELUP;
	public static final Sound ENTITY_PLAYER_SMALL_FALL;
	public static final Sound ENTITY_PLAYER_SPLASH;
	public static final Sound ENTITY_PLAYER_SWIM;
	public static final Sound ENTITY_POLAR_BEAR_AMBIENT;
	public static final Sound ENTITY_POLAR_BEAR_BABY_AMBIENT;
	public static final Sound ENTITY_POLAR_BEAR_DEATH;
	public static final Sound ENTITY_POLAR_BEAR_HURT;
	public static final Sound ENTITY_POLAR_BEAR_STEP;
	public static final Sound ENTITY_POLAR_BEAR_WARNING;
	public static final Sound BLOCK_PORTAL_AMBIENT;
	public static final Sound BLOCK_PORTAL_TRAVEL;
	public static final Sound BLOCK_PORTAL_TRIGGER;
	public static final Sound ENTITY_RABBIT_AMBIENT;
	public static final Sound ENTITY_RABBIT_ATTACK;
	public static final Sound ENTITY_RABBIT_DEATH;
	public static final Sound ENTITY_RABBIT_HURT;
	public static final Sound ENTITY_RABBIT_JUMP;
	public static final Sound RECORD_11;
	public static final Sound RECORD_13;
	public static final Sound RECORD_BLOCKS;
	public static final Sound RECORD_CAT;
	public static final Sound RECORD_CHIRP;
	public static final Sound RECORD_FAR;
	public static final Sound RECORD_MALL;
	public static final Sound RECORD_MELLOHI;
	public static final Sound RECORD_STAL;
	public static final Sound RECORD_STRAD;
	public static final Sound RECORD_WAIT;
	public static final Sound RECORD_WARD;
	public static final Sound BLOCK_REDSTONE_TORCH_BURNOUT;
	public static final Sound BLOCK_SAND_BREAK;
	public static final Sound BLOCK_SAND_FALL;
	public static final Sound BLOCK_SAND_HIT;
	public static final Sound BLOCK_SAND_PLACE;
	public static final Sound BLOCK_SAND_STEP;
	public static final Sound ENTITY_SHEEP_AMBIENT;
	public static final Sound ENTITY_SHEEP_DEATH;
	public static final Sound ENTITY_SHEEP_HURT;
	public static final Sound ENTITY_SHEEP_SHEAR;
	public static final Sound ENTITY_SHEEP_STEP;
	public static final Sound ITEM_SHIELD_BLOCK;
	public static final Sound ITEM_SHIELD_BREAK;
	public static final Sound ITEM_SHOVEL_FLATTEN;
	public static final Sound ENTITY_SHULKER_AMBIENT;
	public static final Sound BLOCK_SHULKER_BOX_CLOSE;
	public static final Sound BLOCK_SHULKER_BOX_OPEN;
	public static final Sound ENTITY_SHULKER_BULLET_HIT;
	public static final Sound ENTITY_SHULKER_BULLET_HURT;
	public static final Sound ENTITY_SHULKER_CLOSE;
	public static final Sound ENTITY_SHULKER_DEATH;
	public static final Sound ENTITY_SHULKER_HURT;
	public static final Sound ENTITY_SHULKER_HURT_CLOSED;
	public static final Sound ENTITY_SHULKER_OPEN;
	public static final Sound ENTITY_SHULKER_SHOOT;
	public static final Sound ENTITY_SHULKER_TELEPORT;
	public static final Sound ENTITY_SILVERFISH_AMBIENT;
	public static final Sound ENTITY_SILVERFISH_DEATH;
	public static final Sound ENTITY_SILVERFISH_HURT;
	public static final Sound ENTITY_SILVERFISH_STEP;
	public static final Sound ENTITY_SKELETON_AMBIENT;
	public static final Sound ENTITY_SKELETON_DEATH;
	public static final Sound ENTITY_SKELETON_HORSE_AMBIENT;
	public static final Sound ENTITY_SKELETON_HORSE_DEATH;
	public static final Sound ENTITY_SKELETON_HORSE_HURT;
	public static final Sound ENTITY_SKELETON_HURT;
	public static final Sound ENTITY_SKELETON_SHOOT;
	public static final Sound ENTITY_SKELETON_STEP;
	public static final Sound ENTITY_SLIME_ATTACK;
	public static final Sound BLOCK_SLIME_BREAK;
	public static final Sound ENTITY_SLIME_DEATH;
	public static final Sound BLOCK_SLIME_FALL;
	public static final Sound BLOCK_SLIME_HIT;
	public static final Sound ENTITY_SLIME_HURT;
	public static final Sound ENTITY_SLIME_JUMP;
	public static final Sound BLOCK_SLIME_PLACE;
	public static final Sound ENTITY_SLIME_SQUISH;
	public static final Sound BLOCK_SLIME_STEP;
	public static final Sound ENTITY_SMALL_MAGMACUBE_DEATH;
	public static final Sound ENTITY_SMALL_MAGMACUBE_HURT;
	public static final Sound ENTITY_SMALL_MAGMACUBE_SQUISH;
	public static final Sound ENTITY_SMALL_SLIME_DEATH;
	public static final Sound ENTITY_SMALL_SLIME_HURT;
	public static final Sound ENTITY_SMALL_SLIME_JUMP;
	public static final Sound ENTITY_SMALL_SLIME_SQUISH;
	public static final Sound ENTITY_SNOWBALL_THROW;
	public static final Sound ENTITY_SNOWMAN_AMBIENT;
	public static final Sound ENTITY_SNOWMAN_DEATH;
	public static final Sound ENTITY_SNOWMAN_HURT;
	public static final Sound ENTITY_SNOWMAN_SHOOT;
	public static final Sound BLOCK_SNOW_BREAK;
	public static final Sound BLOCK_SNOW_FALL;
	public static final Sound BLOCK_SNOW_HIT;
	public static final Sound BLOCK_SNOW_PLACE;
	public static final Sound BLOCK_SNOW_STEP;
	public static final Sound ENTITY_SPIDER_AMBIENT;
	public static final Sound ENTITY_SPIDER_DEATH;
	public static final Sound ENTITY_SPIDER_HURT;
	public static final Sound ENTITY_SPIDER_STEP;
	public static final Sound ENTITY_SPLASH_POTION_BREAK;
	public static final Sound ENTITY_SPLASH_POTION_THROW;
	public static final Sound ENTITY_SQUID_AMBIENT;
	public static final Sound ENTITY_SQUID_DEATH;
	public static final Sound ENTITY_SQUID_HURT;
	public static final Sound BLOCK_STONE_BREAK;
	public static final Sound BLOCK_STONE_BUTTON_CLICK_OFF;
	public static final Sound BLOCK_STONE_BUTTON_CLICK_ON;
	public static final Sound BLOCK_STONE_FALL;
	public static final Sound BLOCK_STONE_HIT;
	public static final Sound BLOCK_STONE_PLACE;
	public static final Sound BLOCK_STONE_PRESSUREPLATE_CLICK_OFF;
	public static final Sound BLOCK_STONE_PRESSUREPLATE_CLICK_ON;
	public static final Sound BLOCK_STONE_STEP;
	public static final Sound ENTITY_STRAY_AMBIENT;
	public static final Sound ENTITY_STRAY_DEATH;
	public static final Sound ENTITY_STRAY_HURT;
	public static final Sound ENTITY_STRAY_STEP;
	public static final Sound ENCHANT_THORNS_HIT;
	public static final Sound ENTITY_TNT_PRIMED;
	public static final Sound ITEM_TOTEM_USE;
	public static final Sound BLOCK_TRIPWIRE_ATTACH;
	public static final Sound BLOCK_TRIPWIRE_CLICK_OFF;
	public static final Sound BLOCK_TRIPWIRE_CLICK_ON;
	public static final Sound BLOCK_TRIPWIRE_DETACH;
	public static final Sound UI_BUTTON_CLICK;
	public static final Sound ENTITY_VEX_AMBIENT;
	public static final Sound ENTITY_VEX_CHARGE;
	public static final Sound ENTITY_VEX_DEATH;
	public static final Sound ENTITY_VEX_HURT;
	public static final Sound ENTITY_VILLAGER_AMBIENT;
	public static final Sound ENTITY_VILLAGER_DEATH;
	public static final Sound ENTITY_VILLAGER_HURT;
	public static final Sound ENTITY_VILLAGER_NO;
	public static final Sound ENTITY_VILLAGER_TRADING;
	public static final Sound ENTITY_VILLAGER_YES;
	public static final Sound ENTITY_VINDICATION_ILLAGER_AMBIENT;
	public static final Sound ENTITY_VINDICATION_ILLAGER_DEATH;
	public static final Sound ENTITY_VINDICATION_ILLAGER_HURT;
	public static final Sound BLOCK_WATERLILY_PLACE;
	public static final Sound BLOCK_WATER_AMBIENT;
	public static final Sound WEATHER_RAIN;
	public static final Sound WEATHER_RAIN_ABOVE;
	public static final Sound ENTITY_WITCH_AMBIENT;
	public static final Sound ENTITY_WITCH_DEATH;
	public static final Sound ENTITY_WITCH_DRINK;
	public static final Sound ENTITY_WITCH_HURT;
	public static final Sound ENTITY_WITCH_THROW;
	public static final Sound ENTITY_WITHER_AMBIENT;
	public static final Sound ENTITY_WITHER_BREAK_BLOCK;
	public static final Sound ENTITY_WITHER_DEATH;
	public static final Sound ENTITY_WITHER_HURT;
	public static final Sound ENTITY_WITHER_SHOOT;
	public static final Sound ENTITY_WITHER_SKELETON_AMBIENT;
	public static final Sound ENTITY_WITHER_SKELETON_DEATH;
	public static final Sound ENTITY_WITHER_SKELETON_HURT;
	public static final Sound ENTITY_WITHER_SKELETON_STEP;
	public static final Sound ENTITY_WITHER_SPAWN;
	public static final Sound ENTITY_WOLF_AMBIENT;
	public static final Sound ENTITY_WOLF_DEATH;
	public static final Sound ENTITY_WOLF_GROWL;
	public static final Sound ENTITY_WOLF_HOWL;
	public static final Sound ENTITY_WOLF_HURT;
	public static final Sound ENTITY_WOLF_PANT;
	public static final Sound ENTITY_WOLF_SHAKE;
	public static final Sound ENTITY_WOLF_STEP;
	public static final Sound ENTITY_WOLF_WHINE;
	public static final Sound BLOCK_WOODEN_DOOR_CLOSE;
	public static final Sound BLOCK_WOODEN_DOOR_OPEN;
	public static final Sound BLOCK_WOODEN_TRAPDOOR_CLOSE;
	public static final Sound BLOCK_WOODEN_TRAPDOOR_OPEN;
	public static final Sound BLOCK_WOOD_BREAK;
	public static final Sound BLOCK_WOOD_BUTTON_CLICK_OFF;
	public static final Sound BLOCK_WOOD_BUTTON_CLICK_ON;
	public static final Sound BLOCK_WOOD_FALL;
	public static final Sound BLOCK_WOOD_HIT;
	public static final Sound BLOCK_WOOD_PLACE;
	public static final Sound BLOCK_WOOD_PRESSUREPLATE_CLICK_OFF;
	public static final Sound BLOCK_WOOD_PRESSUREPLATE_CLICK_ON;
	public static final Sound BLOCK_WOOD_STEP;
	public static final Sound ENTITY_ZOMBIE_AMBIENT;
	public static final Sound ENTITY_ZOMBIE_ATTACK_DOOR_WOOD;
	public static final Sound ENTITY_ZOMBIE_ATTACK_IRON_DOOR;
	public static final Sound ENTITY_ZOMBIE_BREAK_DOOR_WOOD;
	public static final Sound ENTITY_ZOMBIE_DEATH;
	public static final Sound ENTITY_ZOMBIE_HORSE_AMBIENT;
	public static final Sound ENTITY_ZOMBIE_HORSE_DEATH;
	public static final Sound ENTITY_ZOMBIE_HORSE_HURT;
	public static final Sound ENTITY_ZOMBIE_HURT;
	public static final Sound ENTITY_ZOMBIE_INFECT;
	public static final Sound ENTITY_ZOMBIE_PIG_AMBIENT;
	public static final Sound ENTITY_ZOMBIE_PIG_ANGRY;
	public static final Sound ENTITY_ZOMBIE_PIG_DEATH;
	public static final Sound ENTITY_ZOMBIE_PIG_HURT;
	public static final Sound ENTITY_ZOMBIE_STEP;
	public static final Sound ENTITY_ZOMBIE_VILLAGER_AMBIENT;
	public static final Sound ENTITY_ZOMBIE_VILLAGER_CONVERTED;
	public static final Sound ENTITY_ZOMBIE_VILLAGER_CURE;
	public static final Sound ENTITY_ZOMBIE_VILLAGER_DEATH;
	public static final Sound ENTITY_ZOMBIE_VILLAGER_HURT;
	public static final Sound ENTITY_ZOMBIE_VILLAGER_STEP;

	private static Sound get(String id) {
		Sound sound = Sound.REGISTRY.get(new Identifier(id));
		if (sound == null) {
			throw new IllegalStateException("Invalid Sound requested: " + id);
		} else {
			return sound;
		}
	}

	static {
		if (!Bootstrap.isInitialized()) {
			throw new RuntimeException("Accessed Sounds before Bootstrap!");
		} else {
			AMBIENT_CAVE = get("ambient.cave");
			BLOCK_ANVIL_BREAK = get("block.anvil.break");
			BLOCK_ANVIL_DESTROY = get("block.anvil.destroy");
			BLOCK_ANVIL_FALL = get("block.anvil.fall");
			BLOCK_ANVIL_HIT = get("block.anvil.hit");
			BLOCK_ANVIL_LAND = get("block.anvil.land");
			BLOCK_ANVIL_PLACE = get("block.anvil.place");
			BLOCK_ANVIL_STEP = get("block.anvil.step");
			BLOCK_ANVIL_USE = get("block.anvil.use");
			ENTITY_ARMORSTAND_BREAK = get("entity.armorstand.break");
			ENTITY_ARMORSTAND_FALL = get("entity.armorstand.fall");
			ENTITY_ARMORSTAND_HIT = get("entity.armorstand.hit");
			ENTITY_ARMORSTAND_PLACE = get("entity.armorstand.place");
			ITEM_ARMOR_EQUIP_CHAIN = get("item.armor.equip_chain");
			ITEM_ARMOR_EQUIP_DIAMOND = get("item.armor.equip_diamond");
			ITEM_ARMOR_EQUIP_ELYTRA = get("item.armor.equip_elytra");
			ITEM_ARMOR_EQUIP_GENERIC = get("item.armor.equip_generic");
			ITEM_ARMOR_EQUIP_GOLD = get("item.armor.equip_gold");
			ITEM_ARMOR_EQUIP_IRON = get("item.armor.equip_iron");
			ITEM_ARMOR_EQUIP_LEATHER = get("item.armor.equip_leather");
			ENTITY_ARROW_HIT = get("entity.arrow.hit");
			ENTITY_ARROW_HIT_PLAYER = get("entity.arrow.hit_player");
			ENTITY_ARROW_SHOOT = get("entity.arrow.shoot");
			ENTITY_BAT_AMBIENT = get("entity.bat.ambient");
			ENTITY_BAT_DEATH = get("entity.bat.death");
			ENTITY_BAT_HURT = get("entity.bat.hurt");
			ENTITY_BAT_LOOP = get("entity.bat.loop");
			ENTITY_BAT_TAKEOFF = get("entity.bat.takeoff");
			ENTITY_BLAZE_AMBIENT = get("entity.blaze.ambient");
			ENTITY_BLAZE_BURN = get("entity.blaze.burn");
			ENTITY_BLAZE_DEATH = get("entity.blaze.death");
			ENTITY_BLAZE_HURT = get("entity.blaze.hurt");
			ENTITY_BLAZE_SHOOT = get("entity.blaze.shoot");
			ENTITY_BOBBER_SPLASH = get("entity.bobber.splash");
			ENTITY_BOBBER_THROW = get("entity.bobber.throw");
			ITEM_BOTTLE_EMPTY = get("item.bottle.empty");
			ITEM_BOTTLE_FILL = get("item.bottle.fill");
			ITEM_BOTTLE_FILL_DRAGONBREATH = get("item.bottle.fill_dragonbreath");
			BLOCK_BREWING_STAND_BREW = get("block.brewing_stand.brew");
			ITEM_BUCKET_EMPTY = get("item.bucket.empty");
			ITEM_BUCKET_EMPTY_LAVA = get("item.bucket.empty_lava");
			ITEM_BUCKET_FILL = get("item.bucket.fill");
			ITEM_BUCKET_FILL_LAVA = get("item.bucket.fill_lava");
			ENTITY_CAT_AMBIENT = get("entity.cat.ambient");
			ENTITY_CAT_DEATH = get("entity.cat.death");
			ENTITY_CAT_HISS = get("entity.cat.hiss");
			ENTITY_CAT_HURT = get("entity.cat.hurt");
			ENTITY_CAT_PURR = get("entity.cat.purr");
			ENTITY_CAT_PURREOW = get("entity.cat.purreow");
			BLOCK_CHEST_CLOSE = get("block.chest.close");
			BLOCK_CHEST_LOCKED = get("block.chest.locked");
			BLOCK_CHEST_OPEN = get("block.chest.open");
			ENTITY_CHICKEN_AMBIENT = get("entity.chicken.ambient");
			ENTITY_CHICKEN_DEATH = get("entity.chicken.death");
			ENTITY_CHICKEN_EGG = get("entity.chicken.egg");
			ENTITY_CHICKEN_HURT = get("entity.chicken.hurt");
			ENTITY_CHICKEN_STEP = get("entity.chicken.step");
			BLOCK_CHORUS_FLOWER_DEATH = get("block.chorus_flower.death");
			BLOCK_CHORUS_FLOWER_GROW = get("block.chorus_flower.grow");
			ITEM_CHORUS_FRUIT_TELEPORT = get("item.chorus_fruit.teleport");
			BLOCK_CLOTH_BREAK = get("block.cloth.break");
			BLOCK_CLOTH_FALL = get("block.cloth.fall");
			BLOCK_CLOTH_HIT = get("block.cloth.hit");
			BLOCK_CLOTH_PLACE = get("block.cloth.place");
			BLOCK_CLOTH_STEP = get("block.cloth.step");
			BLOCK_COMPARATOR_CLICK = get("block.comparator.click");
			ENTITY_COW_AMBIENT = get("entity.cow.ambient");
			ENTITY_COW_DEATH = get("entity.cow.death");
			ENTITY_COW_HURT = get("entity.cow.hurt");
			ENTITY_COW_MILK = get("entity.cow.milk");
			ENTITY_COW_STEP = get("entity.cow.step");
			ENTITY_CREEPER_DEATH = get("entity.creeper.death");
			ENTITY_CREEPER_HURT = get("entity.creeper.hurt");
			ENTITY_CREEPER_PRIMED = get("entity.creeper.primed");
			BLOCK_DISPENSER_DISPENSE = get("block.dispenser.dispense");
			BLOCK_DISPENSER_FAIL = get("block.dispenser.fail");
			BLOCK_DISPENSER_LAUNCH = get("block.dispenser.launch");
			ENTITY_DONKEY_AMBIENT = get("entity.donkey.ambient");
			ENTITY_DONKEY_ANGRY = get("entity.donkey.angry");
			ENTITY_DONKEY_CHEST = get("entity.donkey.chest");
			ENTITY_DONKEY_DEATH = get("entity.donkey.death");
			ENTITY_DONKEY_HURT = get("entity.donkey.hurt");
			ENTITY_EGG_THROW = get("entity.egg.throw");
			ENTITY_ELDER_GUARDIAN_AMBIENT = get("entity.elder_guardian.ambient");
			ENTITY_ELDER_GUARDIAN_AMBIENT_LAND = get("entity.elder_guardian.ambient_land");
			ENTITY_ELDER_GUARDIAN_CURSE = get("entity.elder_guardian.curse");
			ENTITY_ELDER_GUARDIAN_DEATH = get("entity.elder_guardian.death");
			ENTITY_ELDER_GUARDIAN_DEATH_LAND = get("entity.elder_guardian.death_land");
			ENTITY_ELDER_GUARDIAN_FLOP = get("entity.elder_guardian.flop");
			ENTITY_ELDER_GUARDIAN_HURT = get("entity.elder_guardian.hurt");
			ENTITY_ELDER_GUARDIAN_HURT_LAND = get("entity.elder_guardian.hurt_land");
			ITEM_ELYTRA_FLYING = get("item.elytra.flying");
			BLOCK_ENCHANTMENT_TABLE_USE = get("block.enchantment_table.use");
			BLOCK_ENDERCHEST_CLOSE = get("block.enderchest.close");
			BLOCK_ENDERCHEST_OPEN = get("block.enderchest.open");
			ENTITY_ENDERDRAGON_AMBIENT = get("entity.enderdragon.ambient");
			ENTITY_ENDERDRAGON_DEATH = get("entity.enderdragon.death");
			ENTITY_ENDERDRAGON_FIREBALL_EXPLODE = get("entity.enderdragon_fireball.explode");
			ENTITY_ENDERDRAGON_FLAP = get("entity.enderdragon.flap");
			ENTITY_ENDERDRAGON_GROWL = get("entity.enderdragon.growl");
			ENTITY_ENDERDRAGON_HURT = get("entity.enderdragon.hurt");
			ENTITY_ENDERDRAGON_SHOOT = get("entity.enderdragon.shoot");
			ENTITY_ENDEREYE_LAUNCH = get("entity.endereye.launch");
			ENTITY_ENDERMEN_AMBIENT = get("entity.endermen.ambient");
			ENTITY_ENDERMEN_DEATH = get("entity.endermen.death");
			ENTITY_ENDERMEN_HURT = get("entity.endermen.hurt");
			ENTITY_ENDERMEN_SCREAM = get("entity.endermen.scream");
			ENTITY_ENDERMEN_STARE = get("entity.endermen.stare");
			ENTITY_ENDERMEN_TELEPORT = get("entity.endermen.teleport");
			ENTITY_ENDERMITE_AMBIENT = get("entity.endermite.ambient");
			ENTITY_ENDERMITE_DEATH = get("entity.endermite.death");
			ENTITY_ENDERMITE_HURT = get("entity.endermite.hurt");
			ENTITY_ENDERMITE_STEP = get("entity.endermite.step");
			ENTITY_ENDERPEARL_THROW = get("entity.enderpearl.throw");
			BLOCK_END_GATEWAY_SPAWN = get("block.end_gateway.spawn");
			ENTITY_EVOCATION_FANGS_ATTACK = get("entity.evocation_fangs.attack");
			ENTITY_EVOCATION_ILLAGER_AMBIENT = get("entity.evocation_illager.ambient");
			ENTITY_EVOCATION_ILLAGER_CAST_SPELL = get("entity.evocation_illager.cast_spell");
			ENTITY_EVOCATION_ILLAGER_DEATH = get("entity.evocation_illager.death");
			ENTITY_EVOCATION_ILLAGER_HURT = get("entity.evocation_illager.hurt");
			ENTITY_EVOCATION_ILLAGER_PREPARE_ATTACK = get("entity.evocation_illager.prepare_attack");
			ENTITY_EVOCATION_ILLAGER_PREPARE_SUMMON = get("entity.evocation_illager.prepare_summon");
			ENTITY_EVOCATION_ILLAGER_PREPARE_WOLOLO = get("entity.evocation_illager.prepare_wololo");
			ENTITY_EXPERIENCE_BOTTLE_THROW = get("entity.experience_bottle.throw");
			ENTITY_EXPERIENCE_ORB_PICKUP = get("entity.experience_orb.pickup");
			BLOCK_FENCE_GATE_CLOSE = get("block.fence_gate.close");
			BLOCK_FENCE_GATE_OPEN = get("block.fence_gate.open");
			ITEM_FIRECHARGE_USE = get("item.firecharge.use");
			ENTITY_FIREWORK_BLAST = get("entity.firework.blast");
			ENTITY_FIREWORK_BLAST_FAR = get("entity.firework.blast_far");
			ENTITY_FIREWORK_LARGE_BLAST = get("entity.firework.large_blast");
			ENTITY_FIREWORK_LARGE_BLAST_FAR = get("entity.firework.large_blast_far");
			ENTITY_FIREWORK_LAUNCH = get("entity.firework.launch");
			ENTITY_FIREWORK_SHOOT = get("entity.firework.shoot");
			ENTITY_FIREWORK_TWINKLE = get("entity.firework.twinkle");
			ENTITY_FIREWORK_TWINKLE_FAR = get("entity.firework.twinkle_far");
			BLOCK_FIRE_AMBIENT = get("block.fire.ambient");
			BLOCK_FIRE_EXTINGUISH = get("block.fire.extinguish");
			ITEM_FLINTANDSTEEL_USE = get("item.flintandsteel.use");
			BLOCK_FURNACE_FIRE_CRACKLE = get("block.furnace.fire_crackle");
			ENTITY_GENERIC_BIG_FALL = get("entity.generic.big_fall");
			ENTITY_GENERIC_BURN = get("entity.generic.burn");
			ENTITY_GENERIC_DEATH = get("entity.generic.death");
			ENTITY_GENERIC_DRINK = get("entity.generic.drink");
			ENTITY_GENERIC_EAT = get("entity.generic.eat");
			ENTITY_GENERIC_EXPLODE = get("entity.generic.explode");
			ENTITY_GENERIC_EXTINGUISH_FIRE = get("entity.generic.extinguish_fire");
			ENTITY_GENERIC_HURT = get("entity.generic.hurt");
			ENTITY_GENERIC_SMALL_FALL = get("entity.generic.small_fall");
			ENTITY_GENERIC_SPLASH = get("entity.generic.splash");
			ENTITY_GENERIC_SWIM = get("entity.generic.swim");
			ENTITY_GHAST_AMBIENT = get("entity.ghast.ambient");
			ENTITY_GHAST_DEATH = get("entity.ghast.death");
			ENTITY_GHAST_HURT = get("entity.ghast.hurt");
			ENTITY_GHAST_SCREAM = get("entity.ghast.scream");
			ENTITY_GHAST_SHOOT = get("entity.ghast.shoot");
			ENTITY_GHAST_WARN = get("entity.ghast.warn");
			BLOCK_GLASS_BREAK = get("block.glass.break");
			BLOCK_GLASS_FALL = get("block.glass.fall");
			BLOCK_GLASS_HIT = get("block.glass.hit");
			BLOCK_GLASS_PLACE = get("block.glass.place");
			BLOCK_GLASS_STEP = get("block.glass.step");
			BLOCK_GRASS_BREAK = get("block.grass.break");
			BLOCK_GRASS_FALL = get("block.grass.fall");
			BLOCK_GRASS_HIT = get("block.grass.hit");
			BLOCK_GRASS_PLACE = get("block.grass.place");
			BLOCK_GRASS_STEP = get("block.grass.step");
			BLOCK_GRAVEL_BREAK = get("block.gravel.break");
			BLOCK_GRAVEL_FALL = get("block.gravel.fall");
			BLOCK_GRAVEL_HIT = get("block.gravel.hit");
			BLOCK_GRAVEL_PLACE = get("block.gravel.place");
			BLOCK_GRAVEL_STEP = get("block.gravel.step");
			ENTITY_GUARDIAN_AMBIENT = get("entity.guardian.ambient");
			ENTITY_GUARDIAN_AMBIENT_LAND = get("entity.guardian.ambient_land");
			ENTITY_GUARDIAN_ATTACK = get("entity.guardian.attack");
			ENTITY_GUARDIAN_DEATH = get("entity.guardian.death");
			ENTITY_GUARDIAN_DEATH_LAND = get("entity.guardian.death_land");
			ENTITY_GUARDIAN_FLOP = get("entity.guardian.flop");
			ENTITY_GUARDIAN_HURT = get("entity.guardian.hurt");
			ENTITY_GUARDIAN_HURT_LAND = get("entity.guardian.hurt_land");
			ITEM_HOE_TILL = get("item.hoe.till");
			ENTITY_HORSE_AMBIENT = get("entity.horse.ambient");
			ENTITY_HORSE_ANGRY = get("entity.horse.angry");
			ENTITY_HORSE_ARMOR = get("entity.horse.armor");
			ENTITY_HORSE_BREATHE = get("entity.horse.breathe");
			ENTITY_HORSE_DEATH = get("entity.horse.death");
			ENTITY_HORSE_EAT = get("entity.horse.eat");
			ENTITY_HORSE_GALLOP = get("entity.horse.gallop");
			ENTITY_HORSE_HURT = get("entity.horse.hurt");
			ENTITY_HORSE_JUMP = get("entity.horse.jump");
			ENTITY_HORSE_LAND = get("entity.horse.land");
			ENTITY_HORSE_SADDLE = get("entity.horse.saddle");
			ENTITY_HORSE_STEP = get("entity.horse.step");
			ENTITY_HORSE_STEP_WOOD = get("entity.horse.step_wood");
			ENTITY_HOSTILE_BIG_FALL = get("entity.hostile.big_fall");
			ENTITY_HOSTILE_DEATH = get("entity.hostile.death");
			ENTITY_HOSTILE_HURT = get("entity.hostile.hurt");
			ENTITY_HOSTILE_SMALL_FALL = get("entity.hostile.small_fall");
			ENTITY_HOSTILE_SPLASH = get("entity.hostile.splash");
			ENTITY_HOSTILE_SWIM = get("entity.hostile.swim");
			ENTITY_HUSK_AMBIENT = get("entity.husk.ambient");
			ENTITY_HUSK_DEATH = get("entity.husk.death");
			ENTITY_HUSK_HURT = get("entity.husk.hurt");
			ENTITY_HUSK_STEP = get("entity.husk.step");
			ENTITY_IRONGOLEM_ATTACK = get("entity.irongolem.attack");
			ENTITY_IRONGOLEM_DEATH = get("entity.irongolem.death");
			ENTITY_IRONGOLEM_HURT = get("entity.irongolem.hurt");
			ENTITY_IRONGOLEM_STEP = get("entity.irongolem.step");
			BLOCK_IRON_DOOR_CLOSE = get("block.iron_door.close");
			BLOCK_IRON_DOOR_OPEN = get("block.iron_door.open");
			BLOCK_IRON_TRAPDOOR_CLOSE = get("block.iron_trapdoor.close");
			BLOCK_IRON_TRAPDOOR_OPEN = get("block.iron_trapdoor.open");
			ENTITY_ITEMFRAME_ADD_ITEM = get("entity.itemframe.add_item");
			ENTITY_ITEMFRAME_BREAK = get("entity.itemframe.break");
			ENTITY_ITEMFRAME_PLACE = get("entity.itemframe.place");
			ENTITY_ITEMFRAME_REMOVE_ITEM = get("entity.itemframe.remove_item");
			ENTITY_ITEMFRAME_ROTATE_ITEM = get("entity.itemframe.rotate_item");
			ENTITY_ITEM_BREAK = get("entity.item.break");
			ENTITY_ITEM_PICKUP = get("entity.item.pickup");
			BLOCK_LADDER_BREAK = get("block.ladder.break");
			BLOCK_LADDER_FALL = get("block.ladder.fall");
			BLOCK_LADDER_HIT = get("block.ladder.hit");
			BLOCK_LADDER_PLACE = get("block.ladder.place");
			BLOCK_LADDER_STEP = get("block.ladder.step");
			BLOCK_LAVA_AMBIENT = get("block.lava.ambient");
			BLOCK_LAVA_EXTINGUISH = get("block.lava.extinguish");
			BLOCK_LAVA_POP = get("block.lava.pop");
			ENTITY_LEASHKNOT_BREAK = get("entity.leashknot.break");
			ENTITY_LEASHKNOT_PLACE = get("entity.leashknot.place");
			BLOCK_LEVER_CLICK = get("block.lever.click");
			ENTITY_LIGHTNING_IMPACT = get("entity.lightning.impact");
			ENTITY_LIGHTNING_THUNDER = get("entity.lightning.thunder");
			ENTITY_LINGERINGPOTION_THROW = get("entity.lingeringpotion.throw");
			ENTITY_LLAMA_AMBIENT = get("entity.llama.ambient");
			ENTITY_LLAMA_ANGRY = get("entity.llama.angry");
			ENTITY_LLAMA_CHEST = get("entity.llama.chest");
			ENTITY_LLAMA_DEATH = get("entity.llama.death");
			ENTITY_LLAMA_EAT = get("entity.llama.eat");
			ENTITY_LLAMA_HURT = get("entity.llama.hurt");
			ENTITY_LLAMA_SPIT = get("entity.llama.spit");
			ENTITY_LLAMA_STEP = get("entity.llama.step");
			ENTITY_LLAMA_SWAG = get("entity.llama.swag");
			ENTITY_MAGMACUBE_DEATH = get("entity.magmacube.death");
			ENTITY_MAGMACUBE_HURT = get("entity.magmacube.hurt");
			ENTITY_MAGMACUBE_JUMP = get("entity.magmacube.jump");
			ENTITY_MAGMACUBE_SQUISH = get("entity.magmacube.squish");
			BLOCK_METAL_BREAK = get("block.metal.break");
			BLOCK_METAL_FALL = get("block.metal.fall");
			BLOCK_METAL_HIT = get("block.metal.hit");
			BLOCK_METAL_PLACE = get("block.metal.place");
			BLOCK_METAL_PRESSUREPLATE_CLICK_OFF = get("block.metal_pressureplate.click_off");
			BLOCK_METAL_PRESSUREPLATE_CLICK_ON = get("block.metal_pressureplate.click_on");
			BLOCK_METAL_STEP = get("block.metal.step");
			ENTITY_MINECART_INSIDE = get("entity.minecart.inside");
			ENTITY_MINECART_RIDING = get("entity.minecart.riding");
			ENTITY_MOOSHROOM_SHEAR = get("entity.mooshroom.shear");
			ENTITY_MULE_AMBIENT = get("entity.mule.ambient");
			ENTITY_MULE_CHEST = get("entity.mule.chest");
			ENTITY_MULE_DEATH = get("entity.mule.death");
			ENTITY_MULE_HURT = get("entity.mule.hurt");
			MUSIC_CREATIVE = get("music.creative");
			MUSIC_CREDITS = get("music.credits");
			MUSIC_DRAGON = get("music.dragon");
			MUSIC_END = get("music.end");
			MUSIC_GAME = get("music.game");
			MUSIC_MENU = get("music.menu");
			MUSIC_NETHER = get("music.nether");
			BLOCK_NOTE_BASEDRUM = get("block.note.basedrum");
			BLOCK_NOTE_BASS = get("block.note.bass");
			BLOCK_NOTE_HARP = get("block.note.harp");
			BLOCK_NOTE_HAT = get("block.note.hat");
			BLOCK_NOTE_PLING = get("block.note.pling");
			BLOCK_NOTE_SNARE = get("block.note.snare");
			ENTITY_PAINTING_BREAK = get("entity.painting.break");
			ENTITY_PAINTING_PLACE = get("entity.painting.place");
			ENTITY_PIG_AMBIENT = get("entity.pig.ambient");
			ENTITY_PIG_DEATH = get("entity.pig.death");
			ENTITY_PIG_HURT = get("entity.pig.hurt");
			ENTITY_PIG_SADDLE = get("entity.pig.saddle");
			ENTITY_PIG_STEP = get("entity.pig.step");
			BLOCK_PISTON_CONTRACT = get("block.piston.contract");
			BLOCK_PISTON_EXTEND = get("block.piston.extend");
			ENTITY_PLAYER_ATTACK_CRIT = get("entity.player.attack.crit");
			ENTITY_PLAYER_ATTACK_KNOCKBACK = get("entity.player.attack.knockback");
			ENTITY_PLAYER_ATTACK_NODAMAGE = get("entity.player.attack.nodamage");
			ENTITY_PLAYER_ATTACK_STRONG = get("entity.player.attack.strong");
			ENTITY_PLAYER_ATTACK_SWEEP = get("entity.player.attack.sweep");
			ENTITY_PLAYER_ATTACK_WEAK = get("entity.player.attack.weak");
			ENTITY_PLAYER_BIG_FALL = get("entity.player.big_fall");
			ENTITY_PLAYER_BREATH = get("entity.player.breath");
			ENTITY_PLAYER_BURP = get("entity.player.burp");
			ENTITY_PLAYER_DEATH = get("entity.player.death");
			ENTITY_PLAYER_HURT = get("entity.player.hurt");
			ENTITY_PLAYER_LEVELUP = get("entity.player.levelup");
			ENTITY_PLAYER_SMALL_FALL = get("entity.player.small_fall");
			ENTITY_PLAYER_SPLASH = get("entity.player.splash");
			ENTITY_PLAYER_SWIM = get("entity.player.swim");
			ENTITY_POLAR_BEAR_AMBIENT = get("entity.polar_bear.ambient");
			ENTITY_POLAR_BEAR_BABY_AMBIENT = get("entity.polar_bear.baby_ambient");
			ENTITY_POLAR_BEAR_DEATH = get("entity.polar_bear.death");
			ENTITY_POLAR_BEAR_HURT = get("entity.polar_bear.hurt");
			ENTITY_POLAR_BEAR_STEP = get("entity.polar_bear.step");
			ENTITY_POLAR_BEAR_WARNING = get("entity.polar_bear.warning");
			BLOCK_PORTAL_AMBIENT = get("block.portal.ambient");
			BLOCK_PORTAL_TRAVEL = get("block.portal.travel");
			BLOCK_PORTAL_TRIGGER = get("block.portal.trigger");
			ENTITY_RABBIT_AMBIENT = get("entity.rabbit.ambient");
			ENTITY_RABBIT_ATTACK = get("entity.rabbit.attack");
			ENTITY_RABBIT_DEATH = get("entity.rabbit.death");
			ENTITY_RABBIT_HURT = get("entity.rabbit.hurt");
			ENTITY_RABBIT_JUMP = get("entity.rabbit.jump");
			RECORD_11 = get("record.11");
			RECORD_13 = get("record.13");
			RECORD_BLOCKS = get("record.blocks");
			RECORD_CAT = get("record.cat");
			RECORD_CHIRP = get("record.chirp");
			RECORD_FAR = get("record.far");
			RECORD_MALL = get("record.mall");
			RECORD_MELLOHI = get("record.mellohi");
			RECORD_STAL = get("record.stal");
			RECORD_STRAD = get("record.strad");
			RECORD_WAIT = get("record.wait");
			RECORD_WARD = get("record.ward");
			BLOCK_REDSTONE_TORCH_BURNOUT = get("block.redstone_torch.burnout");
			BLOCK_SAND_BREAK = get("block.sand.break");
			BLOCK_SAND_FALL = get("block.sand.fall");
			BLOCK_SAND_HIT = get("block.sand.hit");
			BLOCK_SAND_PLACE = get("block.sand.place");
			BLOCK_SAND_STEP = get("block.sand.step");
			ENTITY_SHEEP_AMBIENT = get("entity.sheep.ambient");
			ENTITY_SHEEP_DEATH = get("entity.sheep.death");
			ENTITY_SHEEP_HURT = get("entity.sheep.hurt");
			ENTITY_SHEEP_SHEAR = get("entity.sheep.shear");
			ENTITY_SHEEP_STEP = get("entity.sheep.step");
			ITEM_SHIELD_BLOCK = get("item.shield.block");
			ITEM_SHIELD_BREAK = get("item.shield.break");
			ITEM_SHOVEL_FLATTEN = get("item.shovel.flatten");
			ENTITY_SHULKER_AMBIENT = get("entity.shulker.ambient");
			BLOCK_SHULKER_BOX_CLOSE = get("block.shulker_box.close");
			BLOCK_SHULKER_BOX_OPEN = get("block.shulker_box.open");
			ENTITY_SHULKER_BULLET_HIT = get("entity.shulker_bullet.hit");
			ENTITY_SHULKER_BULLET_HURT = get("entity.shulker_bullet.hurt");
			ENTITY_SHULKER_CLOSE = get("entity.shulker.close");
			ENTITY_SHULKER_DEATH = get("entity.shulker.death");
			ENTITY_SHULKER_HURT = get("entity.shulker.hurt");
			ENTITY_SHULKER_HURT_CLOSED = get("entity.shulker.hurt_closed");
			ENTITY_SHULKER_OPEN = get("entity.shulker.open");
			ENTITY_SHULKER_SHOOT = get("entity.shulker.shoot");
			ENTITY_SHULKER_TELEPORT = get("entity.shulker.teleport");
			ENTITY_SILVERFISH_AMBIENT = get("entity.silverfish.ambient");
			ENTITY_SILVERFISH_DEATH = get("entity.silverfish.death");
			ENTITY_SILVERFISH_HURT = get("entity.silverfish.hurt");
			ENTITY_SILVERFISH_STEP = get("entity.silverfish.step");
			ENTITY_SKELETON_AMBIENT = get("entity.skeleton.ambient");
			ENTITY_SKELETON_DEATH = get("entity.skeleton.death");
			ENTITY_SKELETON_HORSE_AMBIENT = get("entity.skeleton_horse.ambient");
			ENTITY_SKELETON_HORSE_DEATH = get("entity.skeleton_horse.death");
			ENTITY_SKELETON_HORSE_HURT = get("entity.skeleton_horse.hurt");
			ENTITY_SKELETON_HURT = get("entity.skeleton.hurt");
			ENTITY_SKELETON_SHOOT = get("entity.skeleton.shoot");
			ENTITY_SKELETON_STEP = get("entity.skeleton.step");
			ENTITY_SLIME_ATTACK = get("entity.slime.attack");
			BLOCK_SLIME_BREAK = get("block.slime.break");
			ENTITY_SLIME_DEATH = get("entity.slime.death");
			BLOCK_SLIME_FALL = get("block.slime.fall");
			BLOCK_SLIME_HIT = get("block.slime.hit");
			ENTITY_SLIME_HURT = get("entity.slime.hurt");
			ENTITY_SLIME_JUMP = get("entity.slime.jump");
			BLOCK_SLIME_PLACE = get("block.slime.place");
			ENTITY_SLIME_SQUISH = get("entity.slime.squish");
			BLOCK_SLIME_STEP = get("block.slime.step");
			ENTITY_SMALL_MAGMACUBE_DEATH = get("entity.small_magmacube.death");
			ENTITY_SMALL_MAGMACUBE_HURT = get("entity.small_magmacube.hurt");
			ENTITY_SMALL_MAGMACUBE_SQUISH = get("entity.small_magmacube.squish");
			ENTITY_SMALL_SLIME_DEATH = get("entity.small_slime.death");
			ENTITY_SMALL_SLIME_HURT = get("entity.small_slime.hurt");
			ENTITY_SMALL_SLIME_JUMP = get("entity.small_slime.jump");
			ENTITY_SMALL_SLIME_SQUISH = get("entity.small_slime.squish");
			ENTITY_SNOWBALL_THROW = get("entity.snowball.throw");
			ENTITY_SNOWMAN_AMBIENT = get("entity.snowman.ambient");
			ENTITY_SNOWMAN_DEATH = get("entity.snowman.death");
			ENTITY_SNOWMAN_HURT = get("entity.snowman.hurt");
			ENTITY_SNOWMAN_SHOOT = get("entity.snowman.shoot");
			BLOCK_SNOW_BREAK = get("block.snow.break");
			BLOCK_SNOW_FALL = get("block.snow.fall");
			BLOCK_SNOW_HIT = get("block.snow.hit");
			BLOCK_SNOW_PLACE = get("block.snow.place");
			BLOCK_SNOW_STEP = get("block.snow.step");
			ENTITY_SPIDER_AMBIENT = get("entity.spider.ambient");
			ENTITY_SPIDER_DEATH = get("entity.spider.death");
			ENTITY_SPIDER_HURT = get("entity.spider.hurt");
			ENTITY_SPIDER_STEP = get("entity.spider.step");
			ENTITY_SPLASH_POTION_BREAK = get("entity.splash_potion.break");
			ENTITY_SPLASH_POTION_THROW = get("entity.splash_potion.throw");
			ENTITY_SQUID_AMBIENT = get("entity.squid.ambient");
			ENTITY_SQUID_DEATH = get("entity.squid.death");
			ENTITY_SQUID_HURT = get("entity.squid.hurt");
			BLOCK_STONE_BREAK = get("block.stone.break");
			BLOCK_STONE_BUTTON_CLICK_OFF = get("block.stone_button.click_off");
			BLOCK_STONE_BUTTON_CLICK_ON = get("block.stone_button.click_on");
			BLOCK_STONE_FALL = get("block.stone.fall");
			BLOCK_STONE_HIT = get("block.stone.hit");
			BLOCK_STONE_PLACE = get("block.stone.place");
			BLOCK_STONE_PRESSUREPLATE_CLICK_OFF = get("block.stone_pressureplate.click_off");
			BLOCK_STONE_PRESSUREPLATE_CLICK_ON = get("block.stone_pressureplate.click_on");
			BLOCK_STONE_STEP = get("block.stone.step");
			ENTITY_STRAY_AMBIENT = get("entity.stray.ambient");
			ENTITY_STRAY_DEATH = get("entity.stray.death");
			ENTITY_STRAY_HURT = get("entity.stray.hurt");
			ENTITY_STRAY_STEP = get("entity.stray.step");
			ENCHANT_THORNS_HIT = get("enchant.thorns.hit");
			ENTITY_TNT_PRIMED = get("entity.tnt.primed");
			ITEM_TOTEM_USE = get("item.totem.use");
			BLOCK_TRIPWIRE_ATTACH = get("block.tripwire.attach");
			BLOCK_TRIPWIRE_CLICK_OFF = get("block.tripwire.click_off");
			BLOCK_TRIPWIRE_CLICK_ON = get("block.tripwire.click_on");
			BLOCK_TRIPWIRE_DETACH = get("block.tripwire.detach");
			UI_BUTTON_CLICK = get("ui.button.click");
			ENTITY_VEX_AMBIENT = get("entity.vex.ambient");
			ENTITY_VEX_CHARGE = get("entity.vex.charge");
			ENTITY_VEX_DEATH = get("entity.vex.death");
			ENTITY_VEX_HURT = get("entity.vex.hurt");
			ENTITY_VILLAGER_AMBIENT = get("entity.villager.ambient");
			ENTITY_VILLAGER_DEATH = get("entity.villager.death");
			ENTITY_VILLAGER_HURT = get("entity.villager.hurt");
			ENTITY_VILLAGER_NO = get("entity.villager.no");
			ENTITY_VILLAGER_TRADING = get("entity.villager.trading");
			ENTITY_VILLAGER_YES = get("entity.villager.yes");
			ENTITY_VINDICATION_ILLAGER_AMBIENT = get("entity.vindication_illager.ambient");
			ENTITY_VINDICATION_ILLAGER_DEATH = get("entity.vindication_illager.death");
			ENTITY_VINDICATION_ILLAGER_HURT = get("entity.vindication_illager.hurt");
			BLOCK_WATERLILY_PLACE = get("block.waterlily.place");
			BLOCK_WATER_AMBIENT = get("block.water.ambient");
			WEATHER_RAIN = get("weather.rain");
			WEATHER_RAIN_ABOVE = get("weather.rain.above");
			ENTITY_WITCH_AMBIENT = get("entity.witch.ambient");
			ENTITY_WITCH_DEATH = get("entity.witch.death");
			ENTITY_WITCH_DRINK = get("entity.witch.drink");
			ENTITY_WITCH_HURT = get("entity.witch.hurt");
			ENTITY_WITCH_THROW = get("entity.witch.throw");
			ENTITY_WITHER_AMBIENT = get("entity.wither.ambient");
			ENTITY_WITHER_BREAK_BLOCK = get("entity.wither.break_block");
			ENTITY_WITHER_DEATH = get("entity.wither.death");
			ENTITY_WITHER_HURT = get("entity.wither.hurt");
			ENTITY_WITHER_SHOOT = get("entity.wither.shoot");
			ENTITY_WITHER_SKELETON_AMBIENT = get("entity.wither_skeleton.ambient");
			ENTITY_WITHER_SKELETON_DEATH = get("entity.wither_skeleton.death");
			ENTITY_WITHER_SKELETON_HURT = get("entity.wither_skeleton.hurt");
			ENTITY_WITHER_SKELETON_STEP = get("entity.wither_skeleton.step");
			ENTITY_WITHER_SPAWN = get("entity.wither.spawn");
			ENTITY_WOLF_AMBIENT = get("entity.wolf.ambient");
			ENTITY_WOLF_DEATH = get("entity.wolf.death");
			ENTITY_WOLF_GROWL = get("entity.wolf.growl");
			ENTITY_WOLF_HOWL = get("entity.wolf.howl");
			ENTITY_WOLF_HURT = get("entity.wolf.hurt");
			ENTITY_WOLF_PANT = get("entity.wolf.pant");
			ENTITY_WOLF_SHAKE = get("entity.wolf.shake");
			ENTITY_WOLF_STEP = get("entity.wolf.step");
			ENTITY_WOLF_WHINE = get("entity.wolf.whine");
			BLOCK_WOODEN_DOOR_CLOSE = get("block.wooden_door.close");
			BLOCK_WOODEN_DOOR_OPEN = get("block.wooden_door.open");
			BLOCK_WOODEN_TRAPDOOR_CLOSE = get("block.wooden_trapdoor.close");
			BLOCK_WOODEN_TRAPDOOR_OPEN = get("block.wooden_trapdoor.open");
			BLOCK_WOOD_BREAK = get("block.wood.break");
			BLOCK_WOOD_BUTTON_CLICK_OFF = get("block.wood_button.click_off");
			BLOCK_WOOD_BUTTON_CLICK_ON = get("block.wood_button.click_on");
			BLOCK_WOOD_FALL = get("block.wood.fall");
			BLOCK_WOOD_HIT = get("block.wood.hit");
			BLOCK_WOOD_PLACE = get("block.wood.place");
			BLOCK_WOOD_PRESSUREPLATE_CLICK_OFF = get("block.wood_pressureplate.click_off");
			BLOCK_WOOD_PRESSUREPLATE_CLICK_ON = get("block.wood_pressureplate.click_on");
			BLOCK_WOOD_STEP = get("block.wood.step");
			ENTITY_ZOMBIE_AMBIENT = get("entity.zombie.ambient");
			ENTITY_ZOMBIE_ATTACK_DOOR_WOOD = get("entity.zombie.attack_door_wood");
			ENTITY_ZOMBIE_ATTACK_IRON_DOOR = get("entity.zombie.attack_iron_door");
			ENTITY_ZOMBIE_BREAK_DOOR_WOOD = get("entity.zombie.break_door_wood");
			ENTITY_ZOMBIE_DEATH = get("entity.zombie.death");
			ENTITY_ZOMBIE_HORSE_AMBIENT = get("entity.zombie_horse.ambient");
			ENTITY_ZOMBIE_HORSE_DEATH = get("entity.zombie_horse.death");
			ENTITY_ZOMBIE_HORSE_HURT = get("entity.zombie_horse.hurt");
			ENTITY_ZOMBIE_HURT = get("entity.zombie.hurt");
			ENTITY_ZOMBIE_INFECT = get("entity.zombie.infect");
			ENTITY_ZOMBIE_PIG_AMBIENT = get("entity.zombie_pig.ambient");
			ENTITY_ZOMBIE_PIG_ANGRY = get("entity.zombie_pig.angry");
			ENTITY_ZOMBIE_PIG_DEATH = get("entity.zombie_pig.death");
			ENTITY_ZOMBIE_PIG_HURT = get("entity.zombie_pig.hurt");
			ENTITY_ZOMBIE_STEP = get("entity.zombie.step");
			ENTITY_ZOMBIE_VILLAGER_AMBIENT = get("entity.zombie_villager.ambient");
			ENTITY_ZOMBIE_VILLAGER_CONVERTED = get("entity.zombie_villager.converted");
			ENTITY_ZOMBIE_VILLAGER_CURE = get("entity.zombie_villager.cure");
			ENTITY_ZOMBIE_VILLAGER_DEATH = get("entity.zombie_villager.death");
			ENTITY_ZOMBIE_VILLAGER_HURT = get("entity.zombie_villager.hurt");
			ENTITY_ZOMBIE_VILLAGER_STEP = get("entity.zombie_villager.step");
		}
	}
}
