package net.minecraft.sound;

import net.minecraft.Bootstrap;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public class Sounds {
	public static final Sound AMBIENT_CAVE;
	public static final Sound AMBIENT_UNDERWATER_ENTER;
	public static final Sound AMBIENT_UNDERWATER_EXIT;
	public static final Sound AMBIENT_UNDERWATER_LOOP;
	public static final Sound AMBIENT_UNDERWATER_LOOP_ADDITIONS;
	public static final Sound AMBIENT_UNDERWATER_LOOP_ADDITIONS_RARE;
	public static final Sound AMBIENT_UNDERWATER_LOOP_ADDITIONS_ULTRA_RARE;
	public static final Sound BLOCK_ANVIL_BREAK;
	public static final Sound BLOCK_ANVIL_DESTROY;
	public static final Sound BLOCK_ANVIL_FALL;
	public static final Sound BLOCK_ANVIL_HIT;
	public static final Sound BLOCK_ANVIL_LAND;
	public static final Sound BLOCK_ANVIL_PLACE;
	public static final Sound BLOCK_ANVIL_STEP;
	public static final Sound BLOCK_ANVIL_USE;
	public static final Sound ITEM_ARMOR_EQUIP_CHAIN;
	public static final Sound ITEM_ARMOR_EQUIP_DIAMOND;
	public static final Sound ITEM_ARMOR_EQUIP_ELYTRA;
	public static final Sound ITEM_ARMOR_EQUIP_GENERIC;
	public static final Sound ITEM_ARMOR_EQUIP_GOLD;
	public static final Sound ITEM_ARMOR_EQUIP_IRON;
	public static final Sound ITEM_ARMOR_EQUIP_LEATHER;
	public static final Sound ITEM_ARMOR_EQUIP_TURTLE;
	public static final Sound ENTITY_ARMOR_STAND_BREAK;
	public static final Sound ENTITY_ARMOR_STAND_FALL;
	public static final Sound ENTITY_ARMOR_STAND_HIT;
	public static final Sound ENTITY_ARMOR_STAND_PLACE;
	public static final Sound ENTITY_ARROW_HIT;
	public static final Sound ENTITY_ARROW_HIT_PLAYER;
	public static final Sound ENTITY_ARROW_SHOOT;
	public static final Sound ITEM_AXE_STRIP;
	public static final Sound ENTITY_BAT_AMBIENT;
	public static final Sound ENTITY_BAT_DEATH;
	public static final Sound ENTITY_BAT_HURT;
	public static final Sound ENTITY_BAT_LOOP;
	public static final Sound ENTITY_BAT_TAKEOFF;
	public static final Sound BLOCK_BEACON_ACTIVATE;
	public static final Sound BLOCK_BEACON_AMBIENT;
	public static final Sound BLOCK_BEACON_DEACTIVATE;
	public static final Sound BLOCK_BEACON_POWER_SELECT;
	public static final Sound ENTITY_BLAZE_AMBIENT;
	public static final Sound ENTITY_BLAZE_BURN;
	public static final Sound ENTITY_BLAZE_DEATH;
	public static final Sound ENTITY_BLAZE_HURT;
	public static final Sound ENTITY_BLAZE_SHOOT;
	public static final Sound ENTITY_BOAT_PADDLE_LAND;
	public static final Sound ENTITY_BOAT_PADDLE_WATER;
	public static final Sound ENTITY_FISHING_BOBBER_RETRIEVE;
	public static final Sound ENTITY_FISHING_BOBBER_SPLASH;
	public static final Sound ENTITY_FISHING_BOBBER_THROW;
	public static final Sound ITEM_BOTTLE_EMPTY;
	public static final Sound ITEM_BOTTLE_FILL;
	public static final Sound ITEM_BOTTLE_FILL_DRAGONBREATH;
	public static final Sound BLOCK_BREWING_STAND_BREW;
	public static final Sound BLOCK_BUBBLE_COLUMN_BUBBLE_POP;
	public static final Sound BLOCK_BUBBLE_COLUMN_UPWARDS_AMBIENT;
	public static final Sound BLOCK_BUBBLE_COLUMN_UPWARDS_INSIDE;
	public static final Sound BLOCK_BUBBLE_COLUMN_WHIRLPOOL_AMBIENT;
	public static final Sound BLOCK_BUBBLE_COLUMN_WHIRLPOOL_INSIDE;
	public static final Sound ITEM_BUCKET_EMPTY;
	public static final Sound ITEM_BUCKET_EMPTY_FISH;
	public static final Sound ITEM_BUCKET_EMPTY_LAVA;
	public static final Sound ITEM_BUCKET_FILL;
	public static final Sound ITEM_BUCKET_FILL_FISH;
	public static final Sound ITEM_BUCKET_FILL_LAVA;
	public static final Sound ENTITY_CAT_AMBIENT;
	public static final Sound ENTITY_CAT_DEATH;
	public static final Sound ENTITY_CAT_HISS;
	public static final Sound ENTITY_CAT_HURT;
	public static final Sound ENTITY_CAT_PURR;
	public static final Sound ENTITY_CAT_PURREOW;
	public static final Sound BLOCK_CHEST_CLOSE;
	public static final Sound BLOCK_CHEST_LOCKED;
	public static final Sound BLOCK_CHEST_OPEN;
	public static final Sound ENTITY_CHICKEN_AMBIENT;
	public static final Sound ENTITY_CHICKEN_DEATH;
	public static final Sound ENTITY_CHICKEN_EGG;
	public static final Sound ENTITY_CHICKEN_HURT;
	public static final Sound ENTITY_CHICKEN_STEP;
	public static final Sound BLOCK_CHORUS_FLOWER_DEATH;
	public static final Sound BLOCK_CHORUS_FLOWER_GROW;
	public static final Sound ITEM_CHORUS_FRUIT_TELEPORT;
	public static final Sound BLOCK_WOOL_BREAK;
	public static final Sound BLOCK_WOOL_FALL;
	public static final Sound BLOCK_WOOL_HIT;
	public static final Sound BLOCK_WOOL_PLACE;
	public static final Sound BLOCK_WOOL_STEP;
	public static final Sound ENTITY_COD_AMBIENT;
	public static final Sound ENTITY_COD_DEATH;
	public static final Sound ENTITY_COD_FLOP;
	public static final Sound ENTITY_COD_HURT;
	public static final Sound BLOCK_COMPARATOR_CLICK;
	public static final Sound BLOCK_CONDUIT_ACTIVATE;
	public static final Sound BLOCK_CONDUIT_AMBIENT;
	public static final Sound BLOCK_CONDUIT_AMBIENT_SHORT;
	public static final Sound BLOCK_CONDUIT_ATTACK_TARGET;
	public static final Sound BLOCK_CONDUIT_DEACTIVATE;
	public static final Sound ENTITY_COW_AMBIENT;
	public static final Sound ENTITY_COW_DEATH;
	public static final Sound ENTITY_COW_HURT;
	public static final Sound ENTITY_COW_MILK;
	public static final Sound ENTITY_COW_STEP;
	public static final Sound ENTITY_CREEPER_DEATH;
	public static final Sound ENTITY_CREEPER_HURT;
	public static final Sound ENTITY_CREEPER_PRIMED;
	public static final Sound BLOCK_DISPENSER_DISPENSE;
	public static final Sound BLOCK_DISPENSER_FAIL;
	public static final Sound BLOCK_DISPENSER_LAUNCH;
	public static final Sound ENTITY_DOLPHIN_AMBIENT;
	public static final Sound ENTITY_DOLPHIN_AMBIENT_WATER;
	public static final Sound ENTITY_DOLPHIN_ATTACK;
	public static final Sound ENTITY_DOLPHIN_DEATH;
	public static final Sound ENTITY_DOLPHIN_EAT;
	public static final Sound ENTITY_DOLPHIN_HURT;
	public static final Sound ENTITY_DOLPHIN_JUMP;
	public static final Sound ENTITY_DOLPHIN_PLAY;
	public static final Sound ENTITY_DOLPHIN_SPLASH;
	public static final Sound ENTITY_DOLPHIN_SWIM;
	public static final Sound ENTITY_DONKEY_AMBIENT;
	public static final Sound ENTITY_DONKEY_ANGRY;
	public static final Sound ENTITY_DONKEY_CHEST;
	public static final Sound ENTITY_DONKEY_DEATH;
	public static final Sound ENTITY_DONKEY_HURT;
	public static final Sound ENTITY_DROWNED_AMBIENT;
	public static final Sound ENTITY_DROWNED_AMBIENT_WATER;
	public static final Sound ENTITY_DROWNED_DEATH;
	public static final Sound ENTITY_DROWNED_DEATH_WATER;
	public static final Sound ENTITY_DROWNED_HURT;
	public static final Sound ENTITY_DROWNED_HURT_WATER;
	public static final Sound ENTITY_DROWNED_SHOOT;
	public static final Sound ENTITY_DROWNED_STEP;
	public static final Sound ENTITY_DROWNED_SWIM;
	public static final Sound ENTITY_EGG_THROW;
	public static final Sound ENTITY_ELDER_GUARDIAN_AMBIENT;
	public static final Sound ENTITY_ELDER_GUARDIAN_AMBIENT_LAND;
	public static final Sound ENTITY_ELDER_GUARDIAN_CURSE;
	public static final Sound ENTITY_ELDER_GUARDIAN_DEATH;
	public static final Sound ENTITY_ELDER_GUARDIAN_DEATH_LAND;
	public static final Sound ENTITY_ELDER_GUARDIAN_FLOP;
	public static final Sound ENTITY_ELDER_GUARDIAN_HURT;
	public static final Sound ENTITY_ELDER_GUARDIAN_HURT_LAND;
	public static final Sound ITEM_ELYTRA_FLYING;
	public static final Sound BLOCK_ENCHANTMENT_TABLE_USE;
	public static final Sound BLOCK_ENDER_CHEST_CLOSE;
	public static final Sound BLOCK_ENDER_CHEST_OPEN;
	public static final Sound ENTITY_ENDER_DRAGON_AMBIENT;
	public static final Sound ENTITY_ENDER_DRAGON_DEATH;
	public static final Sound ENTITY_DRAGON_FIREBALL_EXPLODE;
	public static final Sound ENTITY_ENDER_DRAGON_FLAP;
	public static final Sound ENTITY_ENDER_DRAGON_GROWL;
	public static final Sound ENTITY_ENDER_DRAGON_HURT;
	public static final Sound ENTITY_ENDER_DRAGON_SHOOT;
	public static final Sound ENTITY_ENDER_EYE_DEATH;
	public static final Sound ENTITY_ENDER_EYE_LAUNCH;
	public static final Sound ENTITY_ENDERMAN_AMBIENT;
	public static final Sound ENTITY_ENDERMAN_DEATH;
	public static final Sound ENTITY_ENDERMAN_HURT;
	public static final Sound ENTITY_ENDERMAN_SCREAM;
	public static final Sound ENTITY_ENDERMAN_STARE;
	public static final Sound ENTITY_ENDERMAN_TELEPORT;
	public static final Sound ENTITY_ENDERMITE_AMBIENT;
	public static final Sound ENTITY_ENDERMITE_DEATH;
	public static final Sound ENTITY_ENDERMITE_HURT;
	public static final Sound ENTITY_ENDERMITE_STEP;
	public static final Sound ENTITY_ENDER_PEARL_THROW;
	public static final Sound BLOCK_END_GATEWAY_SPAWN;
	public static final Sound BLOCK_END_PORTAL_FRAME_FILL;
	public static final Sound BLOCK_END_PORTAL_SPAWN;
	public static final Sound ENTITY_EVOKER_AMBIENT;
	public static final Sound ENTITY_EVOKER_CAST_SPELL;
	public static final Sound ENTITY_EVOKER_DEATH;
	public static final Sound ENTITY_EVOKER_FANGS_ATTACK;
	public static final Sound ENTITY_EVOKER_HURT;
	public static final Sound ENTITY_EVOKER_PREPARE_ATTACK;
	public static final Sound ENTITY_EVOKER_PREPARE_SUMMON;
	public static final Sound ENTITY_EVOKER_PREPARE_WOLOLO;
	public static final Sound ENTITY_EXPERIENCE_BOTTLE_THROW;
	public static final Sound ENTITY_EXPERIENCE_ORB_PICKUP;
	public static final Sound BLOCK_FENCE_GATE_CLOSE;
	public static final Sound BLOCK_FENCE_GATE_OPEN;
	public static final Sound ITEM_FIRECHARGE_USE;
	public static final Sound ENTITY_FIREWORK_ROCKET_BLAST;
	public static final Sound ENTITY_FIREWORK_ROCKET_BLAST_FAR;
	public static final Sound ENTITY_FIREWORK_ROCKET_LARGE_BLAST;
	public static final Sound ENTITY_FIREWORK_ROCKET_LARGE_BLAST_FAR;
	public static final Sound ENTITY_FIREWORK_ROCKET_LAUNCH;
	public static final Sound ENTITY_FIREWORK_ROCKET_SHOOT;
	public static final Sound ENTITY_FIREWORK_ROCKET_TWINKLE;
	public static final Sound ENTITY_FIREWORK_ROCKET_TWINKLE_FAR;
	public static final Sound BLOCK_FIRE_AMBIENT;
	public static final Sound BLOCK_FIRE_EXTINGUISH;
	public static final Sound ENTITY_FISH_SWIM;
	public static final Sound ITEM_FLINTANDSTEEL_USE;
	public static final Sound BLOCK_FURNACE_FIRE_CRACKLE;
	public static final Sound ENTITY_GENERIC_BIG_FALL;
	public static final Sound ENTITY_GENERIC_BURN;
	public static final Sound ENTITY_GENERIC_DEATH;
	public static final Sound ENTITY_GENERIC_DRINK;
	public static final Sound ENTITY_GENERIC_EAT;
	public static final Sound ENTITY_GENERIC_EXPLODE;
	public static final Sound ENTITY_GENERIC_EXTINGUISH_FIRE;
	public static final Sound ENTITY_GENERIC_HURT;
	public static final Sound ENTITY_GENERIC_SMALL_FALL;
	public static final Sound ENTITY_GENERIC_SPLASH;
	public static final Sound ENTITY_GENERIC_SWIM;
	public static final Sound ENTITY_GHAST_AMBIENT;
	public static final Sound ENTITY_GHAST_DEATH;
	public static final Sound ENTITY_GHAST_HURT;
	public static final Sound ENTITY_GHAST_SCREAM;
	public static final Sound ENTITY_GHAST_SHOOT;
	public static final Sound ENTITY_GHAST_WARN;
	public static final Sound BLOCK_GLASS_BREAK;
	public static final Sound BLOCK_GLASS_FALL;
	public static final Sound BLOCK_GLASS_HIT;
	public static final Sound BLOCK_GLASS_PLACE;
	public static final Sound BLOCK_GLASS_STEP;
	public static final Sound BLOCK_GRASS_BREAK;
	public static final Sound BLOCK_GRASS_FALL;
	public static final Sound BLOCK_GRASS_HIT;
	public static final Sound BLOCK_GRASS_PLACE;
	public static final Sound BLOCK_GRASS_STEP;
	public static final Sound BLOCK_WET_GRASS_BREAK;
	public static final Sound BLOCK_WET_GRASS_FALL;
	public static final Sound BLOCK_WET_GRASS_HIT;
	public static final Sound BLOCK_WET_GRASS_PLACE;
	public static final Sound BLOCK_WET_GRASS_STEP;
	public static final Sound BLOCK_CORAL_BLOCK_BREAK;
	public static final Sound BLOCK_CORAL_BLOCK_FALL;
	public static final Sound BLOCK_CORAL_BLOCK_HIT;
	public static final Sound BLOCK_CORAL_BLOCK_PLACE;
	public static final Sound BLOCK_CORAL_BLOCK_STEP;
	public static final Sound BLOCK_GRAVEL_BREAK;
	public static final Sound BLOCK_GRAVEL_FALL;
	public static final Sound BLOCK_GRAVEL_HIT;
	public static final Sound BLOCK_GRAVEL_PLACE;
	public static final Sound BLOCK_GRAVEL_STEP;
	public static final Sound ENTITY_GUARDIAN_AMBIENT;
	public static final Sound ENTITY_GUARDIAN_AMBIENT_LAND;
	public static final Sound ENTITY_GUARDIAN_ATTACK;
	public static final Sound ENTITY_GUARDIAN_DEATH;
	public static final Sound ENTITY_GUARDIAN_DEATH_LAND;
	public static final Sound ENTITY_GUARDIAN_FLOP;
	public static final Sound ENTITY_GUARDIAN_HURT;
	public static final Sound ENTITY_GUARDIAN_HURT_LAND;
	public static final Sound ITEM_HOE_TILL;
	public static final Sound ENTITY_HORSE_AMBIENT;
	public static final Sound ENTITY_HORSE_ANGRY;
	public static final Sound ENTITY_HORSE_ARMOR;
	public static final Sound ENTITY_HORSE_BREATHE;
	public static final Sound ENTITY_HORSE_DEATH;
	public static final Sound ENTITY_HORSE_EAT;
	public static final Sound ENTITY_HORSE_GALLOP;
	public static final Sound ENTITY_HORSE_HURT;
	public static final Sound ENTITY_HORSE_JUMP;
	public static final Sound ENTITY_HORSE_LAND;
	public static final Sound ENTITY_HORSE_SADDLE;
	public static final Sound ENTITY_HORSE_STEP;
	public static final Sound ENTITY_HORSE_STEP_WOOD;
	public static final Sound ENTITY_HOSTILE_BIG_FALL;
	public static final Sound ENTITY_HOSTILE_DEATH;
	public static final Sound ENTITY_HOSTILE_HURT;
	public static final Sound ENTITY_HOSTILE_SMALL_FALL;
	public static final Sound ENTITY_HOSTILE_SPLASH;
	public static final Sound ENTITY_HOSTILE_SWIM;
	public static final Sound ENTITY_HUSK_AMBIENT;
	public static final Sound ENTITY_HUSK_CONVERTED_TO_ZOMBIE;
	public static final Sound ENTITY_HUSK_DEATH;
	public static final Sound ENTITY_HUSK_HURT;
	public static final Sound ENTITY_HUSK_STEP;
	public static final Sound ENTITY_ILLUSIONER_AMBIENT;
	public static final Sound ENTITY_ILLUSIONER_CAST_SPELL;
	public static final Sound ENTITY_ILLUSIONER_DEATH;
	public static final Sound ENTITY_ILLUSIONER_HURT;
	public static final Sound ENTITY_ILLUSIONER_MIRROR_MOVE;
	public static final Sound ENTITY_ILLUSIONER_PREPARE_BLINDNESS;
	public static final Sound ENTITY_ILLUSIONER_PREPARE_MIRROR;
	public static final Sound BLOCK_IRON_DOOR_CLOSE;
	public static final Sound BLOCK_IRON_DOOR_OPEN;
	public static final Sound ENTITY_IRON_GOLEM_ATTACK;
	public static final Sound ENTITY_IRON_GOLEM_DEATH;
	public static final Sound ENTITY_IRON_GOLEM_HURT;
	public static final Sound ENTITY_IRON_GOLEM_STEP;
	public static final Sound BLOCK_IRON_TRAPDOOR_CLOSE;
	public static final Sound BLOCK_IRON_TRAPDOOR_OPEN;
	public static final Sound ENTITY_ITEM_FRAME_ADD_ITEM;
	public static final Sound ENTITY_ITEM_FRAME_BREAK;
	public static final Sound ENTITY_ITEM_FRAME_PLACE;
	public static final Sound ENTITY_ITEM_FRAME_REMOVE_ITEM;
	public static final Sound ENTITY_ITEM_FRAME_ROTATE_ITEM;
	public static final Sound ENTITY_ITEM_BREAK;
	public static final Sound ENTITY_ITEM_PICKUP;
	public static final Sound BLOCK_LADDER_BREAK;
	public static final Sound BLOCK_LADDER_FALL;
	public static final Sound BLOCK_LADDER_HIT;
	public static final Sound BLOCK_LADDER_PLACE;
	public static final Sound BLOCK_LADDER_STEP;
	public static final Sound BLOCK_LAVA_AMBIENT;
	public static final Sound BLOCK_LAVA_EXTINGUISH;
	public static final Sound BLOCK_LAVA_POP;
	public static final Sound ENTITY_LEASH_KNOT_BREAK;
	public static final Sound ENTITY_LEASH_KNOT_PLACE;
	public static final Sound BLOCK_LEVER_CLICK;
	public static final Sound ENTITY_LIGHTNING_BOLT_IMPACT;
	public static final Sound ENTITY_LIGHTNING_BOLT_THUNDER;
	public static final Sound ENTITY_LINGERING_POTION_THROW;
	public static final Sound ENTITY_LLAMA_AMBIENT;
	public static final Sound ENTITY_LLAMA_ANGRY;
	public static final Sound ENTITY_LLAMA_CHEST;
	public static final Sound ENTITY_LLAMA_DEATH;
	public static final Sound ENTITY_LLAMA_EAT;
	public static final Sound ENTITY_LLAMA_HURT;
	public static final Sound ENTITY_LLAMA_SPIT;
	public static final Sound ENTITY_LLAMA_STEP;
	public static final Sound ENTITY_LLAMA_SWAG;
	public static final Sound ENTITY_MAGMA_CUBE_DEATH;
	public static final Sound ENTITY_MAGMA_CUBE_HURT;
	public static final Sound ENTITY_MAGMA_CUBE_JUMP;
	public static final Sound ENTITY_MAGMA_CUBE_SQUISH;
	public static final Sound BLOCK_METAL_BREAK;
	public static final Sound BLOCK_METAL_FALL;
	public static final Sound BLOCK_METAL_HIT;
	public static final Sound BLOCK_METAL_PLACE;
	public static final Sound BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF;
	public static final Sound BLOCK_METAL_PRESSURE_PLATE_CLICK_ON;
	public static final Sound BLOCK_METAL_STEP;
	public static final Sound ENTITY_MINECART_INSIDE;
	public static final Sound ENTITY_MINECART_RIDING;
	public static final Sound ENTITY_MOOSHROOM_SHEAR;
	public static final Sound ENTITY_MULE_AMBIENT;
	public static final Sound ENTITY_MULE_CHEST;
	public static final Sound ENTITY_MULE_DEATH;
	public static final Sound ENTITY_MULE_HURT;
	public static final Sound MUSIC_CREATIVE;
	public static final Sound MUSIC_CREDITS;
	public static final Sound MUSIC_DRAGON;
	public static final Sound MUSIC_END;
	public static final Sound MUSIC_GAME;
	public static final Sound MUSIC_MENU;
	public static final Sound MUSIC_NETHER;
	public static final Sound MUSIC_UNDER_WATER;
	public static final Sound BLOCK_NOTE_BLOCK_BASEDRUM;
	public static final Sound BLOCK_NOTE_BLOCK_BASS;
	public static final Sound BLOCK_NOTE_BLOCK_BELL;
	public static final Sound BLOCK_NOTE_BLOCK_CHIME;
	public static final Sound BLOCK_NOTE_BLOCK_FLUTE;
	public static final Sound BLOCK_NOTE_BLOCK_GUITAR;
	public static final Sound BLOCK_NOTE_BLOCK_HARP;
	public static final Sound BLOCK_NOTE_BLOCK_HAT;
	public static final Sound BLOCK_NOTE_BLOCK_PLING;
	public static final Sound BLOCK_NOTE_BLOCK_SNARE;
	public static final Sound BLOCK_NOTE_BLOCK_XYLOPHONE;
	public static final Sound ENTITY_PAINTING_BREAK;
	public static final Sound ENTITY_PAINTING_PLACE;
	public static final Sound ENTITY_PARROT_AMBIENT;
	public static final Sound ENTITY_PARROT_DEATH;
	public static final Sound ENTITY_PARROT_EAT;
	public static final Sound ENTITY_PARROT_FLY;
	public static final Sound ENTITY_PARROT_HURT;
	public static final Sound ENTITY_PARROT_IMITATE_BLAZE;
	public static final Sound ENTITY_PARROT_IMITATE_CREEPER;
	public static final Sound ENTITY_PARROT_IMITATE_DROWNED;
	public static final Sound ENTITY_PARROT_IMITATE_ELDER_GUARDIAN;
	public static final Sound ENTITY_PARROT_IMITATE_ENDER_DRAGON;
	public static final Sound ENTITY_PARROT_IMITATE_ENDERMAN;
	public static final Sound ENTITY_PARROT_IMITATE_ENDERMITE;
	public static final Sound ENTITY_PARROT_IMITATE_EVOKER;
	public static final Sound ENTITY_PARROT_IMITATE_GHAST;
	public static final Sound ENTITY_PARROT_IMITATE_HUSK;
	public static final Sound ENTITY_PARROT_IMITATE_ILLUSIONER;
	public static final Sound ENTITY_PARROT_IMITATE_MAGMA_CUBE;
	public static final Sound ENTITY_PARROT_IMITATE_PHANTOM;
	public static final Sound ENTITY_PARROT_IMITATE_POLAR_BEAR;
	public static final Sound ENTITY_PARROT_IMITATE_SHULKER;
	public static final Sound ENTITY_PARROT_IMITATE_SILVERFISH;
	public static final Sound ENTITY_PARROT_IMITATE_SKELETON;
	public static final Sound ENTITY_PARROT_IMITATE_SLIME;
	public static final Sound ENTITY_PARROT_IMITATE_SPIDER;
	public static final Sound ENTITY_PARROT_IMITATE_STRAY;
	public static final Sound ENTITY_PARROT_IMITATE_VEX;
	public static final Sound ENTITY_PARROT_IMITATE_VINDICATOR;
	public static final Sound ENTITY_PARROT_IMITATE_WITCH;
	public static final Sound ENTITY_PARROT_IMITATE_WITHER;
	public static final Sound ENTITY_PARROT_IMITATE_WITHER_SKELETON;
	public static final Sound ENTITY_PARROT_IMITATE_WOLF;
	public static final Sound ENTITY_PARROT_IMITATE_ZOMBIE;
	public static final Sound ENTITY_PARROT_IMITATE_ZOMBIE_PIGMAN;
	public static final Sound ENTITY_PARROT_IMITATE_ZOMBIE_VILLAGER;
	public static final Sound ENTITY_PARROT_STEP;
	public static final Sound ENTITY_PHANTOM_AMBIENT;
	public static final Sound ENTITY_PHANTOM_BITE;
	public static final Sound ENTITY_PHANTOM_DEATH;
	public static final Sound ENTITY_PHANTOM_FLAP;
	public static final Sound ENTITY_PHANTOM_HURT;
	public static final Sound ENTITY_PHANTOM_SWOOP;
	public static final Sound ENTITY_PIG_AMBIENT;
	public static final Sound ENTITY_PIG_DEATH;
	public static final Sound ENTITY_PIG_HURT;
	public static final Sound ENTITY_PIG_SADDLE;
	public static final Sound ENTITY_PIG_STEP;
	public static final Sound BLOCK_PISTON_CONTRACT;
	public static final Sound BLOCK_PISTON_EXTEND;
	public static final Sound ENTITY_PLAYER_ATTACK_CRIT;
	public static final Sound ENTITY_PLAYER_ATTACK_KNOCKBACK;
	public static final Sound ENTITY_PLAYER_ATTACK_NODAMAGE;
	public static final Sound ENTITY_PLAYER_ATTACK_STRONG;
	public static final Sound ENTITY_PLAYER_ATTACK_SWEEP;
	public static final Sound ENTITY_PLAYER_ATTACK_WEAK;
	public static final Sound ENTITY_PLAYER_BIG_FALL;
	public static final Sound ENTITY_PLAYER_BREATH;
	public static final Sound ENTITY_PLAYER_BURP;
	public static final Sound ENTITY_PLAYER_DEATH;
	public static final Sound ENTITY_PLAYER_HURT;
	public static final Sound ENTITY_PLAYER_HURT_DROWN;
	public static final Sound ENTITY_PLAYER_HURT_ON_FIRE;
	public static final Sound ENTITY_PLAYER_LEVELUP;
	public static final Sound ENTITY_PLAYER_SMALL_FALL;
	public static final Sound ENTITY_PLAYER_SPLASH;
	public static final Sound ENTITY_PLAYER_SPLASH_HIGH_SPEED;
	public static final Sound ENTITY_PLAYER_SWIM;
	public static final Sound ENTITY_POLAR_BEAR_AMBIENT;
	public static final Sound ENTITY_POLAR_BEAR_AMBIENT_BABY;
	public static final Sound ENTITY_POLAR_BEAR_DEATH;
	public static final Sound ENTITY_POLAR_BEAR_HURT;
	public static final Sound ENTITY_POLAR_BEAR_STEP;
	public static final Sound ENTITY_POLAR_BEAR_WARNING;
	public static final Sound BLOCK_PORTAL_AMBIENT;
	public static final Sound BLOCK_PORTAL_TRAVEL;
	public static final Sound BLOCK_PORTAL_TRIGGER;
	public static final Sound ENTITY_PUFFER_FISH_AMBIENT;
	public static final Sound ENTITY_PUFFER_FISH_BLOW_OUT;
	public static final Sound ENTITY_PUFFER_FISH_BLOW_UP;
	public static final Sound ENTITY_PUFFER_FISH_DEATH;
	public static final Sound ENTITY_PUFFER_FISH_FLOP;
	public static final Sound ENTITY_PUFFER_FISH_HURT;
	public static final Sound ENTITY_PUFFER_FISH_STING;
	public static final Sound BLOCK_PUMPKIN_CARVE;
	public static final Sound ENTITY_RABBIT_AMBIENT;
	public static final Sound ENTITY_RABBIT_ATTACK;
	public static final Sound ENTITY_RABBIT_DEATH;
	public static final Sound ENTITY_RABBIT_HURT;
	public static final Sound ENTITY_RABBIT_JUMP;
	public static final Sound MUSIC_DISC_11;
	public static final Sound MUSIC_DISC_13;
	public static final Sound MUSIC_DISC_BLOCKS;
	public static final Sound MUSIC_DISC_CAT;
	public static final Sound MUSIC_DISC_CHIRP;
	public static final Sound MUSIC_DISC_FAR;
	public static final Sound MUSIC_DISC_MALL;
	public static final Sound MUSIC_DISC_MELLOHI;
	public static final Sound MUSIC_DISC_STAL;
	public static final Sound MUSIC_DISC_STRAD;
	public static final Sound MUSIC_DISC_WAIT;
	public static final Sound MUSIC_DISC_WARD;
	public static final Sound BLOCK_REDSTONE_TORCH_BURNOUT;
	public static final Sound ENTITY_SALMON_AMBIENT;
	public static final Sound ENTITY_SALMON_DEATH;
	public static final Sound ENTITY_SALMON_FLOP;
	public static final Sound ENTITY_SALMON_HURT;
	public static final Sound BLOCK_SAND_BREAK;
	public static final Sound BLOCK_SAND_FALL;
	public static final Sound BLOCK_SAND_HIT;
	public static final Sound BLOCK_SAND_PLACE;
	public static final Sound BLOCK_SAND_STEP;
	public static final Sound ENTITY_SHEEP_AMBIENT;
	public static final Sound ENTITY_SHEEP_DEATH;
	public static final Sound ENTITY_SHEEP_HURT;
	public static final Sound ENTITY_SHEEP_SHEAR;
	public static final Sound ENTITY_SHEEP_STEP;
	public static final Sound ITEM_SHIELD_BLOCK;
	public static final Sound ITEM_SHIELD_BREAK;
	public static final Sound ITEM_SHOVEL_FLATTEN;
	public static final Sound ENTITY_SHULKER_AMBIENT;
	public static final Sound BLOCK_SHULKER_BOX_CLOSE;
	public static final Sound BLOCK_SHULKER_BOX_OPEN;
	public static final Sound ENTITY_SHULKER_BULLET_HIT;
	public static final Sound ENTITY_SHULKER_BULLET_HURT;
	public static final Sound ENTITY_SHULKER_CLOSE;
	public static final Sound ENTITY_SHULKER_DEATH;
	public static final Sound ENTITY_SHULKER_HURT;
	public static final Sound ENTITY_SHULKER_HURT_CLOSED;
	public static final Sound ENTITY_SHULKER_OPEN;
	public static final Sound ENTITY_SHULKER_SHOOT;
	public static final Sound ENTITY_SHULKER_TELEPORT;
	public static final Sound ENTITY_SILVERFISH_AMBIENT;
	public static final Sound ENTITY_SILVERFISH_DEATH;
	public static final Sound ENTITY_SILVERFISH_HURT;
	public static final Sound ENTITY_SILVERFISH_STEP;
	public static final Sound ENTITY_SKELETON_AMBIENT;
	public static final Sound ENTITY_SKELETON_DEATH;
	public static final Sound ENTITY_SKELETON_HORSE_AMBIENT;
	public static final Sound ENTITY_SKELETON_HORSE_DEATH;
	public static final Sound ENTITY_SKELETON_HORSE_HURT;
	public static final Sound ENTITY_SKELETON_HORSE_SWIM;
	public static final Sound ENTITY_SKELETON_HORSE_AMBIENT_WATER;
	public static final Sound ENTITY_SKELETON_HORSE_GALLOP_WATER;
	public static final Sound ENTITY_SKELETON_HORSE_JUMP_WATER;
	public static final Sound ENTITY_SKELETON_HORSE_STEP_WATER;
	public static final Sound ENTITY_SKELETON_HURT;
	public static final Sound ENTITY_SKELETON_SHOOT;
	public static final Sound ENTITY_SKELETON_STEP;
	public static final Sound ENTITY_SLIME_ATTACK;
	public static final Sound ENTITY_SLIME_DEATH;
	public static final Sound ENTITY_SLIME_HURT;
	public static final Sound ENTITY_SLIME_JUMP;
	public static final Sound ENTITY_SLIME_SQUISH;
	public static final Sound BLOCK_SLIME_BLOCK_BREAK;
	public static final Sound BLOCK_SLIME_BLOCK_FALL;
	public static final Sound BLOCK_SLIME_BLOCK_HIT;
	public static final Sound BLOCK_SLIME_BLOCK_PLACE;
	public static final Sound BLOCK_SLIME_BLOCK_STEP;
	public static final Sound ENTITY_MAGMA_CUBE_DEATH_SMALL;
	public static final Sound ENTITY_MAGMA_CUBE_HURT_SMALL;
	public static final Sound ENTITY_MAGMA_CUBE_SQUISH_SMALL;
	public static final Sound ENTITY_SLIME_DEATH_SMALL;
	public static final Sound ENTITY_SLIME_HURT_SMALL;
	public static final Sound ENTITY_SLIME_JUMP_SMALL;
	public static final Sound ENTITY_SLIME_SQUISH_SMALL;
	public static final Sound ENTITY_SNOWBALL_THROW;
	public static final Sound BLOCK_SNOW_BREAK;
	public static final Sound BLOCK_SNOW_FALL;
	public static final Sound ENTITY_SNOW_GOLEM_AMBIENT;
	public static final Sound ENTITY_SNOW_GOLEM_DEATH;
	public static final Sound ENTITY_SNOW_GOLEM_HURT;
	public static final Sound ENTITY_SNOW_GOLEM_SHOOT;
	public static final Sound BLOCK_SNOW_HIT;
	public static final Sound BLOCK_SNOW_PLACE;
	public static final Sound BLOCK_SNOW_STEP;
	public static final Sound ENTITY_SPIDER_AMBIENT;
	public static final Sound ENTITY_SPIDER_DEATH;
	public static final Sound ENTITY_SPIDER_HURT;
	public static final Sound ENTITY_SPIDER_STEP;
	public static final Sound ENTITY_SPLASH_POTION_BREAK;
	public static final Sound ENTITY_SPLASH_POTION_THROW;
	public static final Sound ENTITY_SQUID_AMBIENT;
	public static final Sound ENTITY_SQUID_DEATH;
	public static final Sound ENTITY_SQUID_HURT;
	public static final Sound ENTITY_SQUID_SQUIRT;
	public static final Sound BLOCK_STONE_BREAK;
	public static final Sound BLOCK_STONE_BUTTON_CLICK_OFF;
	public static final Sound BLOCK_STONE_BUTTON_CLICK_ON;
	public static final Sound BLOCK_STONE_FALL;
	public static final Sound BLOCK_STONE_HIT;
	public static final Sound BLOCK_STONE_PLACE;
	public static final Sound BLOCK_STONE_PRESSURE_PLATE_CLICK_OFF;
	public static final Sound BLOCK_STONE_PRESSURE_PLATE_CLICK_ON;
	public static final Sound BLOCK_STONE_STEP;
	public static final Sound ENTITY_STRAY_AMBIENT;
	public static final Sound ENTITY_STRAY_DEATH;
	public static final Sound ENTITY_STRAY_HURT;
	public static final Sound ENTITY_STRAY_STEP;
	public static final Sound ENCHANT_THORNS_HIT;
	public static final Sound ENTITY_TNT_PRIMED;
	public static final Sound ITEM_TOTEM_USE;
	public static final Sound ITEM_TRIDENT_HIT;
	public static final Sound ITEM_TRIDENT_HIT_GROUND;
	public static final Sound ITEM_TRIDENT_RETURN;
	public static final Sound ITEM_TRIDENT_RIPTIDE_1;
	public static final Sound ITEM_TRIDENT_RIPTIDE_2;
	public static final Sound ITEM_TRIDENT_RIPTIDE_3;
	public static final Sound ITEM_TRIDENT_THROW;
	public static final Sound ITEM_TRIDENT_THUNDER;
	public static final Sound BLOCK_TRIPWIRE_ATTACH;
	public static final Sound BLOCK_TRIPWIRE_CLICK_OFF;
	public static final Sound BLOCK_TRIPWIRE_CLICK_ON;
	public static final Sound BLOCK_TRIPWIRE_DETACH;
	public static final Sound ENTITY_TROPICAL_FISH_AMBIENT;
	public static final Sound ENTITY_TROPICAL_FISH_DEATH;
	public static final Sound ENTITY_TROPICAL_FISH_FLOP;
	public static final Sound ENTITY_TROPICAL_FISH_HURT;
	public static final Sound ENTITY_TURTLE_AMBIENT_LAND;
	public static final Sound ENTITY_TURTLE_DEATH;
	public static final Sound ENTITY_TURTLE_DEATH_BABY;
	public static final Sound ENTITY_TURTLE_EGG_BREAK;
	public static final Sound ENTITY_TURTLE_EGG_CRACK;
	public static final Sound ENTITY_TURTLE_EGG_HATCH;
	public static final Sound ENTITY_TURTLE_HURT;
	public static final Sound ENTITY_TURTLE_HURT_BABY;
	public static final Sound ENTITY_TURTLE_LAY_EGG;
	public static final Sound ENTITY_TURTLE_SHAMBLE;
	public static final Sound ENTITY_TURTLE_SHAMBLE_BABY;
	public static final Sound ENTITY_TURTLE_SWIM;
	public static final Sound UI_BUTTON_CLICK;
	public static final Sound UI_TOAST_CHALLENGE_COMPLETE;
	public static final Sound UI_TOAST_IN;
	public static final Sound UI_TOAST_OUT;
	public static final Sound ENTITY_VEX_AMBIENT;
	public static final Sound ENTITY_VEX_CHARGE;
	public static final Sound ENTITY_VEX_DEATH;
	public static final Sound ENTITY_VEX_HURT;
	public static final Sound ENTITY_VILLAGER_AMBIENT;
	public static final Sound ENTITY_VILLAGER_DEATH;
	public static final Sound ENTITY_VILLAGER_HURT;
	public static final Sound ENTITY_VILLAGER_NO;
	public static final Sound ENTITY_VILLAGER_TRADE;
	public static final Sound ENTITY_VILLAGER_YES;
	public static final Sound ENTITY_VINDICATOR_AMBIENT;
	public static final Sound ENTITY_VINDICATOR_DEATH;
	public static final Sound ENTITY_VINDICATOR_HURT;
	public static final Sound BLOCK_LILY_PAD_PLACE;
	public static final Sound BLOCK_WATER_AMBIENT;
	public static final Sound WEATHER_RAIN;
	public static final Sound WEATHER_RAIN_ABOVE;
	public static final Sound ENTITY_WITCH_AMBIENT;
	public static final Sound ENTITY_WITCH_DEATH;
	public static final Sound ENTITY_WITCH_DRINK;
	public static final Sound ENTITY_WITCH_HURT;
	public static final Sound ENTITY_WITCH_THROW;
	public static final Sound ENTITY_WITHER_AMBIENT;
	public static final Sound ENTITY_WITHER_BREAK_BLOCK;
	public static final Sound ENTITY_WITHER_DEATH;
	public static final Sound ENTITY_WITHER_HURT;
	public static final Sound ENTITY_WITHER_SHOOT;
	public static final Sound ENTITY_WITHER_SKELETON_AMBIENT;
	public static final Sound ENTITY_WITHER_SKELETON_DEATH;
	public static final Sound ENTITY_WITHER_SKELETON_HURT;
	public static final Sound ENTITY_WITHER_SKELETON_STEP;
	public static final Sound ENTITY_WITHER_SPAWN;
	public static final Sound ENTITY_WOLF_AMBIENT;
	public static final Sound ENTITY_WOLF_DEATH;
	public static final Sound ENTITY_WOLF_GROWL;
	public static final Sound ENTITY_WOLF_HOWL;
	public static final Sound ENTITY_WOLF_HURT;
	public static final Sound ENTITY_WOLF_PANT;
	public static final Sound ENTITY_WOLF_SHAKE;
	public static final Sound ENTITY_WOLF_STEP;
	public static final Sound ENTITY_WOLF_WHINE;
	public static final Sound BLOCK_WOODEN_DOOR_CLOSE;
	public static final Sound BLOCK_WOODEN_DOOR_OPEN;
	public static final Sound BLOCK_WOODEN_TRAPDOOR_CLOSE;
	public static final Sound BLOCK_WOODEN_TRAPDOOR_OPEN;
	public static final Sound BLOCK_WOOD_BREAK;
	public static final Sound BLOCK_WOODEN_BUTTON_CLICK_OFF;
	public static final Sound BLOCK_WOODEN_BUTTON_CLICK_ON;
	public static final Sound BLOCK_WOOD_FALL;
	public static final Sound BLOCK_WOOD_HIT;
	public static final Sound BLOCK_WOOD_PLACE;
	public static final Sound BLOCK_WOODEN_PRESSURE_PLATE_CLICK_OFF;
	public static final Sound BLOCK_WOODEN_PRESSURE_PLATE_CLICK_ON;
	public static final Sound BLOCK_WOOD_STEP;
	public static final Sound ENTITY_ZOMBIE_AMBIENT;
	public static final Sound ENTITY_ZOMBIE_ATTACK_WOODEN_DOOR;
	public static final Sound ENTITY_ZOMBIE_ATTACK_IRON_DOOR;
	public static final Sound ENTITY_ZOMBIE_BREAK_WOODEN_DOOR;
	public static final Sound ENTITY_ZOMBIE_CONVERTED_TO_DROWNED;
	public static final Sound ENTITY_ZOMBIE_DEATH;
	public static final Sound ENTITY_ZOMBIE_DESTROY_EGG;
	public static final Sound ENTITY_ZOMBIE_HORSE_AMBIENT;
	public static final Sound ENTITY_ZOMBIE_HORSE_DEATH;
	public static final Sound ENTITY_ZOMBIE_HORSE_HURT;
	public static final Sound ENTITY_ZOMBIE_HURT;
	public static final Sound ENTITY_ZOMBIE_INFECT;
	public static final Sound ENTITY_ZOMBIE_PIGMAN_AMBIENT;
	public static final Sound ENTITY_ZOMBIE_PIGMAN_ANGRY;
	public static final Sound ENTITY_ZOMBIE_PIGMAN_DEATH;
	public static final Sound ENTITY_ZOMBIE_PIGMAN_HURT;
	public static final Sound ENTITY_ZOMBIE_STEP;
	public static final Sound ENTITY_ZOMBIE_VILLAGER_AMBIENT;
	public static final Sound ENTITY_ZOMBIE_VILLAGER_CONVERTED;
	public static final Sound ENTITY_ZOMBIE_VILLAGER_CURE;
	public static final Sound ENTITY_ZOMBIE_VILLAGER_DEATH;
	public static final Sound ENTITY_ZOMBIE_VILLAGER_HURT;
	public static final Sound ENTITY_ZOMBIE_VILLAGER_STEP;

	private static Sound get(String id) {
		Sound sound = Registry.SOUND_EVENT.getByIdentifier(new Identifier(id));
		if (sound == null) {
			throw new IllegalStateException("Invalid Sound requested: " + id);
		} else {
			return sound;
		}
	}

	static {
		if (!Bootstrap.isInitialized()) {
			throw new RuntimeException("Accessed Sounds before Bootstrap!");
		} else {
			AMBIENT_CAVE = get("ambient.cave");
			AMBIENT_UNDERWATER_ENTER = get("ambient.underwater.enter");
			AMBIENT_UNDERWATER_EXIT = get("ambient.underwater.exit");
			AMBIENT_UNDERWATER_LOOP = get("ambient.underwater.loop");
			AMBIENT_UNDERWATER_LOOP_ADDITIONS = get("ambient.underwater.loop.additions");
			AMBIENT_UNDERWATER_LOOP_ADDITIONS_RARE = get("ambient.underwater.loop.additions.rare");
			AMBIENT_UNDERWATER_LOOP_ADDITIONS_ULTRA_RARE = get("ambient.underwater.loop.additions.ultra_rare");
			BLOCK_ANVIL_BREAK = get("block.anvil.break");
			BLOCK_ANVIL_DESTROY = get("block.anvil.destroy");
			BLOCK_ANVIL_FALL = get("block.anvil.fall");
			BLOCK_ANVIL_HIT = get("block.anvil.hit");
			BLOCK_ANVIL_LAND = get("block.anvil.land");
			BLOCK_ANVIL_PLACE = get("block.anvil.place");
			BLOCK_ANVIL_STEP = get("block.anvil.step");
			BLOCK_ANVIL_USE = get("block.anvil.use");
			ITEM_ARMOR_EQUIP_CHAIN = get("item.armor.equip_chain");
			ITEM_ARMOR_EQUIP_DIAMOND = get("item.armor.equip_diamond");
			ITEM_ARMOR_EQUIP_ELYTRA = get("item.armor.equip_elytra");
			ITEM_ARMOR_EQUIP_GENERIC = get("item.armor.equip_generic");
			ITEM_ARMOR_EQUIP_GOLD = get("item.armor.equip_gold");
			ITEM_ARMOR_EQUIP_IRON = get("item.armor.equip_iron");
			ITEM_ARMOR_EQUIP_LEATHER = get("item.armor.equip_leather");
			ITEM_ARMOR_EQUIP_TURTLE = get("item.armor.equip_turtle");
			ENTITY_ARMOR_STAND_BREAK = get("entity.armor_stand.break");
			ENTITY_ARMOR_STAND_FALL = get("entity.armor_stand.fall");
			ENTITY_ARMOR_STAND_HIT = get("entity.armor_stand.hit");
			ENTITY_ARMOR_STAND_PLACE = get("entity.armor_stand.place");
			ENTITY_ARROW_HIT = get("entity.arrow.hit");
			ENTITY_ARROW_HIT_PLAYER = get("entity.arrow.hit_player");
			ENTITY_ARROW_SHOOT = get("entity.arrow.shoot");
			ITEM_AXE_STRIP = get("item.axe.strip");
			ENTITY_BAT_AMBIENT = get("entity.bat.ambient");
			ENTITY_BAT_DEATH = get("entity.bat.death");
			ENTITY_BAT_HURT = get("entity.bat.hurt");
			ENTITY_BAT_LOOP = get("entity.bat.loop");
			ENTITY_BAT_TAKEOFF = get("entity.bat.takeoff");
			BLOCK_BEACON_ACTIVATE = get("block.beacon.activate");
			BLOCK_BEACON_AMBIENT = get("block.beacon.ambient");
			BLOCK_BEACON_DEACTIVATE = get("block.beacon.deactivate");
			BLOCK_BEACON_POWER_SELECT = get("block.beacon.power_select");
			ENTITY_BLAZE_AMBIENT = get("entity.blaze.ambient");
			ENTITY_BLAZE_BURN = get("entity.blaze.burn");
			ENTITY_BLAZE_DEATH = get("entity.blaze.death");
			ENTITY_BLAZE_HURT = get("entity.blaze.hurt");
			ENTITY_BLAZE_SHOOT = get("entity.blaze.shoot");
			ENTITY_BOAT_PADDLE_LAND = get("entity.boat.paddle_land");
			ENTITY_BOAT_PADDLE_WATER = get("entity.boat.paddle_water");
			ENTITY_FISHING_BOBBER_RETRIEVE = get("entity.fishing_bobber.retrieve");
			ENTITY_FISHING_BOBBER_SPLASH = get("entity.fishing_bobber.splash");
			ENTITY_FISHING_BOBBER_THROW = get("entity.fishing_bobber.throw");
			ITEM_BOTTLE_EMPTY = get("item.bottle.empty");
			ITEM_BOTTLE_FILL = get("item.bottle.fill");
			ITEM_BOTTLE_FILL_DRAGONBREATH = get("item.bottle.fill_dragonbreath");
			BLOCK_BREWING_STAND_BREW = get("block.brewing_stand.brew");
			BLOCK_BUBBLE_COLUMN_BUBBLE_POP = get("block.bubble_column.bubble_pop");
			BLOCK_BUBBLE_COLUMN_UPWARDS_AMBIENT = get("block.bubble_column.upwards_ambient");
			BLOCK_BUBBLE_COLUMN_UPWARDS_INSIDE = get("block.bubble_column.upwards_inside");
			BLOCK_BUBBLE_COLUMN_WHIRLPOOL_AMBIENT = get("block.bubble_column.whirlpool_ambient");
			BLOCK_BUBBLE_COLUMN_WHIRLPOOL_INSIDE = get("block.bubble_column.whirlpool_inside");
			ITEM_BUCKET_EMPTY = get("item.bucket.empty");
			ITEM_BUCKET_EMPTY_FISH = get("item.bucket.empty_fish");
			ITEM_BUCKET_EMPTY_LAVA = get("item.bucket.empty_lava");
			ITEM_BUCKET_FILL = get("item.bucket.fill");
			ITEM_BUCKET_FILL_FISH = get("item.bucket.fill_fish");
			ITEM_BUCKET_FILL_LAVA = get("item.bucket.fill_lava");
			ENTITY_CAT_AMBIENT = get("entity.cat.ambient");
			ENTITY_CAT_DEATH = get("entity.cat.death");
			ENTITY_CAT_HISS = get("entity.cat.hiss");
			ENTITY_CAT_HURT = get("entity.cat.hurt");
			ENTITY_CAT_PURR = get("entity.cat.purr");
			ENTITY_CAT_PURREOW = get("entity.cat.purreow");
			BLOCK_CHEST_CLOSE = get("block.chest.close");
			BLOCK_CHEST_LOCKED = get("block.chest.locked");
			BLOCK_CHEST_OPEN = get("block.chest.open");
			ENTITY_CHICKEN_AMBIENT = get("entity.chicken.ambient");
			ENTITY_CHICKEN_DEATH = get("entity.chicken.death");
			ENTITY_CHICKEN_EGG = get("entity.chicken.egg");
			ENTITY_CHICKEN_HURT = get("entity.chicken.hurt");
			ENTITY_CHICKEN_STEP = get("entity.chicken.step");
			BLOCK_CHORUS_FLOWER_DEATH = get("block.chorus_flower.death");
			BLOCK_CHORUS_FLOWER_GROW = get("block.chorus_flower.grow");
			ITEM_CHORUS_FRUIT_TELEPORT = get("item.chorus_fruit.teleport");
			BLOCK_WOOL_BREAK = get("block.wool.break");
			BLOCK_WOOL_FALL = get("block.wool.fall");
			BLOCK_WOOL_HIT = get("block.wool.hit");
			BLOCK_WOOL_PLACE = get("block.wool.place");
			BLOCK_WOOL_STEP = get("block.wool.step");
			ENTITY_COD_AMBIENT = get("entity.cod.ambient");
			ENTITY_COD_DEATH = get("entity.cod.death");
			ENTITY_COD_FLOP = get("entity.cod.flop");
			ENTITY_COD_HURT = get("entity.cod.hurt");
			BLOCK_COMPARATOR_CLICK = get("block.comparator.click");
			BLOCK_CONDUIT_ACTIVATE = get("block.conduit.activate");
			BLOCK_CONDUIT_AMBIENT = get("block.conduit.ambient");
			BLOCK_CONDUIT_AMBIENT_SHORT = get("block.conduit.ambient.short");
			BLOCK_CONDUIT_ATTACK_TARGET = get("block.conduit.attack.target");
			BLOCK_CONDUIT_DEACTIVATE = get("block.conduit.deactivate");
			ENTITY_COW_AMBIENT = get("entity.cow.ambient");
			ENTITY_COW_DEATH = get("entity.cow.death");
			ENTITY_COW_HURT = get("entity.cow.hurt");
			ENTITY_COW_MILK = get("entity.cow.milk");
			ENTITY_COW_STEP = get("entity.cow.step");
			ENTITY_CREEPER_DEATH = get("entity.creeper.death");
			ENTITY_CREEPER_HURT = get("entity.creeper.hurt");
			ENTITY_CREEPER_PRIMED = get("entity.creeper.primed");
			BLOCK_DISPENSER_DISPENSE = get("block.dispenser.dispense");
			BLOCK_DISPENSER_FAIL = get("block.dispenser.fail");
			BLOCK_DISPENSER_LAUNCH = get("block.dispenser.launch");
			ENTITY_DOLPHIN_AMBIENT = get("entity.dolphin.ambient");
			ENTITY_DOLPHIN_AMBIENT_WATER = get("entity.dolphin.ambient_water");
			ENTITY_DOLPHIN_ATTACK = get("entity.dolphin.attack");
			ENTITY_DOLPHIN_DEATH = get("entity.dolphin.death");
			ENTITY_DOLPHIN_EAT = get("entity.dolphin.eat");
			ENTITY_DOLPHIN_HURT = get("entity.dolphin.hurt");
			ENTITY_DOLPHIN_JUMP = get("entity.dolphin.jump");
			ENTITY_DOLPHIN_PLAY = get("entity.dolphin.play");
			ENTITY_DOLPHIN_SPLASH = get("entity.dolphin.splash");
			ENTITY_DOLPHIN_SWIM = get("entity.dolphin.swim");
			ENTITY_DONKEY_AMBIENT = get("entity.donkey.ambient");
			ENTITY_DONKEY_ANGRY = get("entity.donkey.angry");
			ENTITY_DONKEY_CHEST = get("entity.donkey.chest");
			ENTITY_DONKEY_DEATH = get("entity.donkey.death");
			ENTITY_DONKEY_HURT = get("entity.donkey.hurt");
			ENTITY_DROWNED_AMBIENT = get("entity.drowned.ambient");
			ENTITY_DROWNED_AMBIENT_WATER = get("entity.drowned.ambient_water");
			ENTITY_DROWNED_DEATH = get("entity.drowned.death");
			ENTITY_DROWNED_DEATH_WATER = get("entity.drowned.death_water");
			ENTITY_DROWNED_HURT = get("entity.drowned.hurt");
			ENTITY_DROWNED_HURT_WATER = get("entity.drowned.hurt_water");
			ENTITY_DROWNED_SHOOT = get("entity.drowned.shoot");
			ENTITY_DROWNED_STEP = get("entity.drowned.step");
			ENTITY_DROWNED_SWIM = get("entity.drowned.swim");
			ENTITY_EGG_THROW = get("entity.egg.throw");
			ENTITY_ELDER_GUARDIAN_AMBIENT = get("entity.elder_guardian.ambient");
			ENTITY_ELDER_GUARDIAN_AMBIENT_LAND = get("entity.elder_guardian.ambient_land");
			ENTITY_ELDER_GUARDIAN_CURSE = get("entity.elder_guardian.curse");
			ENTITY_ELDER_GUARDIAN_DEATH = get("entity.elder_guardian.death");
			ENTITY_ELDER_GUARDIAN_DEATH_LAND = get("entity.elder_guardian.death_land");
			ENTITY_ELDER_GUARDIAN_FLOP = get("entity.elder_guardian.flop");
			ENTITY_ELDER_GUARDIAN_HURT = get("entity.elder_guardian.hurt");
			ENTITY_ELDER_GUARDIAN_HURT_LAND = get("entity.elder_guardian.hurt_land");
			ITEM_ELYTRA_FLYING = get("item.elytra.flying");
			BLOCK_ENCHANTMENT_TABLE_USE = get("block.enchantment_table.use");
			BLOCK_ENDER_CHEST_CLOSE = get("block.ender_chest.close");
			BLOCK_ENDER_CHEST_OPEN = get("block.ender_chest.open");
			ENTITY_ENDER_DRAGON_AMBIENT = get("entity.ender_dragon.ambient");
			ENTITY_ENDER_DRAGON_DEATH = get("entity.ender_dragon.death");
			ENTITY_DRAGON_FIREBALL_EXPLODE = get("entity.dragon_fireball.explode");
			ENTITY_ENDER_DRAGON_FLAP = get("entity.ender_dragon.flap");
			ENTITY_ENDER_DRAGON_GROWL = get("entity.ender_dragon.growl");
			ENTITY_ENDER_DRAGON_HURT = get("entity.ender_dragon.hurt");
			ENTITY_ENDER_DRAGON_SHOOT = get("entity.ender_dragon.shoot");
			ENTITY_ENDER_EYE_DEATH = get("entity.ender_eye.death");
			ENTITY_ENDER_EYE_LAUNCH = get("entity.ender_eye.launch");
			ENTITY_ENDERMAN_AMBIENT = get("entity.enderman.ambient");
			ENTITY_ENDERMAN_DEATH = get("entity.enderman.death");
			ENTITY_ENDERMAN_HURT = get("entity.enderman.hurt");
			ENTITY_ENDERMAN_SCREAM = get("entity.enderman.scream");
			ENTITY_ENDERMAN_STARE = get("entity.enderman.stare");
			ENTITY_ENDERMAN_TELEPORT = get("entity.enderman.teleport");
			ENTITY_ENDERMITE_AMBIENT = get("entity.endermite.ambient");
			ENTITY_ENDERMITE_DEATH = get("entity.endermite.death");
			ENTITY_ENDERMITE_HURT = get("entity.endermite.hurt");
			ENTITY_ENDERMITE_STEP = get("entity.endermite.step");
			ENTITY_ENDER_PEARL_THROW = get("entity.ender_pearl.throw");
			BLOCK_END_GATEWAY_SPAWN = get("block.end_gateway.spawn");
			BLOCK_END_PORTAL_FRAME_FILL = get("block.end_portal_frame.fill");
			BLOCK_END_PORTAL_SPAWN = get("block.end_portal.spawn");
			ENTITY_EVOKER_AMBIENT = get("entity.evoker.ambient");
			ENTITY_EVOKER_CAST_SPELL = get("entity.evoker.cast_spell");
			ENTITY_EVOKER_DEATH = get("entity.evoker.death");
			ENTITY_EVOKER_FANGS_ATTACK = get("entity.evoker_fangs.attack");
			ENTITY_EVOKER_HURT = get("entity.evoker.hurt");
			ENTITY_EVOKER_PREPARE_ATTACK = get("entity.evoker.prepare_attack");
			ENTITY_EVOKER_PREPARE_SUMMON = get("entity.evoker.prepare_summon");
			ENTITY_EVOKER_PREPARE_WOLOLO = get("entity.evoker.prepare_wololo");
			ENTITY_EXPERIENCE_BOTTLE_THROW = get("entity.experience_bottle.throw");
			ENTITY_EXPERIENCE_ORB_PICKUP = get("entity.experience_orb.pickup");
			BLOCK_FENCE_GATE_CLOSE = get("block.fence_gate.close");
			BLOCK_FENCE_GATE_OPEN = get("block.fence_gate.open");
			ITEM_FIRECHARGE_USE = get("item.firecharge.use");
			ENTITY_FIREWORK_ROCKET_BLAST = get("entity.firework_rocket.blast");
			ENTITY_FIREWORK_ROCKET_BLAST_FAR = get("entity.firework_rocket.blast_far");
			ENTITY_FIREWORK_ROCKET_LARGE_BLAST = get("entity.firework_rocket.large_blast");
			ENTITY_FIREWORK_ROCKET_LARGE_BLAST_FAR = get("entity.firework_rocket.large_blast_far");
			ENTITY_FIREWORK_ROCKET_LAUNCH = get("entity.firework_rocket.launch");
			ENTITY_FIREWORK_ROCKET_SHOOT = get("entity.firework_rocket.shoot");
			ENTITY_FIREWORK_ROCKET_TWINKLE = get("entity.firework_rocket.twinkle");
			ENTITY_FIREWORK_ROCKET_TWINKLE_FAR = get("entity.firework_rocket.twinkle_far");
			BLOCK_FIRE_AMBIENT = get("block.fire.ambient");
			BLOCK_FIRE_EXTINGUISH = get("block.fire.extinguish");
			ENTITY_FISH_SWIM = get("entity.fish.swim");
			ITEM_FLINTANDSTEEL_USE = get("item.flintandsteel.use");
			BLOCK_FURNACE_FIRE_CRACKLE = get("block.furnace.fire_crackle");
			ENTITY_GENERIC_BIG_FALL = get("entity.generic.big_fall");
			ENTITY_GENERIC_BURN = get("entity.generic.burn");
			ENTITY_GENERIC_DEATH = get("entity.generic.death");
			ENTITY_GENERIC_DRINK = get("entity.generic.drink");
			ENTITY_GENERIC_EAT = get("entity.generic.eat");
			ENTITY_GENERIC_EXPLODE = get("entity.generic.explode");
			ENTITY_GENERIC_EXTINGUISH_FIRE = get("entity.generic.extinguish_fire");
			ENTITY_GENERIC_HURT = get("entity.generic.hurt");
			ENTITY_GENERIC_SMALL_FALL = get("entity.generic.small_fall");
			ENTITY_GENERIC_SPLASH = get("entity.generic.splash");
			ENTITY_GENERIC_SWIM = get("entity.generic.swim");
			ENTITY_GHAST_AMBIENT = get("entity.ghast.ambient");
			ENTITY_GHAST_DEATH = get("entity.ghast.death");
			ENTITY_GHAST_HURT = get("entity.ghast.hurt");
			ENTITY_GHAST_SCREAM = get("entity.ghast.scream");
			ENTITY_GHAST_SHOOT = get("entity.ghast.shoot");
			ENTITY_GHAST_WARN = get("entity.ghast.warn");
			BLOCK_GLASS_BREAK = get("block.glass.break");
			BLOCK_GLASS_FALL = get("block.glass.fall");
			BLOCK_GLASS_HIT = get("block.glass.hit");
			BLOCK_GLASS_PLACE = get("block.glass.place");
			BLOCK_GLASS_STEP = get("block.glass.step");
			BLOCK_GRASS_BREAK = get("block.grass.break");
			BLOCK_GRASS_FALL = get("block.grass.fall");
			BLOCK_GRASS_HIT = get("block.grass.hit");
			BLOCK_GRASS_PLACE = get("block.grass.place");
			BLOCK_GRASS_STEP = get("block.grass.step");
			BLOCK_WET_GRASS_BREAK = get("block.wet_grass.break");
			BLOCK_WET_GRASS_FALL = get("block.wet_grass.fall");
			BLOCK_WET_GRASS_HIT = get("block.wet_grass.hit");
			BLOCK_WET_GRASS_PLACE = get("block.wet_grass.place");
			BLOCK_WET_GRASS_STEP = get("block.wet_grass.step");
			BLOCK_CORAL_BLOCK_BREAK = get("block.coral_block.break");
			BLOCK_CORAL_BLOCK_FALL = get("block.coral_block.fall");
			BLOCK_CORAL_BLOCK_HIT = get("block.coral_block.hit");
			BLOCK_CORAL_BLOCK_PLACE = get("block.coral_block.place");
			BLOCK_CORAL_BLOCK_STEP = get("block.coral_block.step");
			BLOCK_GRAVEL_BREAK = get("block.gravel.break");
			BLOCK_GRAVEL_FALL = get("block.gravel.fall");
			BLOCK_GRAVEL_HIT = get("block.gravel.hit");
			BLOCK_GRAVEL_PLACE = get("block.gravel.place");
			BLOCK_GRAVEL_STEP = get("block.gravel.step");
			ENTITY_GUARDIAN_AMBIENT = get("entity.guardian.ambient");
			ENTITY_GUARDIAN_AMBIENT_LAND = get("entity.guardian.ambient_land");
			ENTITY_GUARDIAN_ATTACK = get("entity.guardian.attack");
			ENTITY_GUARDIAN_DEATH = get("entity.guardian.death");
			ENTITY_GUARDIAN_DEATH_LAND = get("entity.guardian.death_land");
			ENTITY_GUARDIAN_FLOP = get("entity.guardian.flop");
			ENTITY_GUARDIAN_HURT = get("entity.guardian.hurt");
			ENTITY_GUARDIAN_HURT_LAND = get("entity.guardian.hurt_land");
			ITEM_HOE_TILL = get("item.hoe.till");
			ENTITY_HORSE_AMBIENT = get("entity.horse.ambient");
			ENTITY_HORSE_ANGRY = get("entity.horse.angry");
			ENTITY_HORSE_ARMOR = get("entity.horse.armor");
			ENTITY_HORSE_BREATHE = get("entity.horse.breathe");
			ENTITY_HORSE_DEATH = get("entity.horse.death");
			ENTITY_HORSE_EAT = get("entity.horse.eat");
			ENTITY_HORSE_GALLOP = get("entity.horse.gallop");
			ENTITY_HORSE_HURT = get("entity.horse.hurt");
			ENTITY_HORSE_JUMP = get("entity.horse.jump");
			ENTITY_HORSE_LAND = get("entity.horse.land");
			ENTITY_HORSE_SADDLE = get("entity.horse.saddle");
			ENTITY_HORSE_STEP = get("entity.horse.step");
			ENTITY_HORSE_STEP_WOOD = get("entity.horse.step_wood");
			ENTITY_HOSTILE_BIG_FALL = get("entity.hostile.big_fall");
			ENTITY_HOSTILE_DEATH = get("entity.hostile.death");
			ENTITY_HOSTILE_HURT = get("entity.hostile.hurt");
			ENTITY_HOSTILE_SMALL_FALL = get("entity.hostile.small_fall");
			ENTITY_HOSTILE_SPLASH = get("entity.hostile.splash");
			ENTITY_HOSTILE_SWIM = get("entity.hostile.swim");
			ENTITY_HUSK_AMBIENT = get("entity.husk.ambient");
			ENTITY_HUSK_CONVERTED_TO_ZOMBIE = get("entity.husk.converted_to_zombie");
			ENTITY_HUSK_DEATH = get("entity.husk.death");
			ENTITY_HUSK_HURT = get("entity.husk.hurt");
			ENTITY_HUSK_STEP = get("entity.husk.step");
			ENTITY_ILLUSIONER_AMBIENT = get("entity.illusioner.ambient");
			ENTITY_ILLUSIONER_CAST_SPELL = get("entity.illusioner.cast_spell");
			ENTITY_ILLUSIONER_DEATH = get("entity.illusioner.death");
			ENTITY_ILLUSIONER_HURT = get("entity.illusioner.hurt");
			ENTITY_ILLUSIONER_MIRROR_MOVE = get("entity.illusioner.mirror_move");
			ENTITY_ILLUSIONER_PREPARE_BLINDNESS = get("entity.illusioner.prepare_blindness");
			ENTITY_ILLUSIONER_PREPARE_MIRROR = get("entity.illusioner.prepare_mirror");
			BLOCK_IRON_DOOR_CLOSE = get("block.iron_door.close");
			BLOCK_IRON_DOOR_OPEN = get("block.iron_door.open");
			ENTITY_IRON_GOLEM_ATTACK = get("entity.iron_golem.attack");
			ENTITY_IRON_GOLEM_DEATH = get("entity.iron_golem.death");
			ENTITY_IRON_GOLEM_HURT = get("entity.iron_golem.hurt");
			ENTITY_IRON_GOLEM_STEP = get("entity.iron_golem.step");
			BLOCK_IRON_TRAPDOOR_CLOSE = get("block.iron_trapdoor.close");
			BLOCK_IRON_TRAPDOOR_OPEN = get("block.iron_trapdoor.open");
			ENTITY_ITEM_FRAME_ADD_ITEM = get("entity.item_frame.add_item");
			ENTITY_ITEM_FRAME_BREAK = get("entity.item_frame.break");
			ENTITY_ITEM_FRAME_PLACE = get("entity.item_frame.place");
			ENTITY_ITEM_FRAME_REMOVE_ITEM = get("entity.item_frame.remove_item");
			ENTITY_ITEM_FRAME_ROTATE_ITEM = get("entity.item_frame.rotate_item");
			ENTITY_ITEM_BREAK = get("entity.item.break");
			ENTITY_ITEM_PICKUP = get("entity.item.pickup");
			BLOCK_LADDER_BREAK = get("block.ladder.break");
			BLOCK_LADDER_FALL = get("block.ladder.fall");
			BLOCK_LADDER_HIT = get("block.ladder.hit");
			BLOCK_LADDER_PLACE = get("block.ladder.place");
			BLOCK_LADDER_STEP = get("block.ladder.step");
			BLOCK_LAVA_AMBIENT = get("block.lava.ambient");
			BLOCK_LAVA_EXTINGUISH = get("block.lava.extinguish");
			BLOCK_LAVA_POP = get("block.lava.pop");
			ENTITY_LEASH_KNOT_BREAK = get("entity.leash_knot.break");
			ENTITY_LEASH_KNOT_PLACE = get("entity.leash_knot.place");
			BLOCK_LEVER_CLICK = get("block.lever.click");
			ENTITY_LIGHTNING_BOLT_IMPACT = get("entity.lightning_bolt.impact");
			ENTITY_LIGHTNING_BOLT_THUNDER = get("entity.lightning_bolt.thunder");
			ENTITY_LINGERING_POTION_THROW = get("entity.lingering_potion.throw");
			ENTITY_LLAMA_AMBIENT = get("entity.llama.ambient");
			ENTITY_LLAMA_ANGRY = get("entity.llama.angry");
			ENTITY_LLAMA_CHEST = get("entity.llama.chest");
			ENTITY_LLAMA_DEATH = get("entity.llama.death");
			ENTITY_LLAMA_EAT = get("entity.llama.eat");
			ENTITY_LLAMA_HURT = get("entity.llama.hurt");
			ENTITY_LLAMA_SPIT = get("entity.llama.spit");
			ENTITY_LLAMA_STEP = get("entity.llama.step");
			ENTITY_LLAMA_SWAG = get("entity.llama.swag");
			ENTITY_MAGMA_CUBE_DEATH = get("entity.magma_cube.death");
			ENTITY_MAGMA_CUBE_HURT = get("entity.magma_cube.hurt");
			ENTITY_MAGMA_CUBE_JUMP = get("entity.magma_cube.jump");
			ENTITY_MAGMA_CUBE_SQUISH = get("entity.magma_cube.squish");
			BLOCK_METAL_BREAK = get("block.metal.break");
			BLOCK_METAL_FALL = get("block.metal.fall");
			BLOCK_METAL_HIT = get("block.metal.hit");
			BLOCK_METAL_PLACE = get("block.metal.place");
			BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF = get("block.metal_pressure_plate.click_off");
			BLOCK_METAL_PRESSURE_PLATE_CLICK_ON = get("block.metal_pressure_plate.click_on");
			BLOCK_METAL_STEP = get("block.metal.step");
			ENTITY_MINECART_INSIDE = get("entity.minecart.inside");
			ENTITY_MINECART_RIDING = get("entity.minecart.riding");
			ENTITY_MOOSHROOM_SHEAR = get("entity.mooshroom.shear");
			ENTITY_MULE_AMBIENT = get("entity.mule.ambient");
			ENTITY_MULE_CHEST = get("entity.mule.chest");
			ENTITY_MULE_DEATH = get("entity.mule.death");
			ENTITY_MULE_HURT = get("entity.mule.hurt");
			MUSIC_CREATIVE = get("music.creative");
			MUSIC_CREDITS = get("music.credits");
			MUSIC_DRAGON = get("music.dragon");
			MUSIC_END = get("music.end");
			MUSIC_GAME = get("music.game");
			MUSIC_MENU = get("music.menu");
			MUSIC_NETHER = get("music.nether");
			MUSIC_UNDER_WATER = get("music.under_water");
			BLOCK_NOTE_BLOCK_BASEDRUM = get("block.note_block.basedrum");
			BLOCK_NOTE_BLOCK_BASS = get("block.note_block.bass");
			BLOCK_NOTE_BLOCK_BELL = get("block.note_block.bell");
			BLOCK_NOTE_BLOCK_CHIME = get("block.note_block.chime");
			BLOCK_NOTE_BLOCK_FLUTE = get("block.note_block.flute");
			BLOCK_NOTE_BLOCK_GUITAR = get("block.note_block.guitar");
			BLOCK_NOTE_BLOCK_HARP = get("block.note_block.harp");
			BLOCK_NOTE_BLOCK_HAT = get("block.note_block.hat");
			BLOCK_NOTE_BLOCK_PLING = get("block.note_block.pling");
			BLOCK_NOTE_BLOCK_SNARE = get("block.note_block.snare");
			BLOCK_NOTE_BLOCK_XYLOPHONE = get("block.note_block.xylophone");
			ENTITY_PAINTING_BREAK = get("entity.painting.break");
			ENTITY_PAINTING_PLACE = get("entity.painting.place");
			ENTITY_PARROT_AMBIENT = get("entity.parrot.ambient");
			ENTITY_PARROT_DEATH = get("entity.parrot.death");
			ENTITY_PARROT_EAT = get("entity.parrot.eat");
			ENTITY_PARROT_FLY = get("entity.parrot.fly");
			ENTITY_PARROT_HURT = get("entity.parrot.hurt");
			ENTITY_PARROT_IMITATE_BLAZE = get("entity.parrot.imitate.blaze");
			ENTITY_PARROT_IMITATE_CREEPER = get("entity.parrot.imitate.creeper");
			ENTITY_PARROT_IMITATE_DROWNED = get("entity.parrot.imitate.drowned");
			ENTITY_PARROT_IMITATE_ELDER_GUARDIAN = get("entity.parrot.imitate.elder_guardian");
			ENTITY_PARROT_IMITATE_ENDER_DRAGON = get("entity.parrot.imitate.ender_dragon");
			ENTITY_PARROT_IMITATE_ENDERMAN = get("entity.parrot.imitate.enderman");
			ENTITY_PARROT_IMITATE_ENDERMITE = get("entity.parrot.imitate.endermite");
			ENTITY_PARROT_IMITATE_EVOKER = get("entity.parrot.imitate.evoker");
			ENTITY_PARROT_IMITATE_GHAST = get("entity.parrot.imitate.ghast");
			ENTITY_PARROT_IMITATE_HUSK = get("entity.parrot.imitate.husk");
			ENTITY_PARROT_IMITATE_ILLUSIONER = get("entity.parrot.imitate.illusioner");
			ENTITY_PARROT_IMITATE_MAGMA_CUBE = get("entity.parrot.imitate.magma_cube");
			ENTITY_PARROT_IMITATE_PHANTOM = get("entity.parrot.imitate.phantom");
			ENTITY_PARROT_IMITATE_POLAR_BEAR = get("entity.parrot.imitate.polar_bear");
			ENTITY_PARROT_IMITATE_SHULKER = get("entity.parrot.imitate.shulker");
			ENTITY_PARROT_IMITATE_SILVERFISH = get("entity.parrot.imitate.silverfish");
			ENTITY_PARROT_IMITATE_SKELETON = get("entity.parrot.imitate.skeleton");
			ENTITY_PARROT_IMITATE_SLIME = get("entity.parrot.imitate.slime");
			ENTITY_PARROT_IMITATE_SPIDER = get("entity.parrot.imitate.spider");
			ENTITY_PARROT_IMITATE_STRAY = get("entity.parrot.imitate.stray");
			ENTITY_PARROT_IMITATE_VEX = get("entity.parrot.imitate.vex");
			ENTITY_PARROT_IMITATE_VINDICATOR = get("entity.parrot.imitate.vindicator");
			ENTITY_PARROT_IMITATE_WITCH = get("entity.parrot.imitate.witch");
			ENTITY_PARROT_IMITATE_WITHER = get("entity.parrot.imitate.wither");
			ENTITY_PARROT_IMITATE_WITHER_SKELETON = get("entity.parrot.imitate.wither_skeleton");
			ENTITY_PARROT_IMITATE_WOLF = get("entity.parrot.imitate.wolf");
			ENTITY_PARROT_IMITATE_ZOMBIE = get("entity.parrot.imitate.zombie");
			ENTITY_PARROT_IMITATE_ZOMBIE_PIGMAN = get("entity.parrot.imitate.zombie_pigman");
			ENTITY_PARROT_IMITATE_ZOMBIE_VILLAGER = get("entity.parrot.imitate.zombie_villager");
			ENTITY_PARROT_STEP = get("entity.parrot.step");
			ENTITY_PHANTOM_AMBIENT = get("entity.phantom.ambient");
			ENTITY_PHANTOM_BITE = get("entity.phantom.bite");
			ENTITY_PHANTOM_DEATH = get("entity.phantom.death");
			ENTITY_PHANTOM_FLAP = get("entity.phantom.flap");
			ENTITY_PHANTOM_HURT = get("entity.phantom.hurt");
			ENTITY_PHANTOM_SWOOP = get("entity.phantom.swoop");
			ENTITY_PIG_AMBIENT = get("entity.pig.ambient");
			ENTITY_PIG_DEATH = get("entity.pig.death");
			ENTITY_PIG_HURT = get("entity.pig.hurt");
			ENTITY_PIG_SADDLE = get("entity.pig.saddle");
			ENTITY_PIG_STEP = get("entity.pig.step");
			BLOCK_PISTON_CONTRACT = get("block.piston.contract");
			BLOCK_PISTON_EXTEND = get("block.piston.extend");
			ENTITY_PLAYER_ATTACK_CRIT = get("entity.player.attack.crit");
			ENTITY_PLAYER_ATTACK_KNOCKBACK = get("entity.player.attack.knockback");
			ENTITY_PLAYER_ATTACK_NODAMAGE = get("entity.player.attack.nodamage");
			ENTITY_PLAYER_ATTACK_STRONG = get("entity.player.attack.strong");
			ENTITY_PLAYER_ATTACK_SWEEP = get("entity.player.attack.sweep");
			ENTITY_PLAYER_ATTACK_WEAK = get("entity.player.attack.weak");
			ENTITY_PLAYER_BIG_FALL = get("entity.player.big_fall");
			ENTITY_PLAYER_BREATH = get("entity.player.breath");
			ENTITY_PLAYER_BURP = get("entity.player.burp");
			ENTITY_PLAYER_DEATH = get("entity.player.death");
			ENTITY_PLAYER_HURT = get("entity.player.hurt");
			ENTITY_PLAYER_HURT_DROWN = get("entity.player.hurt_drown");
			ENTITY_PLAYER_HURT_ON_FIRE = get("entity.player.hurt_on_fire");
			ENTITY_PLAYER_LEVELUP = get("entity.player.levelup");
			ENTITY_PLAYER_SMALL_FALL = get("entity.player.small_fall");
			ENTITY_PLAYER_SPLASH = get("entity.player.splash");
			ENTITY_PLAYER_SPLASH_HIGH_SPEED = get("entity.player.splash.high_speed");
			ENTITY_PLAYER_SWIM = get("entity.player.swim");
			ENTITY_POLAR_BEAR_AMBIENT = get("entity.polar_bear.ambient");
			ENTITY_POLAR_BEAR_AMBIENT_BABY = get("entity.polar_bear.ambient_baby");
			ENTITY_POLAR_BEAR_DEATH = get("entity.polar_bear.death");
			ENTITY_POLAR_BEAR_HURT = get("entity.polar_bear.hurt");
			ENTITY_POLAR_BEAR_STEP = get("entity.polar_bear.step");
			ENTITY_POLAR_BEAR_WARNING = get("entity.polar_bear.warning");
			BLOCK_PORTAL_AMBIENT = get("block.portal.ambient");
			BLOCK_PORTAL_TRAVEL = get("block.portal.travel");
			BLOCK_PORTAL_TRIGGER = get("block.portal.trigger");
			ENTITY_PUFFER_FISH_AMBIENT = get("entity.puffer_fish.ambient");
			ENTITY_PUFFER_FISH_BLOW_OUT = get("entity.puffer_fish.blow_out");
			ENTITY_PUFFER_FISH_BLOW_UP = get("entity.puffer_fish.blow_up");
			ENTITY_PUFFER_FISH_DEATH = get("entity.puffer_fish.death");
			ENTITY_PUFFER_FISH_FLOP = get("entity.puffer_fish.flop");
			ENTITY_PUFFER_FISH_HURT = get("entity.puffer_fish.hurt");
			ENTITY_PUFFER_FISH_STING = get("entity.puffer_fish.sting");
			BLOCK_PUMPKIN_CARVE = get("block.pumpkin.carve");
			ENTITY_RABBIT_AMBIENT = get("entity.rabbit.ambient");
			ENTITY_RABBIT_ATTACK = get("entity.rabbit.attack");
			ENTITY_RABBIT_DEATH = get("entity.rabbit.death");
			ENTITY_RABBIT_HURT = get("entity.rabbit.hurt");
			ENTITY_RABBIT_JUMP = get("entity.rabbit.jump");
			MUSIC_DISC_11 = get("music_disc.11");
			MUSIC_DISC_13 = get("music_disc.13");
			MUSIC_DISC_BLOCKS = get("music_disc.blocks");
			MUSIC_DISC_CAT = get("music_disc.cat");
			MUSIC_DISC_CHIRP = get("music_disc.chirp");
			MUSIC_DISC_FAR = get("music_disc.far");
			MUSIC_DISC_MALL = get("music_disc.mall");
			MUSIC_DISC_MELLOHI = get("music_disc.mellohi");
			MUSIC_DISC_STAL = get("music_disc.stal");
			MUSIC_DISC_STRAD = get("music_disc.strad");
			MUSIC_DISC_WAIT = get("music_disc.wait");
			MUSIC_DISC_WARD = get("music_disc.ward");
			BLOCK_REDSTONE_TORCH_BURNOUT = get("block.redstone_torch.burnout");
			ENTITY_SALMON_AMBIENT = get("entity.salmon.ambient");
			ENTITY_SALMON_DEATH = get("entity.salmon.death");
			ENTITY_SALMON_FLOP = get("entity.salmon.flop");
			ENTITY_SALMON_HURT = get("entity.salmon.hurt");
			BLOCK_SAND_BREAK = get("block.sand.break");
			BLOCK_SAND_FALL = get("block.sand.fall");
			BLOCK_SAND_HIT = get("block.sand.hit");
			BLOCK_SAND_PLACE = get("block.sand.place");
			BLOCK_SAND_STEP = get("block.sand.step");
			ENTITY_SHEEP_AMBIENT = get("entity.sheep.ambient");
			ENTITY_SHEEP_DEATH = get("entity.sheep.death");
			ENTITY_SHEEP_HURT = get("entity.sheep.hurt");
			ENTITY_SHEEP_SHEAR = get("entity.sheep.shear");
			ENTITY_SHEEP_STEP = get("entity.sheep.step");
			ITEM_SHIELD_BLOCK = get("item.shield.block");
			ITEM_SHIELD_BREAK = get("item.shield.break");
			ITEM_SHOVEL_FLATTEN = get("item.shovel.flatten");
			ENTITY_SHULKER_AMBIENT = get("entity.shulker.ambient");
			BLOCK_SHULKER_BOX_CLOSE = get("block.shulker_box.close");
			BLOCK_SHULKER_BOX_OPEN = get("block.shulker_box.open");
			ENTITY_SHULKER_BULLET_HIT = get("entity.shulker_bullet.hit");
			ENTITY_SHULKER_BULLET_HURT = get("entity.shulker_bullet.hurt");
			ENTITY_SHULKER_CLOSE = get("entity.shulker.close");
			ENTITY_SHULKER_DEATH = get("entity.shulker.death");
			ENTITY_SHULKER_HURT = get("entity.shulker.hurt");
			ENTITY_SHULKER_HURT_CLOSED = get("entity.shulker.hurt_closed");
			ENTITY_SHULKER_OPEN = get("entity.shulker.open");
			ENTITY_SHULKER_SHOOT = get("entity.shulker.shoot");
			ENTITY_SHULKER_TELEPORT = get("entity.shulker.teleport");
			ENTITY_SILVERFISH_AMBIENT = get("entity.silverfish.ambient");
			ENTITY_SILVERFISH_DEATH = get("entity.silverfish.death");
			ENTITY_SILVERFISH_HURT = get("entity.silverfish.hurt");
			ENTITY_SILVERFISH_STEP = get("entity.silverfish.step");
			ENTITY_SKELETON_AMBIENT = get("entity.skeleton.ambient");
			ENTITY_SKELETON_DEATH = get("entity.skeleton.death");
			ENTITY_SKELETON_HORSE_AMBIENT = get("entity.skeleton_horse.ambient");
			ENTITY_SKELETON_HORSE_DEATH = get("entity.skeleton_horse.death");
			ENTITY_SKELETON_HORSE_HURT = get("entity.skeleton_horse.hurt");
			ENTITY_SKELETON_HORSE_SWIM = get("entity.skeleton_horse.swim");
			ENTITY_SKELETON_HORSE_AMBIENT_WATER = get("entity.skeleton_horse.ambient_water");
			ENTITY_SKELETON_HORSE_GALLOP_WATER = get("entity.skeleton_horse.gallop_water");
			ENTITY_SKELETON_HORSE_JUMP_WATER = get("entity.skeleton_horse.jump_water");
			ENTITY_SKELETON_HORSE_STEP_WATER = get("entity.skeleton_horse.step_water");
			ENTITY_SKELETON_HURT = get("entity.skeleton.hurt");
			ENTITY_SKELETON_SHOOT = get("entity.skeleton.shoot");
			ENTITY_SKELETON_STEP = get("entity.skeleton.step");
			ENTITY_SLIME_ATTACK = get("entity.slime.attack");
			ENTITY_SLIME_DEATH = get("entity.slime.death");
			ENTITY_SLIME_HURT = get("entity.slime.hurt");
			ENTITY_SLIME_JUMP = get("entity.slime.jump");
			ENTITY_SLIME_SQUISH = get("entity.slime.squish");
			BLOCK_SLIME_BLOCK_BREAK = get("block.slime_block.break");
			BLOCK_SLIME_BLOCK_FALL = get("block.slime_block.fall");
			BLOCK_SLIME_BLOCK_HIT = get("block.slime_block.hit");
			BLOCK_SLIME_BLOCK_PLACE = get("block.slime_block.place");
			BLOCK_SLIME_BLOCK_STEP = get("block.slime_block.step");
			ENTITY_MAGMA_CUBE_DEATH_SMALL = get("entity.magma_cube.death_small");
			ENTITY_MAGMA_CUBE_HURT_SMALL = get("entity.magma_cube.hurt_small");
			ENTITY_MAGMA_CUBE_SQUISH_SMALL = get("entity.magma_cube.squish_small");
			ENTITY_SLIME_DEATH_SMALL = get("entity.slime.death_small");
			ENTITY_SLIME_HURT_SMALL = get("entity.slime.hurt_small");
			ENTITY_SLIME_JUMP_SMALL = get("entity.slime.jump_small");
			ENTITY_SLIME_SQUISH_SMALL = get("entity.slime.squish_small");
			ENTITY_SNOWBALL_THROW = get("entity.snowball.throw");
			BLOCK_SNOW_BREAK = get("block.snow.break");
			BLOCK_SNOW_FALL = get("block.snow.fall");
			ENTITY_SNOW_GOLEM_AMBIENT = get("entity.snow_golem.ambient");
			ENTITY_SNOW_GOLEM_DEATH = get("entity.snow_golem.death");
			ENTITY_SNOW_GOLEM_HURT = get("entity.snow_golem.hurt");
			ENTITY_SNOW_GOLEM_SHOOT = get("entity.snow_golem.shoot");
			BLOCK_SNOW_HIT = get("block.snow.hit");
			BLOCK_SNOW_PLACE = get("block.snow.place");
			BLOCK_SNOW_STEP = get("block.snow.step");
			ENTITY_SPIDER_AMBIENT = get("entity.spider.ambient");
			ENTITY_SPIDER_DEATH = get("entity.spider.death");
			ENTITY_SPIDER_HURT = get("entity.spider.hurt");
			ENTITY_SPIDER_STEP = get("entity.spider.step");
			ENTITY_SPLASH_POTION_BREAK = get("entity.splash_potion.break");
			ENTITY_SPLASH_POTION_THROW = get("entity.splash_potion.throw");
			ENTITY_SQUID_AMBIENT = get("entity.squid.ambient");
			ENTITY_SQUID_DEATH = get("entity.squid.death");
			ENTITY_SQUID_HURT = get("entity.squid.hurt");
			ENTITY_SQUID_SQUIRT = get("entity.squid.squirt");
			BLOCK_STONE_BREAK = get("block.stone.break");
			BLOCK_STONE_BUTTON_CLICK_OFF = get("block.stone_button.click_off");
			BLOCK_STONE_BUTTON_CLICK_ON = get("block.stone_button.click_on");
			BLOCK_STONE_FALL = get("block.stone.fall");
			BLOCK_STONE_HIT = get("block.stone.hit");
			BLOCK_STONE_PLACE = get("block.stone.place");
			BLOCK_STONE_PRESSURE_PLATE_CLICK_OFF = get("block.stone_pressure_plate.click_off");
			BLOCK_STONE_PRESSURE_PLATE_CLICK_ON = get("block.stone_pressure_plate.click_on");
			BLOCK_STONE_STEP = get("block.stone.step");
			ENTITY_STRAY_AMBIENT = get("entity.stray.ambient");
			ENTITY_STRAY_DEATH = get("entity.stray.death");
			ENTITY_STRAY_HURT = get("entity.stray.hurt");
			ENTITY_STRAY_STEP = get("entity.stray.step");
			ENCHANT_THORNS_HIT = get("enchant.thorns.hit");
			ENTITY_TNT_PRIMED = get("entity.tnt.primed");
			ITEM_TOTEM_USE = get("item.totem.use");
			ITEM_TRIDENT_HIT = get("item.trident.hit");
			ITEM_TRIDENT_HIT_GROUND = get("item.trident.hit_ground");
			ITEM_TRIDENT_RETURN = get("item.trident.return");
			ITEM_TRIDENT_RIPTIDE_1 = get("item.trident.riptide_1");
			ITEM_TRIDENT_RIPTIDE_2 = get("item.trident.riptide_2");
			ITEM_TRIDENT_RIPTIDE_3 = get("item.trident.riptide_3");
			ITEM_TRIDENT_THROW = get("item.trident.throw");
			ITEM_TRIDENT_THUNDER = get("item.trident.thunder");
			BLOCK_TRIPWIRE_ATTACH = get("block.tripwire.attach");
			BLOCK_TRIPWIRE_CLICK_OFF = get("block.tripwire.click_off");
			BLOCK_TRIPWIRE_CLICK_ON = get("block.tripwire.click_on");
			BLOCK_TRIPWIRE_DETACH = get("block.tripwire.detach");
			ENTITY_TROPICAL_FISH_AMBIENT = get("entity.tropical_fish.ambient");
			ENTITY_TROPICAL_FISH_DEATH = get("entity.tropical_fish.death");
			ENTITY_TROPICAL_FISH_FLOP = get("entity.tropical_fish.flop");
			ENTITY_TROPICAL_FISH_HURT = get("entity.tropical_fish.hurt");
			ENTITY_TURTLE_AMBIENT_LAND = get("entity.turtle.ambient_land");
			ENTITY_TURTLE_DEATH = get("entity.turtle.death");
			ENTITY_TURTLE_DEATH_BABY = get("entity.turtle.death_baby");
			ENTITY_TURTLE_EGG_BREAK = get("entity.turtle.egg_break");
			ENTITY_TURTLE_EGG_CRACK = get("entity.turtle.egg_crack");
			ENTITY_TURTLE_EGG_HATCH = get("entity.turtle.egg_hatch");
			ENTITY_TURTLE_HURT = get("entity.turtle.hurt");
			ENTITY_TURTLE_HURT_BABY = get("entity.turtle.hurt_baby");
			ENTITY_TURTLE_LAY_EGG = get("entity.turtle.lay_egg");
			ENTITY_TURTLE_SHAMBLE = get("entity.turtle.shamble");
			ENTITY_TURTLE_SHAMBLE_BABY = get("entity.turtle.shamble_baby");
			ENTITY_TURTLE_SWIM = get("entity.turtle.swim");
			UI_BUTTON_CLICK = get("ui.button.click");
			UI_TOAST_CHALLENGE_COMPLETE = get("ui.toast.challenge_complete");
			UI_TOAST_IN = get("ui.toast.in");
			UI_TOAST_OUT = get("ui.toast.out");
			ENTITY_VEX_AMBIENT = get("entity.vex.ambient");
			ENTITY_VEX_CHARGE = get("entity.vex.charge");
			ENTITY_VEX_DEATH = get("entity.vex.death");
			ENTITY_VEX_HURT = get("entity.vex.hurt");
			ENTITY_VILLAGER_AMBIENT = get("entity.villager.ambient");
			ENTITY_VILLAGER_DEATH = get("entity.villager.death");
			ENTITY_VILLAGER_HURT = get("entity.villager.hurt");
			ENTITY_VILLAGER_NO = get("entity.villager.no");
			ENTITY_VILLAGER_TRADE = get("entity.villager.trade");
			ENTITY_VILLAGER_YES = get("entity.villager.yes");
			ENTITY_VINDICATOR_AMBIENT = get("entity.vindicator.ambient");
			ENTITY_VINDICATOR_DEATH = get("entity.vindicator.death");
			ENTITY_VINDICATOR_HURT = get("entity.vindicator.hurt");
			BLOCK_LILY_PAD_PLACE = get("block.lily_pad.place");
			BLOCK_WATER_AMBIENT = get("block.water.ambient");
			WEATHER_RAIN = get("weather.rain");
			WEATHER_RAIN_ABOVE = get("weather.rain.above");
			ENTITY_WITCH_AMBIENT = get("entity.witch.ambient");
			ENTITY_WITCH_DEATH = get("entity.witch.death");
			ENTITY_WITCH_DRINK = get("entity.witch.drink");
			ENTITY_WITCH_HURT = get("entity.witch.hurt");
			ENTITY_WITCH_THROW = get("entity.witch.throw");
			ENTITY_WITHER_AMBIENT = get("entity.wither.ambient");
			ENTITY_WITHER_BREAK_BLOCK = get("entity.wither.break_block");
			ENTITY_WITHER_DEATH = get("entity.wither.death");
			ENTITY_WITHER_HURT = get("entity.wither.hurt");
			ENTITY_WITHER_SHOOT = get("entity.wither.shoot");
			ENTITY_WITHER_SKELETON_AMBIENT = get("entity.wither_skeleton.ambient");
			ENTITY_WITHER_SKELETON_DEATH = get("entity.wither_skeleton.death");
			ENTITY_WITHER_SKELETON_HURT = get("entity.wither_skeleton.hurt");
			ENTITY_WITHER_SKELETON_STEP = get("entity.wither_skeleton.step");
			ENTITY_WITHER_SPAWN = get("entity.wither.spawn");
			ENTITY_WOLF_AMBIENT = get("entity.wolf.ambient");
			ENTITY_WOLF_DEATH = get("entity.wolf.death");
			ENTITY_WOLF_GROWL = get("entity.wolf.growl");
			ENTITY_WOLF_HOWL = get("entity.wolf.howl");
			ENTITY_WOLF_HURT = get("entity.wolf.hurt");
			ENTITY_WOLF_PANT = get("entity.wolf.pant");
			ENTITY_WOLF_SHAKE = get("entity.wolf.shake");
			ENTITY_WOLF_STEP = get("entity.wolf.step");
			ENTITY_WOLF_WHINE = get("entity.wolf.whine");
			BLOCK_WOODEN_DOOR_CLOSE = get("block.wooden_door.close");
			BLOCK_WOODEN_DOOR_OPEN = get("block.wooden_door.open");
			BLOCK_WOODEN_TRAPDOOR_CLOSE = get("block.wooden_trapdoor.close");
			BLOCK_WOODEN_TRAPDOOR_OPEN = get("block.wooden_trapdoor.open");
			BLOCK_WOOD_BREAK = get("block.wood.break");
			BLOCK_WOODEN_BUTTON_CLICK_OFF = get("block.wooden_button.click_off");
			BLOCK_WOODEN_BUTTON_CLICK_ON = get("block.wooden_button.click_on");
			BLOCK_WOOD_FALL = get("block.wood.fall");
			BLOCK_WOOD_HIT = get("block.wood.hit");
			BLOCK_WOOD_PLACE = get("block.wood.place");
			BLOCK_WOODEN_PRESSURE_PLATE_CLICK_OFF = get("block.wooden_pressure_plate.click_off");
			BLOCK_WOODEN_PRESSURE_PLATE_CLICK_ON = get("block.wooden_pressure_plate.click_on");
			BLOCK_WOOD_STEP = get("block.wood.step");
			ENTITY_ZOMBIE_AMBIENT = get("entity.zombie.ambient");
			ENTITY_ZOMBIE_ATTACK_WOODEN_DOOR = get("entity.zombie.attack_wooden_door");
			ENTITY_ZOMBIE_ATTACK_IRON_DOOR = get("entity.zombie.attack_iron_door");
			ENTITY_ZOMBIE_BREAK_WOODEN_DOOR = get("entity.zombie.break_wooden_door");
			ENTITY_ZOMBIE_CONVERTED_TO_DROWNED = get("entity.zombie.converted_to_drowned");
			ENTITY_ZOMBIE_DEATH = get("entity.zombie.death");
			ENTITY_ZOMBIE_DESTROY_EGG = get("entity.zombie.destroy_egg");
			ENTITY_ZOMBIE_HORSE_AMBIENT = get("entity.zombie_horse.ambient");
			ENTITY_ZOMBIE_HORSE_DEATH = get("entity.zombie_horse.death");
			ENTITY_ZOMBIE_HORSE_HURT = get("entity.zombie_horse.hurt");
			ENTITY_ZOMBIE_HURT = get("entity.zombie.hurt");
			ENTITY_ZOMBIE_INFECT = get("entity.zombie.infect");
			ENTITY_ZOMBIE_PIGMAN_AMBIENT = get("entity.zombie_pigman.ambient");
			ENTITY_ZOMBIE_PIGMAN_ANGRY = get("entity.zombie_pigman.angry");
			ENTITY_ZOMBIE_PIGMAN_DEATH = get("entity.zombie_pigman.death");
			ENTITY_ZOMBIE_PIGMAN_HURT = get("entity.zombie_pigman.hurt");
			ENTITY_ZOMBIE_STEP = get("entity.zombie.step");
			ENTITY_ZOMBIE_VILLAGER_AMBIENT = get("entity.zombie_villager.ambient");
			ENTITY_ZOMBIE_VILLAGER_CONVERTED = get("entity.zombie_villager.converted");
			ENTITY_ZOMBIE_VILLAGER_CURE = get("entity.zombie_villager.cure");
			ENTITY_ZOMBIE_VILLAGER_DEATH = get("entity.zombie_villager.death");
			ENTITY_ZOMBIE_VILLAGER_HURT = get("entity.zombie_villager.hurt");
			ENTITY_ZOMBIE_VILLAGER_STEP = get("entity.zombie_villager.step");
		}
	}
}
