package net.minecraft.world.biome;

import net.minecraft.Bootstrap;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public abstract class Biomes {
	public static final Biome OCEAN;
	public static final Biome DEFAULT;
	public static final Biome PLAINS;
	public static final Biome DESERT;
	public static final Biome EXTREME_HILLS;
	public static final Biome FOREST;
	public static final Biome TAIGA;
	public static final Biome SWAMP;
	public static final Biome RIVER;
	public static final Biome NETHER;
	public static final Biome SKY;
	public static final Biome FROZEN_OCEAN;
	public static final Biome FROZEN_RIVER;
	public static final Biome ICE_FLATS;
	public static final Biome ICE_MOUNTAINS;
	public static final Biome MUSHROOM_ISLAND;
	public static final Biome MUSHROOM_ISLAND_SHORE;
	public static final Biome BEACH;
	public static final Biome DESERT_HILLS;
	public static final Biome FOREST_HILLS;
	public static final Biome TAIGA_HILLS;
	public static final Biome ExTREME_HILLS_SMALLER;
	public static final Biome JUNGLE;
	public static final Biome JUNGLE_HILLS;
	public static final Biome JUNGLE_EDGE;
	public static final Biome DEEP_OCEAN;
	public static final Biome STONE_BEACH;
	public static final Biome COLD_BEACH;
	public static final Biome BIRCH_FOREST;
	public static final Biome BIRCH_FOREST_HILLS;
	public static final Biome ROOFED_FOREST;
	public static final Biome TAIGA_COLD;
	public static final Biome TAIGA_COLD_HILLS;
	public static final Biome GIANT_TREE_TAIGA;
	public static final Biome GIANT_TREE_TAIGA_HILLS;
	public static final Biome EXTREME_HILLS_WITH_TREES;
	public static final Biome SAVANNA;
	public static final Biome SAVANNA_PLATEAU;
	public static final Biome MESA;
	public static final Biome WOODED_BADLANDS_PLATEAU;
	public static final Biome BADLANDS_PLATEAU;
	public static final Biome SMALL_END_ISLANDS;
	public static final Biome END_MIDLANDS;
	public static final Biome END_HIGHLANDS;
	public static final Biome END_BARRENS;
	public static final Biome WARM_OCEAN;
	public static final Biome LUKEWARM_OCEAN;
	public static final Biome COLD_OCEAN;
	public static final Biome DEEP_WARM_OCEAN;
	public static final Biome DEEP_LUKEWARM_OCEAN;
	public static final Biome DEEP_COLD_OCEAN;
	public static final Biome DEEP_FROZEN_OCEAN;
	public static final Biome VOID;
	public static final Biome PLAINS_M;
	public static final Biome DESERT_M;
	public static final Biome EXTREME_HILLS_M;
	public static final Biome FOREST_M;
	public static final Biome TAIGA_M;
	public static final Biome SWAMP_M;
	public static final Biome ICE_FLATS_M;
	public static final Biome JUNGLE_M;
	public static final Biome JUNGLE_EDGE_M;
	public static final Biome BIRCH_FOREST_M;
	public static final Biome BIRCH_FOREST_HILLS_M;
	public static final Biome ROOFED_FOREST_M;
	public static final Biome TAIGA_COLD_M;
	public static final Biome GIANT_SPRUCE_TAIGA;
	public static final Biome GIANT_SPRUCE_TAIGA_HILLS;
	public static final Biome EXTREME_HILLS_WITH_TREES_M;
	public static final Biome SAVANNA_M;
	public static final Biome SHATTERED_SAVANNA_PLATEAU;
	public static final Biome MESA_M;
	public static final Biome MODIFIED_WOODED_BADLANDS_PLATEAU;
	public static final Biome MODIFIED_BADLANDS_PLATEAU;

	private static Biome getBiome(String biomeName) {
		Biome biome = Registry.BIOME.getByIdentifier(new Identifier(biomeName));
		if (biome == null) {
			throw new IllegalStateException("Invalid Biome requested: " + biomeName);
		} else {
			return biome;
		}
	}

	static {
		if (!Bootstrap.isInitialized()) {
			throw new RuntimeException("Accessed Biomes before Bootstrap!");
		} else {
			OCEAN = getBiome("ocean");
			DEFAULT = OCEAN;
			PLAINS = getBiome("plains");
			DESERT = getBiome("desert");
			EXTREME_HILLS = getBiome("mountains");
			FOREST = getBiome("forest");
			TAIGA = getBiome("taiga");
			SWAMP = getBiome("swamp");
			RIVER = getBiome("river");
			NETHER = getBiome("nether");
			SKY = getBiome("the_end");
			FROZEN_OCEAN = getBiome("frozen_ocean");
			FROZEN_RIVER = getBiome("frozen_river");
			ICE_FLATS = getBiome("snowy_tundra");
			ICE_MOUNTAINS = getBiome("snowy_mountains");
			MUSHROOM_ISLAND = getBiome("mushroom_fields");
			MUSHROOM_ISLAND_SHORE = getBiome("mushroom_field_shore");
			BEACH = getBiome("beach");
			DESERT_HILLS = getBiome("desert_hills");
			FOREST_HILLS = getBiome("wooded_hills");
			TAIGA_HILLS = getBiome("taiga_hills");
			ExTREME_HILLS_SMALLER = getBiome("mountain_edge");
			JUNGLE = getBiome("jungle");
			JUNGLE_HILLS = getBiome("jungle_hills");
			JUNGLE_EDGE = getBiome("jungle_edge");
			DEEP_OCEAN = getBiome("deep_ocean");
			STONE_BEACH = getBiome("stone_shore");
			COLD_BEACH = getBiome("snowy_beach");
			BIRCH_FOREST = getBiome("birch_forest");
			BIRCH_FOREST_HILLS = getBiome("birch_forest_hills");
			ROOFED_FOREST = getBiome("dark_forest");
			TAIGA_COLD = getBiome("snowy_taiga");
			TAIGA_COLD_HILLS = getBiome("snowy_taiga_hills");
			GIANT_TREE_TAIGA = getBiome("giant_tree_taiga");
			GIANT_TREE_TAIGA_HILLS = getBiome("giant_tree_taiga_hills");
			EXTREME_HILLS_WITH_TREES = getBiome("wooded_mountains");
			SAVANNA = getBiome("savanna");
			SAVANNA_PLATEAU = getBiome("savanna_plateau");
			MESA = getBiome("badlands");
			WOODED_BADLANDS_PLATEAU = getBiome("wooded_badlands_plateau");
			BADLANDS_PLATEAU = getBiome("badlands_plateau");
			SMALL_END_ISLANDS = getBiome("small_end_islands");
			END_MIDLANDS = getBiome("end_midlands");
			END_HIGHLANDS = getBiome("end_highlands");
			END_BARRENS = getBiome("end_barrens");
			WARM_OCEAN = getBiome("warm_ocean");
			LUKEWARM_OCEAN = getBiome("lukewarm_ocean");
			COLD_OCEAN = getBiome("cold_ocean");
			DEEP_WARM_OCEAN = getBiome("deep_warm_ocean");
			DEEP_LUKEWARM_OCEAN = getBiome("deep_lukewarm_ocean");
			DEEP_COLD_OCEAN = getBiome("deep_cold_ocean");
			DEEP_FROZEN_OCEAN = getBiome("deep_frozen_ocean");
			VOID = getBiome("the_void");
			PLAINS_M = getBiome("sunflower_plains");
			DESERT_M = getBiome("desert_lakes");
			EXTREME_HILLS_M = getBiome("gravelly_mountains");
			FOREST_M = getBiome("flower_forest");
			TAIGA_M = getBiome("taiga_mountains");
			SWAMP_M = getBiome("swamp_hills");
			ICE_FLATS_M = getBiome("ice_spikes");
			JUNGLE_M = getBiome("modified_jungle");
			JUNGLE_EDGE_M = getBiome("modified_jungle_edge");
			BIRCH_FOREST_M = getBiome("tall_birch_forest");
			BIRCH_FOREST_HILLS_M = getBiome("tall_birch_hills");
			ROOFED_FOREST_M = getBiome("dark_forest_hills");
			TAIGA_COLD_M = getBiome("snowy_taiga_mountains");
			GIANT_SPRUCE_TAIGA = getBiome("giant_spruce_taiga");
			GIANT_SPRUCE_TAIGA_HILLS = getBiome("giant_spruce_taiga_hills");
			EXTREME_HILLS_WITH_TREES_M = getBiome("modified_gravelly_mountains");
			SAVANNA_M = getBiome("shattered_savanna");
			SHATTERED_SAVANNA_PLATEAU = getBiome("shattered_savanna_plateau");
			MESA_M = getBiome("eroded_badlands");
			MODIFIED_WOODED_BADLANDS_PLATEAU = getBiome("modified_wooded_badlands_plateau");
			MODIFIED_BADLANDS_PLATEAU = getBiome("modified_badlands_plateau");
		}
	}
}
