package net.minecraft.item;

import net.minecraft.Bootstrap;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public class Items {
	public static final Item AIR;
	public static final Item IRON_SHOVEL;
	public static final Item IRON_PICKAXE;
	public static final Item IRON_AXE;
	public static final Item FLINT_AND_STEEL;
	public static final Item APPLE;
	public static final Item BOW;
	public static final Item ARROW;
	public static final Item SPECTRAL_ARROW;
	public static final Item TIPPED_ARROW;
	public static final Item COAL;
	public static final Item CHARCOAL;
	public static final Item DIAMOND;
	public static final Item IRON_INGOT;
	public static final Item GOLD_INGOT;
	public static final Item IRON_SWORD;
	public static final Item WOODEN_SWORD;
	public static final Item WOODEN_SHOVEL;
	public static final Item WOODEN_PICKAXE;
	public static final Item WOODEN_AXE;
	public static final Item STONE_SWORD;
	public static final Item STONE_SHOVEL;
	public static final Item STONE_PICKAXE;
	public static final Item STONE_AXE;
	public static final Item DIAMOND_SWORD;
	public static final Item DIAMOND_SHOVEL;
	public static final Item DIAMOND_PICKAXE;
	public static final Item DIAMOND_AXE;
	public static final Item STICK;
	public static final Item BOWL;
	public static final Item MUSHROOM_STEW;
	public static final Item GOLDEN_SWORD;
	public static final Item GOLDEN_SHOVEL;
	public static final Item GOLDEN_PICKAXE;
	public static final Item GOLDEN_AXE;
	public static final Item STRING;
	public static final Item FEATHER;
	public static final Item GUNPOWDER;
	public static final Item WOODEN_HOE;
	public static final Item STONE_HOE;
	public static final Item IRON_HOE;
	public static final Item DIAMOND_HOE;
	public static final Item GOLDEN_HOE;
	public static final Item WHEAT_SEEDS;
	public static final Item WHEAT;
	public static final Item BREAD;
	public static final Item LEATHER_HELMET;
	public static final Item LEATHER_CHESTPLATE;
	public static final Item LEATHER_LEGGINGS;
	public static final Item LEATHER_BOOTS;
	public static final Item CHAINMAIL_HELMET;
	public static final Item CHAINMAIL_CHESTPLATE;
	public static final Item CHAINMAIL_LEGGINGS;
	public static final Item CHAINMAIL_BOOTS;
	public static final Item IRON_HELMET;
	public static final Item IRON_CHESTPLATE;
	public static final Item IRON_LEGGINGS;
	public static final Item IRON_BOOTS;
	public static final Item DIAMOND_HELMET;
	public static final Item DIAMOND_CHESTPLATE;
	public static final Item DIAMOND_LEGGINGS;
	public static final Item DIAMOND_BOOTS;
	public static final Item GOLDEN_HELMET;
	public static final Item GOLDEN_CHESTPLATE;
	public static final Item GOLDEN_LEGGINGS;
	public static final Item GOLDEN_BOOTS;
	public static final Item TURTLE_HELMET;
	public static final Item FLINT;
	public static final Item RAW_PORKCHOP;
	public static final Item COOKED_PORKCHOP;
	public static final Item PAINTING;
	public static final Item GOLDEN_APPLE;
	public static final Item ENCHANTED_GOLDEN_APPLE;
	public static final Item SIGN;
	public static final Item BUCKET;
	public static final Item WATER_BUCKET;
	public static final Item LAVA_BUCKET;
	public static final Item MINECART;
	public static final Item SADDLE;
	public static final Item REDSTONE;
	public static final Item SNOWBALL;
	public static final Item BOAT;
	public static final Item SPRUCE_BOAT;
	public static final Item BIRCH_BOAT;
	public static final Item JUNGLE_BOAT;
	public static final Item ACACIA_BOAT;
	public static final Item DARK_OAK_BOAT;
	public static final Item LEATHER;
	public static final Item MILK_BUCKET;
	public static final Item PUFFERFISH_BUCKET;
	public static final Item SALMON_BUCKET;
	public static final Item COD_BUCKET;
	public static final Item TROPICAL_FISH_BUCKET;
	public static final Item BRICK;
	public static final Item CLAY_BALL;
	public static final Item PAPER;
	public static final Item BOOK;
	public static final Item SLIME_BALL;
	public static final Item MINECART_WITH_CHEST;
	public static final Item MINECART_WITH_FURNACE;
	public static final Item EGG;
	public static final Item COMPASS;
	public static final Item FISHING_ROD;
	public static final Item CLOCK;
	public static final Item GLOWSTONE_DUST;
	public static final Item COD;
	public static final Item SALMON;
	public static final Item TROPICAL_FISH;
	public static final Item PUFFERFISH;
	public static final Item COOKED_COD;
	public static final Item COOKED_SALMON;
	public static final Item BONE_MEAL;
	public static final Item ORANGE_DYE;
	public static final Item MAGENTA_DYE;
	public static final Item LIGHT_BLUE_DYE;
	public static final Item DANDELION_YELLOW;
	public static final Item LIME_DYE;
	public static final Item PINK_DYE;
	public static final Item GRAY_DYE;
	public static final Item LIGHT_GRAY_DYE;
	public static final Item CYAN_DYE;
	public static final Item PURPLE_DYE;
	public static final Item LAPIS_LAZULI;
	public static final Item COCOA_BEANS;
	public static final Item CACTUS_GREEN;
	public static final Item ROSE_RED;
	public static final Item INK_SAC;
	public static final Item BONE;
	public static final Item SUGAR;
	public static final Item WHITE_BED;
	public static final Item ORANGE_BED;
	public static final Item MAGENTA_BED;
	public static final Item LIGHT_BLUE_BED;
	public static final Item YELLOW_BED;
	public static final Item LIME_BED;
	public static final Item PINK_BED;
	public static final Item GRAY_BED;
	public static final Item LIGHT_GRAY_BED;
	public static final Item CYAN_BED;
	public static final Item PURPLE_BED;
	public static final Item BLUE_BED;
	public static final Item BROWN_BED;
	public static final Item GREEN_BED;
	public static final Item RED_BED;
	public static final Item BLACK_BED;
	public static final Item COOKIE;
	public static final Item FILLED_MAP;
	public static final Item SHEARS;
	public static final Item MELON;
	public static final Item DRIED_KELP;
	public static final Item PUMPKIN_SEEDS;
	public static final Item MELON_SEEDS;
	public static final Item BEEF;
	public static final Item COOKED_BEEF;
	public static final Item CHICKEN;
	public static final Item COOKED_CHICKEN;
	public static final Item MUTTON;
	public static final Item COOKED_MUTTON;
	public static final Item RAW_RABBIT;
	public static final Item COOKED_RABBIT;
	public static final Item RABBIT_STEW;
	public static final Item RABBIT_FOOT;
	public static final Item RABBIT_HIDE;
	public static final Item ROTTEN_FLESH;
	public static final Item ENDER_PEARL;
	public static final Item BLAZE_ROD;
	public static final Item GHAST_TEAR;
	public static final Item GOLD_NUGGET;
	public static final Item NETHER_WART;
	public static final Item POTION;
	public static final Item SPLASH_POTION;
	public static final Item LINGERING_POTION;
	public static final Item GLASS_BOTTLE;
	public static final Item DRAGON_BREATH;
	public static final Item SPIDER_EYE;
	public static final Item FERMENTED_SPIDER_EYE;
	public static final Item BLAZE_POWDER;
	public static final Item MAGMA_CREAM;
	public static final Item EYE_OF_ENDER;
	public static final Item GLISTERING_MELON;
	public static final Item BAT_SPAWN_EGG;
	public static final Item BLAZE_SPAWN_EGG;
	public static final Item CAVE_SPIDER_SPAWN_EGG;
	public static final Item CHICKEN_SPAWN_EGG;
	public static final Item COD_SPAWN_EGG;
	public static final Item COW_SPAWN_EGG;
	public static final Item CREEPER_SPAWN_EGG;
	public static final Item DOLPHIN_SPAWN_EGG;
	public static final Item DONKEY_SPAWN_EGG;
	public static final Item ELDER_GUARDIAN_SPAWN_EGG;
	public static final Item ENDERMAN_SPAWN_EGG;
	public static final Item ENDERMITE_SPAWN_EGG;
	public static final Item EVOKER_SPAWN_EGG;
	public static final Item GHAST_SPAWN_EGG;
	public static final Item GUARDIAN_SPAWN_EGG;
	public static final Item HORSE_SPAWN_EGG;
	public static final Item HUSK_SPAWN_EGG;
	public static final Item LLAMA_SPAWN_EGG;
	public static final Item MAGMA_CUBE_SPAWN_EGG;
	public static final Item MOOSHROOM_SPAWN_EGG;
	public static final Item MULE_SPAWN_EGG;
	public static final Item OCELOT_SPAWN_EGG;
	public static final Item PARROT_SPAWN_EGG;
	public static final Item PIG_SPAWN_EGG;
	public static final Item PHANTOM_SPAWN_EGG;
	public static final Item POLAR_BEAR_SPAWN_EGG;
	public static final Item PUFFERFISH_SPAWN_EGG;
	public static final Item RABBIT_SPAWN_EGG;
	public static final Item SALMON_SPAWN_EGG;
	public static final Item SHEEP_SPAWN_EGG;
	public static final Item SHULKER_SPAWN_EGG;
	public static final Item SILVERFISH_SPAWN_EGG;
	public static final Item SKELETON_SPAWN_EGG;
	public static final Item SKELETON_HORSE_SPAWN_EGG;
	public static final Item SLIME_SPAWN_EGG;
	public static final Item SPIDER_SPAWN_EGG;
	public static final Item SQUID_SPAWN_EGG;
	public static final Item STRAY_SPAWN_EGG;
	public static final Item TROPICAL_FISH_SPAWN_EGG;
	public static final Item TURTLE_SPAWN_EGG;
	public static final Item VEX_SPAWN_EGG;
	public static final Item VILLAGER_SPAWN_EGG;
	public static final Item VINDICATOR_SPAWN_EGG;
	public static final Item WITCH_SPAWN_EGG;
	public static final Item WITHER_SKELETON_SPAWN_EGG;
	public static final Item WOLF_SPAWN_EGG;
	public static final Item ZOMBIE_SPAWN_EGG;
	public static final Item ZOMBIE_HORSE_SPAWN_EGG;
	public static final Item ZOMBIE_PIGMAN_SPAWN_EGG;
	public static final Item ZOMBIE_VILLAGER_SPAWN_EGG;
	public static final Item EXPERIENCE_BOTTLE;
	public static final Item FIRE_CHARGE;
	public static final Item WRITABLE_BOOK;
	public static final Item WRITTEN_BOOK;
	public static final Item EMERALD;
	public static final Item ITEM_FRAME;
	public static final Item CARROT;
	public static final Item POTATO;
	public static final Item BAKED_POTATO;
	public static final Item POISONOUS_POTATO;
	public static final Item MAP;
	public static final Item GOLDEN_CARROT;
	public static final Item SKELETON_SKULL;
	public static final Item WITHER_SKELETON_SKULL;
	public static final Item PLAYER_HEAD;
	public static final Item CREEPER_HEAD;
	public static final Item ZOMBIE_HEAD;
	public static final Item DRAGON_HEAD;
	public static final Item CARROT_ON_A_STICK;
	public static final Item NETHER_STAR;
	public static final Item PUMPKIN_PIE;
	public static final Item FIREWORK_ROCKET;
	public static final Item FIREWORK_STAR;
	public static final Item ENCHANTED_BOOK;
	public static final Item NETHER_BRICK;
	public static final Item QUARTZ;
	public static final Item MINECART_WITH_TNT;
	public static final Item MINECART_WITH_HOPPER;
	public static final Item ARMOR_STAND;
	public static final Item IRON_HORSE_ARMOR;
	public static final Item GOLDEN_HORSE_ARMOR;
	public static final Item DIAMOND_HORSE_ARMOR;
	public static final Item LEAD;
	public static final Item NAME_TAG;
	public static final Item MINECART_WITH_COMMAND_BLOCK;
	public static final Item MUSIC_DISC_13;
	public static final Item MUSIC_DISC_CAT;
	public static final Item MUSIC_DISC_BLOCKS;
	public static final Item MUSIC_DISC_CHIRP;
	public static final Item MUSIC_DISC_FAR;
	public static final Item MUSIC_DISC_MALL;
	public static final Item MUSIC_DISC_MELLOHI;
	public static final Item MUSIC_DISC_STAL;
	public static final Item MUSIC_DISC_STRAD;
	public static final Item MUSIC_DISC_WARD;
	public static final Item MUSIC_DISC_11;
	public static final Item MUSIC_DISC_WAIT;
	public static final Item PRISMARINE_SHARD;
	public static final Item PRISMARINE_CRYSTALS;
	public static final Item WHITE_BANNER;
	public static final Item ORANGE_BANNER;
	public static final Item MAGENTA_BANNER;
	public static final Item LIGHT_BLUE_BANNER;
	public static final Item YELLOW_BANNER;
	public static final Item LIME_BANNER;
	public static final Item PINK_BANNER;
	public static final Item GRAY_BANNER;
	public static final Item LIGHT_GRAY_BANNER;
	public static final Item CYAN_BANNER;
	public static final Item PURPLE_BANNER;
	public static final Item BLUE_BANNER;
	public static final Item BROWN_BANNER;
	public static final Item GREEN_BANNER;
	public static final Item RED_BANNER;
	public static final Item BLACK_BANNER;
	public static final Item END_CRYSTAL;
	public static final Item SHIELD;
	public static final Item ELYTRA;
	public static final Item CHORUS_FRUIT;
	public static final Item CHORUS_FRUIT_POPPED;
	public static final Item BEETROOT_SEED;
	public static final Item BEETROOT;
	public static final Item BEETROOT_SOUP;
	public static final Item TOTEM_OF_UNDYING;
	public static final Item SHULKER_SHELL;
	public static final Item IRON_NUGGET;
	public static final Item KNOWLEDGE_BOOK;
	public static final Item SCUTE;
	public static final Item DEBUG_STICK;
	public static final Item TRIDENT;
	public static final Item PHANTOM_MEMBRANE;
	public static final Item NAUTILUS_SHELL;
	public static final Item HEART_OF_THE_SEA;

	private static Item getById(String id) {
		Item item = Registry.ITEM.getByIdentifier(new Identifier(id));
		if (item == null) {
			throw new IllegalStateException("Invalid Item requested: " + id);
		} else {
			return item;
		}
	}

	static {
		if (!Bootstrap.isInitialized()) {
			throw new RuntimeException("Accessed Items before Bootstrap!");
		} else {
			AIR = getById("air");
			IRON_SHOVEL = getById("iron_shovel");
			IRON_PICKAXE = getById("iron_pickaxe");
			IRON_AXE = getById("iron_axe");
			FLINT_AND_STEEL = getById("flint_and_steel");
			APPLE = getById("apple");
			BOW = getById("bow");
			ARROW = getById("arrow");
			SPECTRAL_ARROW = getById("spectral_arrow");
			TIPPED_ARROW = getById("tipped_arrow");
			COAL = getById("coal");
			CHARCOAL = getById("charcoal");
			DIAMOND = getById("diamond");
			IRON_INGOT = getById("iron_ingot");
			GOLD_INGOT = getById("gold_ingot");
			IRON_SWORD = getById("iron_sword");
			WOODEN_SWORD = getById("wooden_sword");
			WOODEN_SHOVEL = getById("wooden_shovel");
			WOODEN_PICKAXE = getById("wooden_pickaxe");
			WOODEN_AXE = getById("wooden_axe");
			STONE_SWORD = getById("stone_sword");
			STONE_SHOVEL = getById("stone_shovel");
			STONE_PICKAXE = getById("stone_pickaxe");
			STONE_AXE = getById("stone_axe");
			DIAMOND_SWORD = getById("diamond_sword");
			DIAMOND_SHOVEL = getById("diamond_shovel");
			DIAMOND_PICKAXE = getById("diamond_pickaxe");
			DIAMOND_AXE = getById("diamond_axe");
			STICK = getById("stick");
			BOWL = getById("bowl");
			MUSHROOM_STEW = getById("mushroom_stew");
			GOLDEN_SWORD = getById("golden_sword");
			GOLDEN_SHOVEL = getById("golden_shovel");
			GOLDEN_PICKAXE = getById("golden_pickaxe");
			GOLDEN_AXE = getById("golden_axe");
			STRING = getById("string");
			FEATHER = getById("feather");
			GUNPOWDER = getById("gunpowder");
			WOODEN_HOE = getById("wooden_hoe");
			STONE_HOE = getById("stone_hoe");
			IRON_HOE = getById("iron_hoe");
			DIAMOND_HOE = getById("diamond_hoe");
			GOLDEN_HOE = getById("golden_hoe");
			WHEAT_SEEDS = getById("wheat_seeds");
			WHEAT = getById("wheat");
			BREAD = getById("bread");
			LEATHER_HELMET = getById("leather_helmet");
			LEATHER_CHESTPLATE = getById("leather_chestplate");
			LEATHER_LEGGINGS = getById("leather_leggings");
			LEATHER_BOOTS = getById("leather_boots");
			CHAINMAIL_HELMET = getById("chainmail_helmet");
			CHAINMAIL_CHESTPLATE = getById("chainmail_chestplate");
			CHAINMAIL_LEGGINGS = getById("chainmail_leggings");
			CHAINMAIL_BOOTS = getById("chainmail_boots");
			IRON_HELMET = getById("iron_helmet");
			IRON_CHESTPLATE = getById("iron_chestplate");
			IRON_LEGGINGS = getById("iron_leggings");
			IRON_BOOTS = getById("iron_boots");
			DIAMOND_HELMET = getById("diamond_helmet");
			DIAMOND_CHESTPLATE = getById("diamond_chestplate");
			DIAMOND_LEGGINGS = getById("diamond_leggings");
			DIAMOND_BOOTS = getById("diamond_boots");
			GOLDEN_HELMET = getById("golden_helmet");
			GOLDEN_CHESTPLATE = getById("golden_chestplate");
			GOLDEN_LEGGINGS = getById("golden_leggings");
			GOLDEN_BOOTS = getById("golden_boots");
			TURTLE_HELMET = getById("turtle_helmet");
			FLINT = getById("flint");
			RAW_PORKCHOP = getById("porkchop");
			COOKED_PORKCHOP = getById("cooked_porkchop");
			PAINTING = getById("painting");
			GOLDEN_APPLE = getById("golden_apple");
			ENCHANTED_GOLDEN_APPLE = getById("enchanted_golden_apple");
			SIGN = getById("sign");
			BUCKET = getById("bucket");
			WATER_BUCKET = getById("water_bucket");
			LAVA_BUCKET = getById("lava_bucket");
			MINECART = getById("minecart");
			SADDLE = getById("saddle");
			REDSTONE = getById("redstone");
			SNOWBALL = getById("snowball");
			BOAT = getById("oak_boat");
			SPRUCE_BOAT = getById("spruce_boat");
			BIRCH_BOAT = getById("birch_boat");
			JUNGLE_BOAT = getById("jungle_boat");
			ACACIA_BOAT = getById("acacia_boat");
			DARK_OAK_BOAT = getById("dark_oak_boat");
			LEATHER = getById("leather");
			MILK_BUCKET = getById("milk_bucket");
			PUFFERFISH_BUCKET = getById("pufferfish_bucket");
			SALMON_BUCKET = getById("salmon_bucket");
			COD_BUCKET = getById("cod_bucket");
			TROPICAL_FISH_BUCKET = getById("tropical_fish_bucket");
			BRICK = getById("brick");
			CLAY_BALL = getById("clay_ball");
			PAPER = getById("paper");
			BOOK = getById("book");
			SLIME_BALL = getById("slime_ball");
			MINECART_WITH_CHEST = getById("chest_minecart");
			MINECART_WITH_FURNACE = getById("furnace_minecart");
			EGG = getById("egg");
			COMPASS = getById("compass");
			FISHING_ROD = getById("fishing_rod");
			CLOCK = getById("clock");
			GLOWSTONE_DUST = getById("glowstone_dust");
			COD = getById("cod");
			SALMON = getById("salmon");
			TROPICAL_FISH = getById("tropical_fish");
			PUFFERFISH = getById("pufferfish");
			COOKED_COD = getById("cooked_cod");
			COOKED_SALMON = getById("cooked_salmon");
			BONE_MEAL = getById("bone_meal");
			ORANGE_DYE = getById("orange_dye");
			MAGENTA_DYE = getById("magenta_dye");
			LIGHT_BLUE_DYE = getById("light_blue_dye");
			DANDELION_YELLOW = getById("dandelion_yellow");
			LIME_DYE = getById("lime_dye");
			PINK_DYE = getById("pink_dye");
			GRAY_DYE = getById("gray_dye");
			LIGHT_GRAY_DYE = getById("light_gray_dye");
			CYAN_DYE = getById("cyan_dye");
			PURPLE_DYE = getById("purple_dye");
			LAPIS_LAZULI = getById("lapis_lazuli");
			COCOA_BEANS = getById("cocoa_beans");
			CACTUS_GREEN = getById("cactus_green");
			ROSE_RED = getById("rose_red");
			INK_SAC = getById("ink_sac");
			BONE = getById("bone");
			SUGAR = getById("sugar");
			WHITE_BED = getById("white_bed");
			ORANGE_BED = getById("orange_bed");
			MAGENTA_BED = getById("magenta_bed");
			LIGHT_BLUE_BED = getById("light_blue_bed");
			YELLOW_BED = getById("yellow_bed");
			LIME_BED = getById("lime_bed");
			PINK_BED = getById("pink_bed");
			GRAY_BED = getById("gray_bed");
			LIGHT_GRAY_BED = getById("light_gray_bed");
			CYAN_BED = getById("cyan_bed");
			PURPLE_BED = getById("purple_bed");
			BLUE_BED = getById("blue_bed");
			BROWN_BED = getById("brown_bed");
			GREEN_BED = getById("green_bed");
			RED_BED = getById("red_bed");
			BLACK_BED = getById("black_bed");
			COOKIE = getById("cookie");
			FILLED_MAP = getById("filled_map");
			SHEARS = getById("shears");
			MELON = getById("melon_slice");
			DRIED_KELP = getById("dried_kelp");
			PUMPKIN_SEEDS = getById("pumpkin_seeds");
			MELON_SEEDS = getById("melon_seeds");
			BEEF = getById("beef");
			COOKED_BEEF = getById("cooked_beef");
			CHICKEN = getById("chicken");
			COOKED_CHICKEN = getById("cooked_chicken");
			MUTTON = getById("mutton");
			COOKED_MUTTON = getById("cooked_mutton");
			RAW_RABBIT = getById("rabbit");
			COOKED_RABBIT = getById("cooked_rabbit");
			RABBIT_STEW = getById("rabbit_stew");
			RABBIT_FOOT = getById("rabbit_foot");
			RABBIT_HIDE = getById("rabbit_hide");
			ROTTEN_FLESH = getById("rotten_flesh");
			ENDER_PEARL = getById("ender_pearl");
			BLAZE_ROD = getById("blaze_rod");
			GHAST_TEAR = getById("ghast_tear");
			GOLD_NUGGET = getById("gold_nugget");
			NETHER_WART = getById("nether_wart");
			POTION = getById("potion");
			SPLASH_POTION = getById("splash_potion");
			LINGERING_POTION = getById("lingering_potion");
			GLASS_BOTTLE = getById("glass_bottle");
			DRAGON_BREATH = getById("dragon_breath");
			SPIDER_EYE = getById("spider_eye");
			FERMENTED_SPIDER_EYE = getById("fermented_spider_eye");
			BLAZE_POWDER = getById("blaze_powder");
			MAGMA_CREAM = getById("magma_cream");
			EYE_OF_ENDER = getById("ender_eye");
			GLISTERING_MELON = getById("glistering_melon_slice");
			BAT_SPAWN_EGG = getById("bat_spawn_egg");
			BLAZE_SPAWN_EGG = getById("blaze_spawn_egg");
			CAVE_SPIDER_SPAWN_EGG = getById("cave_spider_spawn_egg");
			CHICKEN_SPAWN_EGG = getById("chicken_spawn_egg");
			COD_SPAWN_EGG = getById("cod_spawn_egg");
			COW_SPAWN_EGG = getById("cow_spawn_egg");
			CREEPER_SPAWN_EGG = getById("creeper_spawn_egg");
			DOLPHIN_SPAWN_EGG = getById("dolphin_spawn_egg");
			DONKEY_SPAWN_EGG = getById("donkey_spawn_egg");
			ELDER_GUARDIAN_SPAWN_EGG = getById("elder_guardian_spawn_egg");
			ENDERMAN_SPAWN_EGG = getById("enderman_spawn_egg");
			ENDERMITE_SPAWN_EGG = getById("endermite_spawn_egg");
			EVOKER_SPAWN_EGG = getById("evoker_spawn_egg");
			GHAST_SPAWN_EGG = getById("ghast_spawn_egg");
			GUARDIAN_SPAWN_EGG = getById("guardian_spawn_egg");
			HORSE_SPAWN_EGG = getById("horse_spawn_egg");
			HUSK_SPAWN_EGG = getById("husk_spawn_egg");
			LLAMA_SPAWN_EGG = getById("llama_spawn_egg");
			MAGMA_CUBE_SPAWN_EGG = getById("magma_cube_spawn_egg");
			MOOSHROOM_SPAWN_EGG = getById("mooshroom_spawn_egg");
			MULE_SPAWN_EGG = getById("mule_spawn_egg");
			OCELOT_SPAWN_EGG = getById("ocelot_spawn_egg");
			PARROT_SPAWN_EGG = getById("parrot_spawn_egg");
			PIG_SPAWN_EGG = getById("pig_spawn_egg");
			PHANTOM_SPAWN_EGG = getById("phantom_spawn_egg");
			POLAR_BEAR_SPAWN_EGG = getById("polar_bear_spawn_egg");
			PUFFERFISH_SPAWN_EGG = getById("pufferfish_spawn_egg");
			RABBIT_SPAWN_EGG = getById("rabbit_spawn_egg");
			SALMON_SPAWN_EGG = getById("salmon_spawn_egg");
			SHEEP_SPAWN_EGG = getById("sheep_spawn_egg");
			SHULKER_SPAWN_EGG = getById("shulker_spawn_egg");
			SILVERFISH_SPAWN_EGG = getById("silverfish_spawn_egg");
			SKELETON_SPAWN_EGG = getById("skeleton_spawn_egg");
			SKELETON_HORSE_SPAWN_EGG = getById("skeleton_horse_spawn_egg");
			SLIME_SPAWN_EGG = getById("slime_spawn_egg");
			SPIDER_SPAWN_EGG = getById("spider_spawn_egg");
			SQUID_SPAWN_EGG = getById("squid_spawn_egg");
			STRAY_SPAWN_EGG = getById("stray_spawn_egg");
			TROPICAL_FISH_SPAWN_EGG = getById("tropical_fish_spawn_egg");
			TURTLE_SPAWN_EGG = getById("turtle_spawn_egg");
			VEX_SPAWN_EGG = getById("vex_spawn_egg");
			VILLAGER_SPAWN_EGG = getById("villager_spawn_egg");
			VINDICATOR_SPAWN_EGG = getById("vindicator_spawn_egg");
			WITCH_SPAWN_EGG = getById("witch_spawn_egg");
			WITHER_SKELETON_SPAWN_EGG = getById("wither_skeleton_spawn_egg");
			WOLF_SPAWN_EGG = getById("wolf_spawn_egg");
			ZOMBIE_SPAWN_EGG = getById("zombie_spawn_egg");
			ZOMBIE_HORSE_SPAWN_EGG = getById("zombie_horse_spawn_egg");
			ZOMBIE_PIGMAN_SPAWN_EGG = getById("zombie_pigman_spawn_egg");
			ZOMBIE_VILLAGER_SPAWN_EGG = getById("zombie_villager_spawn_egg");
			EXPERIENCE_BOTTLE = getById("experience_bottle");
			FIRE_CHARGE = getById("fire_charge");
			WRITABLE_BOOK = getById("writable_book");
			WRITTEN_BOOK = getById("written_book");
			EMERALD = getById("emerald");
			ITEM_FRAME = getById("item_frame");
			CARROT = getById("carrot");
			POTATO = getById("potato");
			BAKED_POTATO = getById("baked_potato");
			POISONOUS_POTATO = getById("poisonous_potato");
			MAP = getById("map");
			GOLDEN_CARROT = getById("golden_carrot");
			SKELETON_SKULL = getById("skeleton_skull");
			WITHER_SKELETON_SKULL = getById("wither_skeleton_skull");
			PLAYER_HEAD = getById("player_head");
			CREEPER_HEAD = getById("creeper_head");
			ZOMBIE_HEAD = getById("zombie_head");
			DRAGON_HEAD = getById("dragon_head");
			CARROT_ON_A_STICK = getById("carrot_on_a_stick");
			NETHER_STAR = getById("nether_star");
			PUMPKIN_PIE = getById("pumpkin_pie");
			FIREWORK_ROCKET = getById("firework_rocket");
			FIREWORK_STAR = getById("firework_star");
			ENCHANTED_BOOK = getById("enchanted_book");
			NETHER_BRICK = getById("nether_brick");
			QUARTZ = getById("quartz");
			MINECART_WITH_TNT = getById("tnt_minecart");
			MINECART_WITH_HOPPER = getById("hopper_minecart");
			ARMOR_STAND = getById("armor_stand");
			IRON_HORSE_ARMOR = getById("iron_horse_armor");
			GOLDEN_HORSE_ARMOR = getById("golden_horse_armor");
			DIAMOND_HORSE_ARMOR = getById("diamond_horse_armor");
			LEAD = getById("lead");
			NAME_TAG = getById("name_tag");
			MINECART_WITH_COMMAND_BLOCK = getById("command_block_minecart");
			MUSIC_DISC_13 = getById("music_disc_13");
			MUSIC_DISC_CAT = getById("music_disc_cat");
			MUSIC_DISC_BLOCKS = getById("music_disc_blocks");
			MUSIC_DISC_CHIRP = getById("music_disc_chirp");
			MUSIC_DISC_FAR = getById("music_disc_far");
			MUSIC_DISC_MALL = getById("music_disc_mall");
			MUSIC_DISC_MELLOHI = getById("music_disc_mellohi");
			MUSIC_DISC_STAL = getById("music_disc_stal");
			MUSIC_DISC_STRAD = getById("music_disc_strad");
			MUSIC_DISC_WARD = getById("music_disc_ward");
			MUSIC_DISC_11 = getById("music_disc_11");
			MUSIC_DISC_WAIT = getById("music_disc_wait");
			PRISMARINE_SHARD = getById("prismarine_shard");
			PRISMARINE_CRYSTALS = getById("prismarine_crystals");
			WHITE_BANNER = getById("white_banner");
			ORANGE_BANNER = getById("orange_banner");
			MAGENTA_BANNER = getById("magenta_banner");
			LIGHT_BLUE_BANNER = getById("light_blue_banner");
			YELLOW_BANNER = getById("yellow_banner");
			LIME_BANNER = getById("lime_banner");
			PINK_BANNER = getById("pink_banner");
			GRAY_BANNER = getById("gray_banner");
			LIGHT_GRAY_BANNER = getById("light_gray_banner");
			CYAN_BANNER = getById("cyan_banner");
			PURPLE_BANNER = getById("purple_banner");
			BLUE_BANNER = getById("blue_banner");
			BROWN_BANNER = getById("brown_banner");
			GREEN_BANNER = getById("green_banner");
			RED_BANNER = getById("red_banner");
			BLACK_BANNER = getById("black_banner");
			END_CRYSTAL = getById("end_crystal");
			SHIELD = getById("shield");
			ELYTRA = getById("elytra");
			CHORUS_FRUIT = getById("chorus_fruit");
			CHORUS_FRUIT_POPPED = getById("popped_chorus_fruit");
			BEETROOT_SEED = getById("beetroot_seeds");
			BEETROOT = getById("beetroot");
			BEETROOT_SOUP = getById("beetroot_soup");
			TOTEM_OF_UNDYING = getById("totem_of_undying");
			SHULKER_SHELL = getById("shulker_shell");
			IRON_NUGGET = getById("iron_nugget");
			KNOWLEDGE_BOOK = getById("knowledge_book");
			SCUTE = getById("scute");
			DEBUG_STICK = getById("debug_stick");
			TRIDENT = getById("trident");
			PHANTOM_MEMBRANE = getById("phantom_membrane");
			NAUTILUS_SHELL = getById("nautilus_shell");
			HEART_OF_THE_SEA = getById("heart_of_the_sea");
		}
	}
}
