package net.minecraft.item;

import net.minecraft.Bootstrap;
import net.minecraft.util.Identifier;

public class Items {
	public static final Item AIR;
	public static final Item IRON_SHOVEL;
	public static final Item IRON_PICKAXE;
	public static final Item IRON_AXE;
	public static final Item FLINT_AND_STEEL;
	public static final Item APPLE;
	public static final BowItem BOW;
	public static final Item ARROW;
	public static final Item SPECTRAL_ARROW;
	public static final Item TIPPED_ARROW;
	public static final Item COAL;
	public static final Item DIAMOND;
	public static final Item IRON_INGOT;
	public static final Item GOLD_INGOT;
	public static final Item IRON_SWORD;
	public static final Item WOODEN_SWORD;
	public static final Item WOODEN_SHOVEL;
	public static final Item WOODEN_PICKAXE;
	public static final Item WOODEN_AXE;
	public static final Item STONE_SWORD;
	public static final Item STONE_SHOVEL;
	public static final Item STONE_PICKAXE;
	public static final Item STONE_AXE;
	public static final Item DIAMOND_SWORD;
	public static final Item DIAMOND_SHOVEL;
	public static final Item DIAMOND_PICKAXE;
	public static final Item DIAMOND_AXE;
	public static final Item STICK;
	public static final Item BOWL;
	public static final Item MUSHROOM_STEW;
	public static final Item GOLDEN_SWORD;
	public static final Item GOLDEN_SHOVEL;
	public static final Item GOLDEN_PICKAXE;
	public static final Item GOLDEN_AXE;
	public static final Item STRING;
	public static final Item FEATHER;
	public static final Item GUNPOWDER;
	public static final Item WOODEN_HOE;
	public static final Item STONE_HOE;
	public static final Item IRON_HOE;
	public static final Item DIAMOND_HOE;
	public static final Item GOLDEN_HOE;
	public static final Item WHEAT_SEEDS;
	public static final Item WHEAT;
	public static final Item BREAD;
	public static final ArmorItem LEATHER_HELMET;
	public static final ArmorItem LEATHER_CHESTPLATE;
	public static final ArmorItem LEATHER_LEGGINGS;
	public static final ArmorItem LEATHER_BOOTS;
	public static final ArmorItem CHAINMAIL_HELMET;
	public static final ArmorItem CHAINMAIL_CHESTPLATE;
	public static final ArmorItem CHAINMAIL_LEGGINGS;
	public static final ArmorItem CHAINMAIL_BOOTS;
	public static final ArmorItem IRON_HELMET;
	public static final ArmorItem IRON_CHESTPLATE;
	public static final ArmorItem IRON_LEGGINGS;
	public static final ArmorItem IRON_BOOTS;
	public static final ArmorItem DIAMOND_HELMET;
	public static final ArmorItem DIAMOND_CHESTPLATE;
	public static final ArmorItem DIAMOND_LEGGINGS;
	public static final ArmorItem DIAMOND_BOOTS;
	public static final ArmorItem GOLDEN_HELMET;
	public static final ArmorItem GOLDEN_CHESTPLATE;
	public static final ArmorItem GOLDEN_LEGGINGS;
	public static final ArmorItem GOLDEN_BOOTS;
	public static final Item FLINT;
	public static final Item RAW_PORKCHOP;
	public static final Item COOKED_PORKCHOP;
	public static final Item PAINTING;
	public static final Item GOLDEN_APPLE;
	public static final Item SIGN;
	public static final Item OAK_DOOR;
	public static final Item SPRUCE_DOOR;
	public static final Item BIRCH_DOOR;
	public static final Item JUNGLE_DOOR;
	public static final Item ACACIA_DOOR;
	public static final Item DARK_OAK_DOOR;
	public static final Item BUCKET;
	public static final Item WATER_BUCKET;
	public static final Item LAVA_BUCKET;
	public static final Item MINECART;
	public static final Item SADDLE;
	public static final Item IRON_DOOR;
	public static final Item REDSTONE;
	public static final Item SNOWBALL;
	public static final Item BOAT;
	public static final Item SPRUCE_BOAT;
	public static final Item BIRCH_BOAT;
	public static final Item JUNGLE_BOAT;
	public static final Item ACACIA_BOAT;
	public static final Item DARK_OAK_BOAT;
	public static final Item LEATHER;
	public static final Item MILK_BUCKET;
	public static final Item BRICK;
	public static final Item CLAY_BALL;
	public static final Item SUGARCANE;
	public static final Item PAPER;
	public static final Item BOOK;
	public static final Item SLIME_BALL;
	public static final Item MINECART_WITH_CHEST;
	public static final Item MINECART_WITH_FURNACE;
	public static final Item EGG;
	public static final Item COMPASS;
	public static final FishingRodItem FISHING_ROD;
	public static final Item CLOCK;
	public static final Item GLOWSTONE_DUST;
	public static final Item RAW_FISH;
	public static final Item COOKED_FISH;
	public static final Item DYE;
	public static final Item BONE;
	public static final Item SUGAR;
	public static final Item CAKE;
	public static final Item BED;
	public static final Item REPEATER;
	public static final Item COOKIE;
	public static final FilledMapItem FILLED_MAP;
	public static final ShearsItem SHEARS;
	public static final Item MELON;
	public static final Item PUMPKIN_SEEDS;
	public static final Item MELON_SEEDS;
	public static final Item BEEF;
	public static final Item COOKED_BEEF;
	public static final Item CHICKEN;
	public static final Item COOKED_CHICKEN;
	public static final Item MUTTON;
	public static final Item COOKED_MUTTON;
	public static final Item RAW_RABBIT;
	public static final Item COOKED_RABBIT;
	public static final Item RABBIT_STEW;
	public static final Item RABBIT_FOOT;
	public static final Item RABBIT_HIDE;
	public static final Item ROTTEN_FLESH;
	public static final Item ENDER_PEARL;
	public static final Item BLAZE_ROD;
	public static final Item GHAST_TEAR;
	public static final Item GOLD_NUGGET;
	public static final Item NETHER_WART;
	public static final PotionItem POTION;
	public static final PotionItem SPLASH_POTION;
	public static final PotionItem LINGERING_POTION;
	public static final Item GLASS_BOTTLE;
	public static final Item DRAGON_BREATH;
	public static final Item SPIDER_EYE;
	public static final Item FERMENTED_SPIDER_EYE;
	public static final Item BLAZE_POWDER;
	public static final Item MAGMA_CREAM;
	public static final Item BREWING_STAND;
	public static final Item CAULDRON;
	public static final Item EYE_OF_ENDER;
	public static final Item GLISTERING_MELON;
	public static final Item SPAWN_EGG;
	public static final Item EXPERIENCE_BOTTLE;
	public static final Item FIRE_CHARGE;
	public static final Item WRITABLE_BOOK;
	public static final Item WRITTEN_BOOK;
	public static final Item EMERALD;
	public static final Item ITEM_FRAME;
	public static final Item FLOWER_POT;
	public static final Item CARROT;
	public static final Item POTATO;
	public static final Item BAKED_POTATO;
	public static final Item POISONOUS_POTATO;
	public static final EmptyMapItem MAP;
	public static final Item GOLDEN_CARROT;
	public static final Item SKULL;
	public static final Item CARROT_ON_A_STICK;
	public static final Item NETHER_STAR;
	public static final Item PUMPKIN_PIE;
	public static final Item FIREWORKS;
	public static final Item FIREWORK_CHARGE;
	public static final EnchantedBookItem ENCHANTED_BOOK;
	public static final Item COMPARATOR;
	public static final Item NETHERBRICK;
	public static final Item QUARTZ;
	public static final Item MINECART_WITH_TNT;
	public static final Item MINECART_WITH_HOPPER;
	public static final ArmorStandItem ARMOR_STAND;
	public static final Item IRON_HORSE_ARMOR;
	public static final Item GOLDEN_HORSE_ARMOR;
	public static final Item DIAMOND_HORSE_ARMOR;
	public static final Item LEAD;
	public static final Item NAME_TAG;
	public static final Item MINECART_WITH_COMMAND_BLOCK;
	public static final Item RECORD_13;
	public static final Item RECORD_CAT;
	public static final Item RECORD_BLOCKS;
	public static final Item RECORD_CHIRP;
	public static final Item RECORD_FAR;
	public static final Item RECORD_MALL;
	public static final Item RECORD_MELLOHI;
	public static final Item RECORD_STAL;
	public static final Item RECORD_STRAD;
	public static final Item RECORD_WARD;
	public static final Item RECORD_11;
	public static final Item RECORD_WAIT;
	public static final Item PRISMARINE_SHARD;
	public static final Item PRISMARINE_CRYSTALS;
	public static final Item BANNER;
	public static final Item END_CRYSTAL;
	public static final Item SHIELD;
	public static final Item ELYTRA;
	public static final Item CHORUS_FRUIT;
	public static final Item CHORUS_FRUIT_POPPED;
	public static final Item BEETROOT_SEED;
	public static final Item BEETROOT;
	public static final Item BEETROOT_SOUP;
	public static final Item TOTEM_OF_UNDYING;
	public static final Item SHULKER_SHELL;
	public static final Item IRON_NUGGET;

	private static Item getById(String id) {
		Item item = Item.REGISTRY.get(new Identifier(id));
		if (item == null) {
			throw new IllegalStateException("Invalid Item requested: " + id);
		} else {
			return item;
		}
	}

	static {
		if (!Bootstrap.isInitialized()) {
			throw new RuntimeException("Accessed Items before Bootstrap!");
		} else {
			AIR = getById("air");
			IRON_SHOVEL = getById("iron_shovel");
			IRON_PICKAXE = getById("iron_pickaxe");
			IRON_AXE = getById("iron_axe");
			FLINT_AND_STEEL = getById("flint_and_steel");
			APPLE = getById("apple");
			BOW = (BowItem)getById("bow");
			ARROW = getById("arrow");
			SPECTRAL_ARROW = getById("spectral_arrow");
			TIPPED_ARROW = getById("tipped_arrow");
			COAL = getById("coal");
			DIAMOND = getById("diamond");
			IRON_INGOT = getById("iron_ingot");
			GOLD_INGOT = getById("gold_ingot");
			IRON_SWORD = getById("iron_sword");
			WOODEN_SWORD = getById("wooden_sword");
			WOODEN_SHOVEL = getById("wooden_shovel");
			WOODEN_PICKAXE = getById("wooden_pickaxe");
			WOODEN_AXE = getById("wooden_axe");
			STONE_SWORD = getById("stone_sword");
			STONE_SHOVEL = getById("stone_shovel");
			STONE_PICKAXE = getById("stone_pickaxe");
			STONE_AXE = getById("stone_axe");
			DIAMOND_SWORD = getById("diamond_sword");
			DIAMOND_SHOVEL = getById("diamond_shovel");
			DIAMOND_PICKAXE = getById("diamond_pickaxe");
			DIAMOND_AXE = getById("diamond_axe");
			STICK = getById("stick");
			BOWL = getById("bowl");
			MUSHROOM_STEW = getById("mushroom_stew");
			GOLDEN_SWORD = getById("golden_sword");
			GOLDEN_SHOVEL = getById("golden_shovel");
			GOLDEN_PICKAXE = getById("golden_pickaxe");
			GOLDEN_AXE = getById("golden_axe");
			STRING = getById("string");
			FEATHER = getById("feather");
			GUNPOWDER = getById("gunpowder");
			WOODEN_HOE = getById("wooden_hoe");
			STONE_HOE = getById("stone_hoe");
			IRON_HOE = getById("iron_hoe");
			DIAMOND_HOE = getById("diamond_hoe");
			GOLDEN_HOE = getById("golden_hoe");
			WHEAT_SEEDS = getById("wheat_seeds");
			WHEAT = getById("wheat");
			BREAD = getById("bread");
			LEATHER_HELMET = (ArmorItem)getById("leather_helmet");
			LEATHER_CHESTPLATE = (ArmorItem)getById("leather_chestplate");
			LEATHER_LEGGINGS = (ArmorItem)getById("leather_leggings");
			LEATHER_BOOTS = (ArmorItem)getById("leather_boots");
			CHAINMAIL_HELMET = (ArmorItem)getById("chainmail_helmet");
			CHAINMAIL_CHESTPLATE = (ArmorItem)getById("chainmail_chestplate");
			CHAINMAIL_LEGGINGS = (ArmorItem)getById("chainmail_leggings");
			CHAINMAIL_BOOTS = (ArmorItem)getById("chainmail_boots");
			IRON_HELMET = (ArmorItem)getById("iron_helmet");
			IRON_CHESTPLATE = (ArmorItem)getById("iron_chestplate");
			IRON_LEGGINGS = (ArmorItem)getById("iron_leggings");
			IRON_BOOTS = (ArmorItem)getById("iron_boots");
			DIAMOND_HELMET = (ArmorItem)getById("diamond_helmet");
			DIAMOND_CHESTPLATE = (ArmorItem)getById("diamond_chestplate");
			DIAMOND_LEGGINGS = (ArmorItem)getById("diamond_leggings");
			DIAMOND_BOOTS = (ArmorItem)getById("diamond_boots");
			GOLDEN_HELMET = (ArmorItem)getById("golden_helmet");
			GOLDEN_CHESTPLATE = (ArmorItem)getById("golden_chestplate");
			GOLDEN_LEGGINGS = (ArmorItem)getById("golden_leggings");
			GOLDEN_BOOTS = (ArmorItem)getById("golden_boots");
			FLINT = getById("flint");
			RAW_PORKCHOP = getById("porkchop");
			COOKED_PORKCHOP = getById("cooked_porkchop");
			PAINTING = getById("painting");
			GOLDEN_APPLE = getById("golden_apple");
			SIGN = getById("sign");
			OAK_DOOR = getById("wooden_door");
			SPRUCE_DOOR = getById("spruce_door");
			BIRCH_DOOR = getById("birch_door");
			JUNGLE_DOOR = getById("jungle_door");
			ACACIA_DOOR = getById("acacia_door");
			DARK_OAK_DOOR = getById("dark_oak_door");
			BUCKET = getById("bucket");
			WATER_BUCKET = getById("water_bucket");
			LAVA_BUCKET = getById("lava_bucket");
			MINECART = getById("minecart");
			SADDLE = getById("saddle");
			IRON_DOOR = getById("iron_door");
			REDSTONE = getById("redstone");
			SNOWBALL = getById("snowball");
			BOAT = getById("boat");
			SPRUCE_BOAT = getById("spruce_boat");
			BIRCH_BOAT = getById("birch_boat");
			JUNGLE_BOAT = getById("jungle_boat");
			ACACIA_BOAT = getById("acacia_boat");
			DARK_OAK_BOAT = getById("dark_oak_boat");
			LEATHER = getById("leather");
			MILK_BUCKET = getById("milk_bucket");
			BRICK = getById("brick");
			CLAY_BALL = getById("clay_ball");
			SUGARCANE = getById("reeds");
			PAPER = getById("paper");
			BOOK = getById("book");
			SLIME_BALL = getById("slime_ball");
			MINECART_WITH_CHEST = getById("chest_minecart");
			MINECART_WITH_FURNACE = getById("furnace_minecart");
			EGG = getById("egg");
			COMPASS = getById("compass");
			FISHING_ROD = (FishingRodItem)getById("fishing_rod");
			CLOCK = getById("clock");
			GLOWSTONE_DUST = getById("glowstone_dust");
			RAW_FISH = getById("fish");
			COOKED_FISH = getById("cooked_fish");
			DYE = getById("dye");
			BONE = getById("bone");
			SUGAR = getById("sugar");
			CAKE = getById("cake");
			BED = getById("bed");
			REPEATER = getById("repeater");
			COOKIE = getById("cookie");
			FILLED_MAP = (FilledMapItem)getById("filled_map");
			SHEARS = (ShearsItem)getById("shears");
			MELON = getById("melon");
			PUMPKIN_SEEDS = getById("pumpkin_seeds");
			MELON_SEEDS = getById("melon_seeds");
			BEEF = getById("beef");
			COOKED_BEEF = getById("cooked_beef");
			CHICKEN = getById("chicken");
			COOKED_CHICKEN = getById("cooked_chicken");
			MUTTON = getById("mutton");
			COOKED_MUTTON = getById("cooked_mutton");
			RAW_RABBIT = getById("rabbit");
			COOKED_RABBIT = getById("cooked_rabbit");
			RABBIT_STEW = getById("rabbit_stew");
			RABBIT_FOOT = getById("rabbit_foot");
			RABBIT_HIDE = getById("rabbit_hide");
			ROTTEN_FLESH = getById("rotten_flesh");
			ENDER_PEARL = getById("ender_pearl");
			BLAZE_ROD = getById("blaze_rod");
			GHAST_TEAR = getById("ghast_tear");
			GOLD_NUGGET = getById("gold_nugget");
			NETHER_WART = getById("nether_wart");
			POTION = (PotionItem)getById("potion");
			SPLASH_POTION = (PotionItem)getById("splash_potion");
			LINGERING_POTION = (PotionItem)getById("lingering_potion");
			GLASS_BOTTLE = getById("glass_bottle");
			DRAGON_BREATH = getById("dragon_breath");
			SPIDER_EYE = getById("spider_eye");
			FERMENTED_SPIDER_EYE = getById("fermented_spider_eye");
			BLAZE_POWDER = getById("blaze_powder");
			MAGMA_CREAM = getById("magma_cream");
			BREWING_STAND = getById("brewing_stand");
			CAULDRON = getById("cauldron");
			EYE_OF_ENDER = getById("ender_eye");
			GLISTERING_MELON = getById("speckled_melon");
			SPAWN_EGG = getById("spawn_egg");
			EXPERIENCE_BOTTLE = getById("experience_bottle");
			FIRE_CHARGE = getById("fire_charge");
			WRITABLE_BOOK = getById("writable_book");
			WRITTEN_BOOK = getById("written_book");
			EMERALD = getById("emerald");
			ITEM_FRAME = getById("item_frame");
			FLOWER_POT = getById("flower_pot");
			CARROT = getById("carrot");
			POTATO = getById("potato");
			BAKED_POTATO = getById("baked_potato");
			POISONOUS_POTATO = getById("poisonous_potato");
			MAP = (EmptyMapItem)getById("map");
			GOLDEN_CARROT = getById("golden_carrot");
			SKULL = getById("skull");
			CARROT_ON_A_STICK = getById("carrot_on_a_stick");
			NETHER_STAR = getById("nether_star");
			PUMPKIN_PIE = getById("pumpkin_pie");
			FIREWORKS = getById("fireworks");
			FIREWORK_CHARGE = getById("firework_charge");
			ENCHANTED_BOOK = (EnchantedBookItem)getById("enchanted_book");
			COMPARATOR = getById("comparator");
			NETHERBRICK = getById("netherbrick");
			QUARTZ = getById("quartz");
			MINECART_WITH_TNT = getById("tnt_minecart");
			MINECART_WITH_HOPPER = getById("hopper_minecart");
			ARMOR_STAND = (ArmorStandItem)getById("armor_stand");
			IRON_HORSE_ARMOR = getById("iron_horse_armor");
			GOLDEN_HORSE_ARMOR = getById("golden_horse_armor");
			DIAMOND_HORSE_ARMOR = getById("diamond_horse_armor");
			LEAD = getById("lead");
			NAME_TAG = getById("name_tag");
			MINECART_WITH_COMMAND_BLOCK = getById("command_block_minecart");
			RECORD_13 = getById("record_13");
			RECORD_CAT = getById("record_cat");
			RECORD_BLOCKS = getById("record_blocks");
			RECORD_CHIRP = getById("record_chirp");
			RECORD_FAR = getById("record_far");
			RECORD_MALL = getById("record_mall");
			RECORD_MELLOHI = getById("record_mellohi");
			RECORD_STAL = getById("record_stal");
			RECORD_STRAD = getById("record_strad");
			RECORD_WARD = getById("record_ward");
			RECORD_11 = getById("record_11");
			RECORD_WAIT = getById("record_wait");
			PRISMARINE_SHARD = getById("prismarine_shard");
			PRISMARINE_CRYSTALS = getById("prismarine_crystals");
			BANNER = getById("banner");
			END_CRYSTAL = getById("end_crystal");
			SHIELD = getById("shield");
			ELYTRA = getById("elytra");
			CHORUS_FRUIT = getById("chorus_fruit");
			CHORUS_FRUIT_POPPED = getById("chorus_fruit_popped");
			BEETROOT_SEED = getById("beetroot_seeds");
			BEETROOT = getById("beetroot");
			BEETROOT_SOUP = getById("beetroot_soup");
			TOTEM_OF_UNDYING = getById("totem_of_undying");
			SHULKER_SHELL = getById("shulker_shell");
			IRON_NUGGET = getById("iron_nugget");
		}
	}
}
