package net.minecraft.block;

import com.google.common.collect.Sets;
import java.util.Set;
import net.minecraft.Bootstrap;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public class Blocks {
	private static final Set<Block> field_12591;
	public static final Block AIR;
	public static final Block STONE;
	public static final Block GRANITE;
	public static final Block POLISHED_GRANITE;
	public static final Block DIORITE;
	public static final Block POLISHED_DIORITE;
	public static final Block ANDESITE;
	public static final Block POLISHED_ANDESITE;
	public static final Block GRASS_BLOCK;
	public static final Block DIRT;
	public static final Block COARSE_DIRT;
	public static final Block PODZOL;
	public static final Block COBBLESTONE;
	public static final Block OAK_PLANKS;
	public static final Block SPRUCE_PLANKS;
	public static final Block BIRCH_PLANKS;
	public static final Block JUNGLE_PLANKS;
	public static final Block ACACIA_PLANKS;
	public static final Block DARK_OAK_PLANKS;
	public static final Block OAK_SAPLING;
	public static final Block SPRUCE_SAPLING;
	public static final Block BIRCH_SAPLING;
	public static final Block JUNGLE_SAPLING;
	public static final Block ACACIA_SAPLING;
	public static final Block DARK_OAK_SAPLING;
	public static final Block BEDROCK;
	public static final Block WATER;
	public static final Block BUBBLE_COLUMN;
	public static final Block LAVA;
	public static final Block SAND;
	public static final Block RED_SAND;
	public static final Block GRAVEL;
	public static final Block GOLD_ORE;
	public static final Block IRON_ORE;
	public static final Block COAL_ORE;
	public static final Block OAK_LOG;
	public static final Block SPRUCE_LOG;
	public static final Block BIRCH_LOG;
	public static final Block JUNGLE_LOG;
	public static final Block ACACIA_LOG;
	public static final Block DARK_OAK_LOG;
	public static final Block STRIPPED_OAK_LOG;
	public static final Block STRIPPED_SPRUCE_LOG;
	public static final Block STRIPPED_BIRCH_LOG;
	public static final Block STRIPPED_JUNGLE_LOG;
	public static final Block STRIPPED_ACACIA_LOG;
	public static final Block STRIPPED_DARK_OAK_LOG;
	public static final Block OAK_WOOD;
	public static final Block SPRUCE_WOOD;
	public static final Block BIRCH_WOOD;
	public static final Block JUNGLE_WOOD;
	public static final Block ACACIA_WOOD;
	public static final Block DARK_OAK_WOOD;
	public static final Block STRIPPED_OAK_WOOD;
	public static final Block STRIPPED_SPRUCE_WOOD;
	public static final Block STRIPPED_BIRCH_WOOD;
	public static final Block STRIPPED_JUNGLE_WOOD;
	public static final Block STRIPPED_ACACIA_WOOD;
	public static final Block STRIPPED_DARK_OAK_WOOD;
	public static final Block OAK_LEAVES;
	public static final Block SPRUCE_LEAVES;
	public static final Block BIRCH_LEAVES;
	public static final Block JUNGLE_LEAVES;
	public static final Block ACACIA_LEAVES;
	public static final Block DARK_OAK_LEAVES;
	public static final Block SPONGE;
	public static final Block WET_SPONGE;
	public static final Block GLASS;
	public static final Block LAPIS_LAZULI_ORE;
	public static final Block LAPIS_LAZULI_BLOCK;
	public static final Block DISPENSER;
	public static final Block SANDSTONE;
	public static final Block CHISELED_SANDSTONE;
	public static final Block CUT_SANDSTONE;
	public static final Block NOTE_BLOCK;
	public static final Block WHITE_BED;
	public static final Block ORANGE_BED;
	public static final Block MAGENTA_BED;
	public static final Block LIGHT_BLUE_BED;
	public static final Block YELLOW_BED;
	public static final Block LIME_BED;
	public static final Block PINK_BED;
	public static final Block GRAY_BED;
	public static final Block LIGHT_GRAY_BED;
	public static final Block CYAN_BED;
	public static final Block PURPLE_BED;
	public static final Block BLUE_BED;
	public static final Block BROWN_BED;
	public static final Block GREEN_BED;
	public static final Block RED_BED;
	public static final Block BLACK_BED;
	public static final Block POWERED_RAIL;
	public static final Block DETECTOR_RAIL;
	public static final Block STICKY_PISTON;
	public static final Block COBWEB;
	public static final Block GRASS;
	public static final Block FERN;
	public static final Block DEAD_BUSH;
	public static final Block SEAGRASS;
	public static final Block TALL_SEAGRASS;
	public static final Block PISTON;
	public static final Block PISTON_HEAD;
	public static final Block WHITE_WOOL;
	public static final Block ORANGE_WOOL;
	public static final Block MAGENTA_WOOL;
	public static final Block LIGHT_BLUE_WOOL;
	public static final Block YELLOW_WOOL;
	public static final Block LIME_WOOL;
	public static final Block PINK_WOOL;
	public static final Block GRAY_WOOL;
	public static final Block LIGHT_GRAY_WOOL;
	public static final Block CYAN_WOOL;
	public static final Block PURPLE_WOOL;
	public static final Block BLUE_WOOL;
	public static final Block BROWN_WOOL;
	public static final Block GREEN_WOOL;
	public static final Block RED_WOOL;
	public static final Block BLACK_WOOL;
	public static final Block MOVING_PISTON;
	public static final Block DANDELION;
	public static final Block POPPY;
	public static final Block BLUE_ORCHID;
	public static final Block ALLIUM;
	public static final Block AZURE_BLUET;
	public static final Block RED_TULIP;
	public static final Block ORANGE_TULIP;
	public static final Block WHITE_TULIP;
	public static final Block PINK_TULIP;
	public static final Block OXEYE_DAISY;
	public static final Block BROWN_MUSHROOM;
	public static final Block RED_MUSHROOM;
	public static final Block GOLD_BLOCK;
	public static final Block IRON_BLOCK;
	public static final Block OAK_SLAB;
	public static final Block SPRUCE_SLAB;
	public static final Block BIRCH_SLAB;
	public static final Block JUNGLE_SLAB;
	public static final Block ACACIA_SLAB;
	public static final Block DARK_OAK_SLAB;
	public static final Block STONE_SLAB;
	public static final Block SANDSTONE_SLAB;
	public static final Block PETRIFIED_OAK_SLAB;
	public static final Block COBBLESTONE_SLAB;
	public static final Block BRICK_SLAB;
	public static final Block STONE_BRICK_SLAB;
	public static final Block NETHER_BRICK_SLAB;
	public static final Block QUARTZ_SLAB;
	public static final Block RED_SANDSTONE_SLAB;
	public static final Block PURPUR_SLAB;
	public static final Block PRISMARINE_SLAB;
	public static final Block PRISMARINE_BRICK_SLAB;
	public static final Block DARK_PRISMARINE_SLAB;
	public static final Block SMOOTH_STONE;
	public static final Block SMOOTH_SANDSTONE;
	public static final Block SMOOTH_QUARTZ;
	public static final Block SMOOTH_RED_SANDSTONE;
	public static final Block BRICKS;
	public static final Block TNT;
	public static final Block BOOKSHELF;
	public static final Block MOSSY_COBBLESTONE;
	public static final Block OBSIDIAN;
	public static final Block TORCH;
	public static final Block WALL_TORCH;
	public static final Block FIRE;
	public static final Block SPAWNER;
	public static final Block WOODEN_STAIRS;
	public static final Block CHEST;
	public static final Block REDSTONE_WIRE;
	public static final Block DIAMOND_ORE;
	public static final Block DIAMOND_BLOCK;
	public static final Block CRAFTING_TABLE;
	public static final Block WHEAT;
	public static final Block FARMLAND;
	public static final Block FURNACE;
	public static final Block SIGN;
	public static final Block OAK_DOOR;
	public static final Block SPRUCE_DOOR;
	public static final Block BIRCH_DOOR;
	public static final Block JUNGLE_DOOR;
	public static final Block ACACIA_DOOR;
	public static final Block DARK_OAK_DOOR;
	public static final Block LADDER;
	public static final Block RAIL;
	public static final Block COBBLESTONE_STAIRS;
	public static final Block WALL_SIGN;
	public static final Block LEVER;
	public static final Block STONE_PRESSURE_PLATE;
	public static final Block IRON_DOOR;
	public static final Block OAK_PRESSURE_PLATE;
	public static final Block SPRUCE_PRESSURE_PLATE;
	public static final Block BIRCH_PRESSURE_PLATE;
	public static final Block JUNGLE_PRESSURE_PLATE;
	public static final Block ACACIA_PRESSURE_PLATE;
	public static final Block DARK_OAK_PRESSURE_PLATE;
	public static final Block REDSTONE_ORE;
	public static final Block REDSTONE_TORCH;
	public static final Block REDSTONE_WALL_TORCH;
	public static final Block STONE_BUTTON;
	public static final Block SNOW;
	public static final Block ICE;
	public static final Block SNOW_BLOCK;
	public static final Block CACTUS;
	public static final Block CLAY;
	public static final Block SUGAR_CANE;
	public static final Block JUKEBOX;
	public static final Block OAK_FENCE;
	public static final Block SPRUCE_FENCE;
	public static final Block BIRCH_FENCE;
	public static final Block JUNGLE_FENCE;
	public static final Block DARK_OAK_FENCE;
	public static final Block ACACIA_FENCE;
	public static final Block PUMPKIN;
	public static final Block NETHERRACK;
	public static final Block SOULSAND;
	public static final Block GLOWSTONE;
	public static final Block NETHER_PORTAL;
	public static final Block CARVED_PUMPKIN;
	public static final Block JACK_O_LANTERN;
	public static final Block CAKE;
	public static final Block REPEATER;
	public static final Block OAK_TRAPDOOR;
	public static final Block SPRUCE_TRAPDOOR;
	public static final Block BIRCH_TRAPDOOR;
	public static final Block JUNGLE_TRAPDOOR;
	public static final Block ACACIA_TRAPDOOR;
	public static final Block DARK_OAK_TRAPDOOR;
	public static final Block INFESTED_STONE;
	public static final Block INFESTED_COBBLESTONE;
	public static final Block INFESTED_STONE_BRICKS;
	public static final Block INFESTED_MOSSY_STONE_BRICKS;
	public static final Block INFESTED_CRACKED_STONE_BRICKS;
	public static final Block INFESTED_CHISELED_STONE_BRICKS;
	public static final Block STONE_BRICKS;
	public static final Block MOSSY_STONE_BRICKS;
	public static final Block CRACKED_STONE_BRICKS;
	public static final Block CHISELED_STONE_BRICKS;
	public static final Block BROWN_MUSHROOM_BLOCK;
	public static final Block RED_MUSHROOM_BLOCK;
	public static final Block MUSHROOM_STEM;
	public static final Block IRON_BARS;
	public static final Block GLASS_PANE;
	public static final Block MELON_BLOCK;
	public static final Block ATTACHED_PUMPKIN_STEM;
	public static final Block ATTACHED_MELON_STEM;
	public static final Block PUMPKIN_STEM;
	public static final Block MELON_STEM;
	public static final Block VINE;
	public static final Block OAK_FENCE_GATE;
	public static final Block SPRUCE_FENCE_GATE;
	public static final Block BIRCH_FENCE_GATE;
	public static final Block JUNGLE_FENCE_GATE;
	public static final Block DARK_OAK_FENCE_GATE;
	public static final Block ACACIA_FENCE_GATE;
	public static final Block BRICK_STAIRS;
	public static final Block STONE_BRICK_STAIRS;
	public static final Block MYCELIUM;
	public static final Block LILY_PAD;
	public static final Block NETHER_BRICKS;
	public static final Block NETHER_BRICK_FENCE;
	public static final Block NETHER_BRICK_STAIRS;
	public static final Block NETHER_WART;
	public static final Block ENCHANTING_TABLE;
	public static final Block BREWING_STAND;
	public static final Block CAULDRON;
	public static final Block END_PORTAL;
	public static final Block END_PORTAL_FRAME;
	public static final Block END_STONE;
	public static final Block DRAGON_EGG;
	public static final Block REDSTONE_LAMP;
	public static final Block COCOA;
	public static final Block SANDSTONE_STAIRS;
	public static final Block EMERALD_ORE;
	public static final Block ENDERCHEST;
	public static final Block TRIPWIRE_HOOK;
	public static final Block TRIPWIRE;
	public static final Block EMERALD_BLOCK;
	public static final Block SPRUCE_STAIRS;
	public static final Block BIRCH_STAIRS;
	public static final Block JUNGLE_STAIRS;
	public static final Block COMMAND_BLOCK;
	public static final Block BEACON;
	public static final Block COBBLESTONE_WALL;
	public static final Block MOSSY_COBBLESTONE_WALL;
	public static final Block FLOWER_POT;
	public static final Block POTTED_POPPY;
	public static final Block POTTED_BLUE_ORCHID;
	public static final Block POTTED_ALLIUM;
	public static final Block POTTED_AZURE_BLUET;
	public static final Block POTTED_RED_TULIP;
	public static final Block POTTED_ORANGE_TULIP;
	public static final Block POTTED_WHITE_TULIP;
	public static final Block POTTED_PINK_TULIP;
	public static final Block POTTED_OXEYE_DAISY;
	public static final Block POTTED_DANDELION;
	public static final Block POTTED_OAK_SAPLING;
	public static final Block POTTED_SPRUCE_SAPLING;
	public static final Block POTTED_BIRCH_SAPLING;
	public static final Block POTTED_JUNGLE_SAPLING;
	public static final Block POTTED_ACACIA_SAPLING;
	public static final Block POTTED_DARK_OAK_SAPLING;
	public static final Block POTTED_RED_MUSHROOM;
	public static final Block POTTED_BROWN_MUSHROOM;
	public static final Block POTTED_DEAD_BUSH;
	public static final Block POTTED_FERN;
	public static final Block POTTED_CACTUS;
	public static final Block CARROTS;
	public static final Block POTATOES;
	public static final Block OAK_BUTTON;
	public static final Block SPRUCE_BUTTON;
	public static final Block BIRCH_BUTTON;
	public static final Block JUNGLE_BUTTON;
	public static final Block ACACIA_BUTTON;
	public static final Block DARK_OAK_BUTTON;
	public static final Block SKELETON_WALL_SKULL;
	public static final Block SKELETON_SKULL;
	public static final Block WITHER_SKELETON_WALL_SKULL;
	public static final Block WITHER_SKELETON_SKULL;
	public static final Block ZOMBIE_WALL_HEAD;
	public static final Block ZOMBIE_HEAD;
	public static final Block PLAYER_WALL_HEAD;
	public static final Block PLAYER_HEAD;
	public static final Block CREEPER_WALL_HEAD;
	public static final Block CREEPER_HEAD;
	public static final Block DRAGON_WALL_HEAD;
	public static final Block DRAGON_HEAD;
	public static final Block ANVIL;
	public static final Block CHIPPED_ANVIL;
	public static final Block DAMAGED_ANVIL;
	public static final Block TRAPPED_CHEST;
	public static final Block LIGHT_WEIGHTED_PRESSURE_PLATE;
	public static final Block HEAVY_WEIGHTED_PRESSURE_PLATE;
	public static final Block COMPARATOR;
	public static final Block DAYLIGHT_DETECTOR;
	public static final Block REDSTONE_BLOCK;
	public static final Block NETHER_QUARTZ_ORE;
	public static final Block HOPPER;
	public static final Block QUARTZ_BLOCK;
	public static final Block QUARTZ_PILLAR;
	public static final Block CHISELED_QUARTZ_BLOCK;
	public static final Block QUARTZ_STAIRS;
	public static final Block ACTIVATOR_RAIL;
	public static final Block DROPPER;
	public static final Block WHITE_TERRACOTTA;
	public static final Block ORANGE_TERRACOTTA;
	public static final Block MAGENTA_TERRACOTTA;
	public static final Block LIGHT_BLUE_TERRACOTTA;
	public static final Block YELLOW_TERRACOTTA;
	public static final Block LIME_TERRACOTTA;
	public static final Block PINK_TERRACOTTA;
	public static final Block GRAY_TERRACOTTA;
	public static final Block LIGHT_GRAY_TERRACOTTA;
	public static final Block CYAN_TERRACOTTA;
	public static final Block PURPLE_TERRACOTTA;
	public static final Block BLUE_TERRACOTTA;
	public static final Block BROWN_TERRACOTTA;
	public static final Block GREEN_TERRACOTTA;
	public static final Block RED_TERRACOTTA;
	public static final Block BLACK_TERRACOTTA;
	public static final Block BARRIER;
	public static final Block IRON_TRAPDOOR;
	public static final Block HAY_BALE;
	public static final Block WHITE_CARPET;
	public static final Block ORANGE_CARPET;
	public static final Block MAGENTA_CARPET;
	public static final Block LIGHT_BLUE_CARPET;
	public static final Block YELLOW_CARPET;
	public static final Block LIME_CARPET;
	public static final Block PINK_CARPET;
	public static final Block GRAY_CARPET;
	public static final Block LIGHT_GRAY_CARPET;
	public static final Block CYAN_CARPET;
	public static final Block PURPLE_CARPET;
	public static final Block BLUE_CARPET;
	public static final Block BROWN_CARPET;
	public static final Block GREEN_CARPET;
	public static final Block RED_CARPET;
	public static final Block BLACK_CARPET;
	public static final Block TERRACOTTA;
	public static final Block COAL_BLOCK;
	public static final Block PACKED_ICE;
	public static final Block BLUE_ICE;
	public static final Block ACACIA_STAIRS;
	public static final Block DARK_OAK_STAIRS;
	public static final Block SLIME_BLOCK;
	public static final Block SUNFLOWER;
	public static final Block LILAC;
	public static final Block ROSE_BUSH;
	public static final Block PEONY;
	public static final Block TALL_GRASS;
	public static final Block LARGE_FERN;
	public static final Block WHITE_STAINED_GLASS;
	public static final Block ORANGE_STAINED_GLASS;
	public static final Block MAGENTA_STAINED_GLASS;
	public static final Block LIGHT_BLUE_STAINED_GLASS;
	public static final Block YELLOW_STAINED_GLASS;
	public static final Block LIME_STAINED_GLASS;
	public static final Block PINK_STAINED_GLASS;
	public static final Block GRAY_STAINED_GLASS;
	public static final Block LIGHT_GRAY_STAINED_GLASS;
	public static final Block CYAN_STAINED_GLASS;
	public static final Block PURPLE_STAINED_GLASS;
	public static final Block BLUE_STAINED_GLASS;
	public static final Block BROWN_STAINED_GLASS;
	public static final Block GREEN_STAINED_GLASS;
	public static final Block RED_STAINED_GLASS;
	public static final Block BLACK_STAINED_GLASS;
	public static final Block WHITE_STAINED_GLASS_PANE;
	public static final Block ORANGE_STAINED_GLASS_PANE;
	public static final Block MAGENTA_STAINED_GLASS_PANE;
	public static final Block LIGHT_BLUE_STAINED_GLASS_PANE;
	public static final Block YELLOW_STAINED_GLASS_PANE;
	public static final Block LIME_STAINED_GLASS_PANE;
	public static final Block PINK_STAINED_GLASS_PANE;
	public static final Block GRAY_STAINED_GLASS_PANE;
	public static final Block LIGHT_GRAY_STAINED_GLASS_PANE;
	public static final Block CYAN_STAINED_GLASS_PANE;
	public static final Block PURPLE_STAINED_GLASS_PANE;
	public static final Block BLUE_STAINED_GLASS_PANE;
	public static final Block BROWN_STAINED_GLASS_PANE;
	public static final Block GREEN_STAINED_GLASS_PANE;
	public static final Block RED_STAINED_GLASS_PANE;
	public static final Block BLACK_STAINED_GLASS_PANE;
	public static final Block PRISMARINE;
	public static final Block PRISMARINE_BRICKS;
	public static final Block DARK_PRISMARINE;
	public static final Block PRISMARINE_STAIRS;
	public static final Block PRISMARINE_BRICK_STAIRS;
	public static final Block DARK_PRISMARINE_STAIRS;
	public static final Block SEA_LANTERN;
	public static final Block WHITE_BANNER;
	public static final Block ORANGE_BANNER;
	public static final Block MAGENTA_BANNER;
	public static final Block LIGHT_BLUE_BANNER;
	public static final Block YELLOW_BANNER;
	public static final Block LIME_BANNER;
	public static final Block PINK_BANNER;
	public static final Block GRAY_BANNER;
	public static final Block LIGHT_GRAY_BANNER;
	public static final Block CYAN_BANNER;
	public static final Block PURPLE_BANNER;
	public static final Block BLUE_BANNER;
	public static final Block BROWN_BANNER;
	public static final Block GREEN_BANNER;
	public static final Block RED_BANNER;
	public static final Block BLACK_BANNER;
	public static final Block WHITE_WALL_BANNER;
	public static final Block ORANGE_WALL_BANNER;
	public static final Block MAGENTA_WALL_BANNER;
	public static final Block LIGHT_BLUE_WALL_BANNER;
	public static final Block YELLOW_WALL_BANNER;
	public static final Block LIME_WALL_BANNER;
	public static final Block PINK_WALL_BANNER;
	public static final Block GRAY_WALL_BANNER;
	public static final Block LIGHT_GRAY_WALL_BANNER;
	public static final Block CYAN_WALL_BANNER;
	public static final Block PURPLE_WALL_BANNER;
	public static final Block BLUE_WALL_BANNER;
	public static final Block BROWN_WALL_BANNER;
	public static final Block GREEN_WALL_BANNER;
	public static final Block RED_WALL_BANNER;
	public static final Block BLACK_WALL_BANNER;
	public static final Block RED_SANDSTONE;
	public static final Block CHISELED_RED_SANDSTONE;
	public static final Block CUT_RED_SANDSTONE;
	public static final Block RED_SANDSTONE_STAIRS;
	public static final Block END_ROD;
	public static final Block CHORUS_PLANT;
	public static final Block CHORUS_FLOWER;
	public static final Block PURPUR_BLOCK;
	public static final Block PURPUR_PILLAR;
	public static final Block PURPUR_STAIRS;
	public static final Block END_STONE_BRICKS;
	public static final Block BEETROOTS;
	public static final Block GRASS_PATH;
	public static final Block END_GATEWAY;
	public static final Block REPEATING_COMMAND_BLOCK;
	public static final Block CHAIN_COMMAND_BLOCK;
	public static final Block FROSTED_ICE;
	public static final Block MAGMA_BLOCK;
	public static final Block NETHER_WART_BLOCK;
	public static final Block RED_NETHER_BRICKS;
	public static final Block BONE_BLOCK;
	public static final Block STRUCTURE_VOID;
	public static final Block OBSERVER;
	public static final Block SHULKER_BOX;
	public static final Block WHITE_SHULKER_BOX;
	public static final Block ORANGE_SHULKER_BOX;
	public static final Block MAGENTA_SHULKER_BOX;
	public static final Block LIGHT_BLUE_SHULKER_BOX;
	public static final Block YELLOW_SHULKER_BOX;
	public static final Block LIME_SHULKER_BOX;
	public static final Block PINK_SHULKER_BOX;
	public static final Block GRAY_SHULKER_BOX;
	public static final Block LIGHT_GRAY_SHULKER_BOX;
	public static final Block CYAN_SHULKER_BOX;
	public static final Block PURPLE_SHULKER_BOX;
	public static final Block BLUE_SHULKER_BOX;
	public static final Block BROWN_SHULKER_BOX;
	public static final Block GREEN_SHULKER_BOX;
	public static final Block RED_SHULKER_BOX;
	public static final Block BLACK_SHULKER_BOX;
	public static final Block WHITE_GLAZED_TERRACOTTA;
	public static final Block ORANGE_GLAZED_TERRACOTTA;
	public static final Block MAGENTA_GLAZED_TERRACOTTA;
	public static final Block LIGHT_BLUE_GLAZED_TERRACOTTA;
	public static final Block YELLOW_GLAZED_TERRACOTTA;
	public static final Block LIME_GLAZED_TERRACOTTA;
	public static final Block PINK_GLAZED_TERRACOTTA;
	public static final Block GRAY_GLAZED_TERRACOTTA;
	public static final Block LIGHT_GRAY_GLAZED_TERRACOTTA;
	public static final Block CYAN_GLAZED_TERRACOTTA;
	public static final Block PURPLE_GLAZED_TERRACOTTA;
	public static final Block BLUE_GLAZED_TERRACOTTA;
	public static final Block BROWN_GLAZED_TERRACOTTA;
	public static final Block GREEN_GLAZED_TERRACOTTA;
	public static final Block RED_GLAZED_TERRACOTTA;
	public static final Block BLACK_GLAZED_TERRACOTTA;
	public static final Block WHITE_CONCRETE;
	public static final Block ORANGE_CONCRETE;
	public static final Block MAGENTA_CONCRETE;
	public static final Block LIGHT_BLUE_CONCRETE;
	public static final Block YELLOW_CONCRETE;
	public static final Block LIME_CONCRETE;
	public static final Block PINK_CONCRETE;
	public static final Block GRAY_CONCRETE;
	public static final Block LIGHT_GRAY_CONCRETE;
	public static final Block CYAN_CONCRETE;
	public static final Block PURPLE_CONCRETE;
	public static final Block BLUE_CONCRETE;
	public static final Block BROWN_CONCRETE;
	public static final Block GREEN_CONCRETE;
	public static final Block RED_CONCRETE;
	public static final Block BLACK_CONCRETE;
	public static final Block WHITE_CONCRETE_POWDER;
	public static final Block ORANGE_CONCRETE_POWDER;
	public static final Block MAGENTA_CONCRETE_POWDER;
	public static final Block LIGHT_BLUE_CONCRETE_POWDER;
	public static final Block YELLOW_CONCRETE_POWDER;
	public static final Block LIME_CONCRETE_POWDER;
	public static final Block PINK_CONCRETE_POWDER;
	public static final Block GRAY_CONCRETE_POWDER;
	public static final Block LIGHT_GRAY_CONCRETE_POWDER;
	public static final Block CYAN_CONCRETE_POWDER;
	public static final Block PURPLE_CONCRETE_POWDER;
	public static final Block BLUE_CONCRETE_POWDER;
	public static final Block BROWN_CONCRETE_POWDER;
	public static final Block GREEN_CONCRETE_POWDER;
	public static final Block RED_CONCRETE_POWDER;
	public static final Block BLACK_CONCRETE_POWDER;
	public static final Block KELP_PLANT;
	public static final Block KELP;
	public static final Block DRIED_KELP_BLOCK;
	public static final Block TURTLE_EGG;
	public static final Block VOID_AIR;
	public static final Block CAVE_AIR;
	public static final Block DEAD_TUBE_CORAL_BLOCK;
	public static final Block DEAD_BRAIN_CORAL_BLOCK;
	public static final Block DEAD_BUBBLE_CORAL_BLOCK;
	public static final Block DEAD_FIRE_CORAL_BLOCK;
	public static final Block DEAD_HORN_CORAL_BLOCK;
	public static final Block TUBE_CORAL_BLOCK;
	public static final Block BRAIN_CORAL_BLOCK;
	public static final Block BUBBLE_CORAL_BLOCK;
	public static final Block FIRE_CORAL_BLOCK;
	public static final Block HORN_CORAL_BLOCK;
	public static final Block TUBE_CORAL;
	public static final Block BRAIN_CORAL;
	public static final Block BUBBLE_CORAL;
	public static final Block FIRE_CORAL;
	public static final Block HORN_CORAL;
	public static final Block DEAD_TUBE_CORAL;
	public static final Block DEAD_BRAIN_CORAL;
	public static final Block DEAD_BUBBLE_CORAL;
	public static final Block DEAD_FIRE_CORAL;
	public static final Block DEAD_HORN_CORAL;
	public static final Block TUBE_CORAL_WALL_FAN;
	public static final Block BRAIN_CORAL_WALL_FAN;
	public static final Block BUBBLE_CORAL_WALL_FAN;
	public static final Block FIRE_CORAL_WALL_FAN;
	public static final Block HORN_CORAL_WALL_FAN;
	public static final Block TUBE_CORAL_FAN;
	public static final Block BRAIN_CORAL_FAN;
	public static final Block BUBBLE_CORAL_FAN;
	public static final Block FIRE_CORAL_FAN;
	public static final Block HORN_CORAL_FAN;
	public static final Block SEA_PICKLE;
	public static final Block CONDUIT;
	public static final Block DEAD_TUBE_CORAL_WALL_FAN;
	public static final Block DEAD_BRAIN_CORAL_WALL_FAN;
	public static final Block DEAD_BUBBLE_CORAL_WALL_FAN;
	public static final Block DEAD_FIRE_CORAL_WALL_FAN;
	public static final Block DEAD_HORN_CORAL_WALL_FAN;
	public static final Block DEAD_TUBE_CORAL_FAN;
	public static final Block DEAD_BRAIN_CORAL_FAN;
	public static final Block DEAD_BUBBLE_CORAL_FAN;
	public static final Block DEAD_FIRE_CORAL_FAN;
	public static final Block DEAD_HORN_CORAL_FAN;
	public static final Block STRUCTURE_BLOCK;

	private static Block getById(String id) {
		Block block = Registry.BLOCK.get(new Identifier(id));
		if (!field_12591.add(block)) {
			throw new IllegalStateException("Invalid Block requested: " + id);
		} else {
			return block;
		}
	}

	static {
		if (!Bootstrap.isInitialized()) {
			throw new RuntimeException("Accessed Blocks before Bootstrap!");
		} else {
			field_12591 = Sets.newHashSet(new Block[]{(Block)null});
			AIR = getById("air");
			STONE = getById("stone");
			GRANITE = getById("granite");
			POLISHED_GRANITE = getById("polished_granite");
			DIORITE = getById("diorite");
			POLISHED_DIORITE = getById("polished_diorite");
			ANDESITE = getById("andesite");
			POLISHED_ANDESITE = getById("polished_andesite");
			GRASS_BLOCK = getById("grass_block");
			DIRT = getById("dirt");
			COARSE_DIRT = getById("coarse_dirt");
			PODZOL = getById("podzol");
			COBBLESTONE = getById("cobblestone");
			OAK_PLANKS = getById("oak_planks");
			SPRUCE_PLANKS = getById("spruce_planks");
			BIRCH_PLANKS = getById("birch_planks");
			JUNGLE_PLANKS = getById("jungle_planks");
			ACACIA_PLANKS = getById("acacia_planks");
			DARK_OAK_PLANKS = getById("dark_oak_planks");
			OAK_SAPLING = getById("oak_sapling");
			SPRUCE_SAPLING = getById("spruce_sapling");
			BIRCH_SAPLING = getById("birch_sapling");
			JUNGLE_SAPLING = getById("jungle_sapling");
			ACACIA_SAPLING = getById("acacia_sapling");
			DARK_OAK_SAPLING = getById("dark_oak_sapling");
			BEDROCK = getById("bedrock");
			WATER = getById("water");
			BUBBLE_COLUMN = getById("bubble_column");
			LAVA = getById("lava");
			SAND = getById("sand");
			RED_SAND = getById("red_sand");
			GRAVEL = getById("gravel");
			GOLD_ORE = getById("gold_ore");
			IRON_ORE = getById("iron_ore");
			COAL_ORE = getById("coal_ore");
			OAK_LOG = getById("oak_log");
			SPRUCE_LOG = getById("spruce_log");
			BIRCH_LOG = getById("birch_log");
			JUNGLE_LOG = getById("jungle_log");
			ACACIA_LOG = getById("acacia_log");
			DARK_OAK_LOG = getById("dark_oak_log");
			STRIPPED_OAK_LOG = getById("stripped_oak_log");
			STRIPPED_SPRUCE_LOG = getById("stripped_spruce_log");
			STRIPPED_BIRCH_LOG = getById("stripped_birch_log");
			STRIPPED_JUNGLE_LOG = getById("stripped_jungle_log");
			STRIPPED_ACACIA_LOG = getById("stripped_acacia_log");
			STRIPPED_DARK_OAK_LOG = getById("stripped_dark_oak_log");
			OAK_WOOD = getById("oak_wood");
			SPRUCE_WOOD = getById("spruce_wood");
			BIRCH_WOOD = getById("birch_wood");
			JUNGLE_WOOD = getById("jungle_wood");
			ACACIA_WOOD = getById("acacia_wood");
			DARK_OAK_WOOD = getById("dark_oak_wood");
			STRIPPED_OAK_WOOD = getById("stripped_oak_wood");
			STRIPPED_SPRUCE_WOOD = getById("stripped_spruce_wood");
			STRIPPED_BIRCH_WOOD = getById("stripped_birch_wood");
			STRIPPED_JUNGLE_WOOD = getById("stripped_jungle_wood");
			STRIPPED_ACACIA_WOOD = getById("stripped_acacia_wood");
			STRIPPED_DARK_OAK_WOOD = getById("stripped_dark_oak_wood");
			OAK_LEAVES = getById("oak_leaves");
			SPRUCE_LEAVES = getById("spruce_leaves");
			BIRCH_LEAVES = getById("birch_leaves");
			JUNGLE_LEAVES = getById("jungle_leaves");
			ACACIA_LEAVES = getById("acacia_leaves");
			DARK_OAK_LEAVES = getById("dark_oak_leaves");
			SPONGE = getById("sponge");
			WET_SPONGE = getById("wet_sponge");
			GLASS = getById("glass");
			LAPIS_LAZULI_ORE = getById("lapis_ore");
			LAPIS_LAZULI_BLOCK = getById("lapis_block");
			DISPENSER = getById("dispenser");
			SANDSTONE = getById("sandstone");
			CHISELED_SANDSTONE = getById("chiseled_sandstone");
			CUT_SANDSTONE = getById("cut_sandstone");
			NOTE_BLOCK = getById("note_block");
			WHITE_BED = getById("white_bed");
			ORANGE_BED = getById("orange_bed");
			MAGENTA_BED = getById("magenta_bed");
			LIGHT_BLUE_BED = getById("light_blue_bed");
			YELLOW_BED = getById("yellow_bed");
			LIME_BED = getById("lime_bed");
			PINK_BED = getById("pink_bed");
			GRAY_BED = getById("gray_bed");
			LIGHT_GRAY_BED = getById("light_gray_bed");
			CYAN_BED = getById("cyan_bed");
			PURPLE_BED = getById("purple_bed");
			BLUE_BED = getById("blue_bed");
			BROWN_BED = getById("brown_bed");
			GREEN_BED = getById("green_bed");
			RED_BED = getById("red_bed");
			BLACK_BED = getById("black_bed");
			POWERED_RAIL = getById("powered_rail");
			DETECTOR_RAIL = getById("detector_rail");
			STICKY_PISTON = getById("sticky_piston");
			COBWEB = getById("cobweb");
			GRASS = getById("grass");
			FERN = getById("fern");
			DEAD_BUSH = getById("dead_bush");
			SEAGRASS = getById("seagrass");
			TALL_SEAGRASS = getById("tall_seagrass");
			PISTON = getById("piston");
			PISTON_HEAD = getById("piston_head");
			WHITE_WOOL = getById("white_wool");
			ORANGE_WOOL = getById("orange_wool");
			MAGENTA_WOOL = getById("magenta_wool");
			LIGHT_BLUE_WOOL = getById("light_blue_wool");
			YELLOW_WOOL = getById("yellow_wool");
			LIME_WOOL = getById("lime_wool");
			PINK_WOOL = getById("pink_wool");
			GRAY_WOOL = getById("gray_wool");
			LIGHT_GRAY_WOOL = getById("light_gray_wool");
			CYAN_WOOL = getById("cyan_wool");
			PURPLE_WOOL = getById("purple_wool");
			BLUE_WOOL = getById("blue_wool");
			BROWN_WOOL = getById("brown_wool");
			GREEN_WOOL = getById("green_wool");
			RED_WOOL = getById("red_wool");
			BLACK_WOOL = getById("black_wool");
			MOVING_PISTON = getById("moving_piston");
			DANDELION = getById("dandelion");
			POPPY = getById("poppy");
			BLUE_ORCHID = getById("blue_orchid");
			ALLIUM = getById("allium");
			AZURE_BLUET = getById("azure_bluet");
			RED_TULIP = getById("red_tulip");
			ORANGE_TULIP = getById("orange_tulip");
			WHITE_TULIP = getById("white_tulip");
			PINK_TULIP = getById("pink_tulip");
			OXEYE_DAISY = getById("oxeye_daisy");
			BROWN_MUSHROOM = getById("brown_mushroom");
			RED_MUSHROOM = getById("red_mushroom");
			GOLD_BLOCK = getById("gold_block");
			IRON_BLOCK = getById("iron_block");
			OAK_SLAB = getById("oak_slab");
			SPRUCE_SLAB = getById("spruce_slab");
			BIRCH_SLAB = getById("birch_slab");
			JUNGLE_SLAB = getById("jungle_slab");
			ACACIA_SLAB = getById("acacia_slab");
			DARK_OAK_SLAB = getById("dark_oak_slab");
			STONE_SLAB = getById("stone_slab");
			SANDSTONE_SLAB = getById("sandstone_slab");
			PETRIFIED_OAK_SLAB = getById("petrified_oak_slab");
			COBBLESTONE_SLAB = getById("cobblestone_slab");
			BRICK_SLAB = getById("brick_slab");
			STONE_BRICK_SLAB = getById("stone_brick_slab");
			NETHER_BRICK_SLAB = getById("nether_brick_slab");
			QUARTZ_SLAB = getById("quartz_slab");
			RED_SANDSTONE_SLAB = getById("red_sandstone_slab");
			PURPUR_SLAB = getById("purpur_slab");
			PRISMARINE_SLAB = getById("prismarine_slab");
			PRISMARINE_BRICK_SLAB = getById("prismarine_brick_slab");
			DARK_PRISMARINE_SLAB = getById("dark_prismarine_slab");
			SMOOTH_STONE = getById("smooth_stone");
			SMOOTH_SANDSTONE = getById("smooth_sandstone");
			SMOOTH_QUARTZ = getById("smooth_quartz");
			SMOOTH_RED_SANDSTONE = getById("smooth_red_sandstone");
			BRICKS = getById("bricks");
			TNT = getById("tnt");
			BOOKSHELF = getById("bookshelf");
			MOSSY_COBBLESTONE = getById("mossy_cobblestone");
			OBSIDIAN = getById("obsidian");
			TORCH = getById("torch");
			WALL_TORCH = getById("wall_torch");
			FIRE = getById("fire");
			SPAWNER = getById("spawner");
			WOODEN_STAIRS = getById("oak_stairs");
			CHEST = getById("chest");
			REDSTONE_WIRE = getById("redstone_wire");
			DIAMOND_ORE = getById("diamond_ore");
			DIAMOND_BLOCK = getById("diamond_block");
			CRAFTING_TABLE = getById("crafting_table");
			WHEAT = getById("wheat");
			FARMLAND = getById("farmland");
			FURNACE = getById("furnace");
			SIGN = getById("sign");
			OAK_DOOR = getById("oak_door");
			SPRUCE_DOOR = getById("spruce_door");
			BIRCH_DOOR = getById("birch_door");
			JUNGLE_DOOR = getById("jungle_door");
			ACACIA_DOOR = getById("acacia_door");
			DARK_OAK_DOOR = getById("dark_oak_door");
			LADDER = getById("ladder");
			RAIL = getById("rail");
			COBBLESTONE_STAIRS = getById("cobblestone_stairs");
			WALL_SIGN = getById("wall_sign");
			LEVER = getById("lever");
			STONE_PRESSURE_PLATE = getById("stone_pressure_plate");
			IRON_DOOR = getById("iron_door");
			OAK_PRESSURE_PLATE = getById("oak_pressure_plate");
			SPRUCE_PRESSURE_PLATE = getById("spruce_pressure_plate");
			BIRCH_PRESSURE_PLATE = getById("birch_pressure_plate");
			JUNGLE_PRESSURE_PLATE = getById("jungle_pressure_plate");
			ACACIA_PRESSURE_PLATE = getById("acacia_pressure_plate");
			DARK_OAK_PRESSURE_PLATE = getById("dark_oak_pressure_plate");
			REDSTONE_ORE = getById("redstone_ore");
			REDSTONE_TORCH = getById("redstone_torch");
			REDSTONE_WALL_TORCH = getById("redstone_wall_torch");
			STONE_BUTTON = getById("stone_button");
			SNOW = getById("snow");
			ICE = getById("ice");
			SNOW_BLOCK = getById("snow_block");
			CACTUS = getById("cactus");
			CLAY = getById("clay");
			SUGAR_CANE = getById("sugar_cane");
			JUKEBOX = getById("jukebox");
			OAK_FENCE = getById("oak_fence");
			SPRUCE_FENCE = getById("spruce_fence");
			BIRCH_FENCE = getById("birch_fence");
			JUNGLE_FENCE = getById("jungle_fence");
			DARK_OAK_FENCE = getById("dark_oak_fence");
			ACACIA_FENCE = getById("acacia_fence");
			PUMPKIN = getById("pumpkin");
			NETHERRACK = getById("netherrack");
			SOULSAND = getById("soul_sand");
			GLOWSTONE = getById("glowstone");
			NETHER_PORTAL = getById("nether_portal");
			CARVED_PUMPKIN = getById("carved_pumpkin");
			JACK_O_LANTERN = getById("jack_o_lantern");
			CAKE = getById("cake");
			REPEATER = getById("repeater");
			OAK_TRAPDOOR = getById("oak_trapdoor");
			SPRUCE_TRAPDOOR = getById("spruce_trapdoor");
			BIRCH_TRAPDOOR = getById("birch_trapdoor");
			JUNGLE_TRAPDOOR = getById("jungle_trapdoor");
			ACACIA_TRAPDOOR = getById("acacia_trapdoor");
			DARK_OAK_TRAPDOOR = getById("dark_oak_trapdoor");
			INFESTED_STONE = getById("infested_stone");
			INFESTED_COBBLESTONE = getById("infested_cobblestone");
			INFESTED_STONE_BRICKS = getById("infested_stone_bricks");
			INFESTED_MOSSY_STONE_BRICKS = getById("infested_mossy_stone_bricks");
			INFESTED_CRACKED_STONE_BRICKS = getById("infested_cracked_stone_bricks");
			INFESTED_CHISELED_STONE_BRICKS = getById("infested_chiseled_stone_bricks");
			STONE_BRICKS = getById("stone_bricks");
			MOSSY_STONE_BRICKS = getById("mossy_stone_bricks");
			CRACKED_STONE_BRICKS = getById("cracked_stone_bricks");
			CHISELED_STONE_BRICKS = getById("chiseled_stone_bricks");
			BROWN_MUSHROOM_BLOCK = getById("brown_mushroom_block");
			RED_MUSHROOM_BLOCK = getById("red_mushroom_block");
			MUSHROOM_STEM = getById("mushroom_stem");
			IRON_BARS = getById("iron_bars");
			GLASS_PANE = getById("glass_pane");
			MELON_BLOCK = getById("melon");
			ATTACHED_PUMPKIN_STEM = getById("attached_pumpkin_stem");
			ATTACHED_MELON_STEM = getById("attached_melon_stem");
			PUMPKIN_STEM = getById("pumpkin_stem");
			MELON_STEM = getById("melon_stem");
			VINE = getById("vine");
			OAK_FENCE_GATE = getById("oak_fence_gate");
			SPRUCE_FENCE_GATE = getById("spruce_fence_gate");
			BIRCH_FENCE_GATE = getById("birch_fence_gate");
			JUNGLE_FENCE_GATE = getById("jungle_fence_gate");
			DARK_OAK_FENCE_GATE = getById("dark_oak_fence_gate");
			ACACIA_FENCE_GATE = getById("acacia_fence_gate");
			BRICK_STAIRS = getById("brick_stairs");
			STONE_BRICK_STAIRS = getById("stone_brick_stairs");
			MYCELIUM = getById("mycelium");
			LILY_PAD = getById("lily_pad");
			NETHER_BRICKS = getById("nether_bricks");
			NETHER_BRICK_FENCE = getById("nether_brick_fence");
			NETHER_BRICK_STAIRS = getById("nether_brick_stairs");
			NETHER_WART = getById("nether_wart");
			ENCHANTING_TABLE = getById("enchanting_table");
			BREWING_STAND = getById("brewing_stand");
			CAULDRON = getById("cauldron");
			END_PORTAL = getById("end_portal");
			END_PORTAL_FRAME = getById("end_portal_frame");
			END_STONE = getById("end_stone");
			DRAGON_EGG = getById("dragon_egg");
			REDSTONE_LAMP = getById("redstone_lamp");
			COCOA = getById("cocoa");
			SANDSTONE_STAIRS = getById("sandstone_stairs");
			EMERALD_ORE = getById("emerald_ore");
			ENDERCHEST = getById("ender_chest");
			TRIPWIRE_HOOK = getById("tripwire_hook");
			TRIPWIRE = getById("tripwire");
			EMERALD_BLOCK = getById("emerald_block");
			SPRUCE_STAIRS = getById("spruce_stairs");
			BIRCH_STAIRS = getById("birch_stairs");
			JUNGLE_STAIRS = getById("jungle_stairs");
			COMMAND_BLOCK = getById("command_block");
			BEACON = getById("beacon");
			COBBLESTONE_WALL = getById("cobblestone_wall");
			MOSSY_COBBLESTONE_WALL = getById("mossy_cobblestone_wall");
			FLOWER_POT = getById("flower_pot");
			POTTED_POPPY = getById("potted_poppy");
			POTTED_BLUE_ORCHID = getById("potted_blue_orchid");
			POTTED_ALLIUM = getById("potted_allium");
			POTTED_AZURE_BLUET = getById("potted_azure_bluet");
			POTTED_RED_TULIP = getById("potted_red_tulip");
			POTTED_ORANGE_TULIP = getById("potted_orange_tulip");
			POTTED_WHITE_TULIP = getById("potted_white_tulip");
			POTTED_PINK_TULIP = getById("potted_pink_tulip");
			POTTED_OXEYE_DAISY = getById("potted_oxeye_daisy");
			POTTED_DANDELION = getById("potted_dandelion");
			POTTED_OAK_SAPLING = getById("potted_oak_sapling");
			POTTED_SPRUCE_SAPLING = getById("potted_spruce_sapling");
			POTTED_BIRCH_SAPLING = getById("potted_birch_sapling");
			POTTED_JUNGLE_SAPLING = getById("potted_jungle_sapling");
			POTTED_ACACIA_SAPLING = getById("potted_acacia_sapling");
			POTTED_DARK_OAK_SAPLING = getById("potted_dark_oak_sapling");
			POTTED_RED_MUSHROOM = getById("potted_red_mushroom");
			POTTED_BROWN_MUSHROOM = getById("potted_brown_mushroom");
			POTTED_DEAD_BUSH = getById("potted_dead_bush");
			POTTED_FERN = getById("potted_fern");
			POTTED_CACTUS = getById("potted_cactus");
			CARROTS = getById("carrots");
			POTATOES = getById("potatoes");
			OAK_BUTTON = getById("oak_button");
			SPRUCE_BUTTON = getById("spruce_button");
			BIRCH_BUTTON = getById("birch_button");
			JUNGLE_BUTTON = getById("jungle_button");
			ACACIA_BUTTON = getById("acacia_button");
			DARK_OAK_BUTTON = getById("dark_oak_button");
			SKELETON_WALL_SKULL = getById("skeleton_wall_skull");
			SKELETON_SKULL = getById("skeleton_skull");
			WITHER_SKELETON_WALL_SKULL = getById("wither_skeleton_wall_skull");
			WITHER_SKELETON_SKULL = getById("wither_skeleton_skull");
			ZOMBIE_WALL_HEAD = getById("zombie_wall_head");
			ZOMBIE_HEAD = getById("zombie_head");
			PLAYER_WALL_HEAD = getById("player_wall_head");
			PLAYER_HEAD = getById("player_head");
			CREEPER_WALL_HEAD = getById("creeper_wall_head");
			CREEPER_HEAD = getById("creeper_head");
			DRAGON_WALL_HEAD = getById("dragon_wall_head");
			DRAGON_HEAD = getById("dragon_head");
			ANVIL = getById("anvil");
			CHIPPED_ANVIL = getById("chipped_anvil");
			DAMAGED_ANVIL = getById("damaged_anvil");
			TRAPPED_CHEST = getById("trapped_chest");
			LIGHT_WEIGHTED_PRESSURE_PLATE = getById("light_weighted_pressure_plate");
			HEAVY_WEIGHTED_PRESSURE_PLATE = getById("heavy_weighted_pressure_plate");
			COMPARATOR = getById("comparator");
			DAYLIGHT_DETECTOR = getById("daylight_detector");
			REDSTONE_BLOCK = getById("redstone_block");
			NETHER_QUARTZ_ORE = getById("nether_quartz_ore");
			HOPPER = getById("hopper");
			QUARTZ_BLOCK = getById("quartz_block");
			QUARTZ_PILLAR = getById("quartz_pillar");
			CHISELED_QUARTZ_BLOCK = getById("chiseled_quartz_block");
			QUARTZ_STAIRS = getById("quartz_stairs");
			ACTIVATOR_RAIL = getById("activator_rail");
			DROPPER = getById("dropper");
			WHITE_TERRACOTTA = getById("white_terracotta");
			ORANGE_TERRACOTTA = getById("orange_terracotta");
			MAGENTA_TERRACOTTA = getById("magenta_terracotta");
			LIGHT_BLUE_TERRACOTTA = getById("light_blue_terracotta");
			YELLOW_TERRACOTTA = getById("yellow_terracotta");
			LIME_TERRACOTTA = getById("lime_terracotta");
			PINK_TERRACOTTA = getById("pink_terracotta");
			GRAY_TERRACOTTA = getById("gray_terracotta");
			LIGHT_GRAY_TERRACOTTA = getById("light_gray_terracotta");
			CYAN_TERRACOTTA = getById("cyan_terracotta");
			PURPLE_TERRACOTTA = getById("purple_terracotta");
			BLUE_TERRACOTTA = getById("blue_terracotta");
			BROWN_TERRACOTTA = getById("brown_terracotta");
			GREEN_TERRACOTTA = getById("green_terracotta");
			RED_TERRACOTTA = getById("red_terracotta");
			BLACK_TERRACOTTA = getById("black_terracotta");
			BARRIER = getById("barrier");
			IRON_TRAPDOOR = getById("iron_trapdoor");
			HAY_BALE = getById("hay_block");
			WHITE_CARPET = getById("white_carpet");
			ORANGE_CARPET = getById("orange_carpet");
			MAGENTA_CARPET = getById("magenta_carpet");
			LIGHT_BLUE_CARPET = getById("light_blue_carpet");
			YELLOW_CARPET = getById("yellow_carpet");
			LIME_CARPET = getById("lime_carpet");
			PINK_CARPET = getById("pink_carpet");
			GRAY_CARPET = getById("gray_carpet");
			LIGHT_GRAY_CARPET = getById("light_gray_carpet");
			CYAN_CARPET = getById("cyan_carpet");
			PURPLE_CARPET = getById("purple_carpet");
			BLUE_CARPET = getById("blue_carpet");
			BROWN_CARPET = getById("brown_carpet");
			GREEN_CARPET = getById("green_carpet");
			RED_CARPET = getById("red_carpet");
			BLACK_CARPET = getById("black_carpet");
			TERRACOTTA = getById("terracotta");
			COAL_BLOCK = getById("coal_block");
			PACKED_ICE = getById("packed_ice");
			BLUE_ICE = getById("blue_ice");
			ACACIA_STAIRS = getById("acacia_stairs");
			DARK_OAK_STAIRS = getById("dark_oak_stairs");
			SLIME_BLOCK = getById("slime_block");
			SUNFLOWER = getById("sunflower");
			LILAC = getById("lilac");
			ROSE_BUSH = getById("rose_bush");
			PEONY = getById("peony");
			TALL_GRASS = getById("tall_grass");
			LARGE_FERN = getById("large_fern");
			WHITE_STAINED_GLASS = getById("white_stained_glass");
			ORANGE_STAINED_GLASS = getById("orange_stained_glass");
			MAGENTA_STAINED_GLASS = getById("magenta_stained_glass");
			LIGHT_BLUE_STAINED_GLASS = getById("light_blue_stained_glass");
			YELLOW_STAINED_GLASS = getById("yellow_stained_glass");
			LIME_STAINED_GLASS = getById("lime_stained_glass");
			PINK_STAINED_GLASS = getById("pink_stained_glass");
			GRAY_STAINED_GLASS = getById("gray_stained_glass");
			LIGHT_GRAY_STAINED_GLASS = getById("light_gray_stained_glass");
			CYAN_STAINED_GLASS = getById("cyan_stained_glass");
			PURPLE_STAINED_GLASS = getById("purple_stained_glass");
			BLUE_STAINED_GLASS = getById("blue_stained_glass");
			BROWN_STAINED_GLASS = getById("brown_stained_glass");
			GREEN_STAINED_GLASS = getById("green_stained_glass");
			RED_STAINED_GLASS = getById("red_stained_glass");
			BLACK_STAINED_GLASS = getById("black_stained_glass");
			WHITE_STAINED_GLASS_PANE = getById("white_stained_glass_pane");
			ORANGE_STAINED_GLASS_PANE = getById("orange_stained_glass_pane");
			MAGENTA_STAINED_GLASS_PANE = getById("magenta_stained_glass_pane");
			LIGHT_BLUE_STAINED_GLASS_PANE = getById("light_blue_stained_glass_pane");
			YELLOW_STAINED_GLASS_PANE = getById("yellow_stained_glass_pane");
			LIME_STAINED_GLASS_PANE = getById("lime_stained_glass_pane");
			PINK_STAINED_GLASS_PANE = getById("pink_stained_glass_pane");
			GRAY_STAINED_GLASS_PANE = getById("gray_stained_glass_pane");
			LIGHT_GRAY_STAINED_GLASS_PANE = getById("light_gray_stained_glass_pane");
			CYAN_STAINED_GLASS_PANE = getById("cyan_stained_glass_pane");
			PURPLE_STAINED_GLASS_PANE = getById("purple_stained_glass_pane");
			BLUE_STAINED_GLASS_PANE = getById("blue_stained_glass_pane");
			BROWN_STAINED_GLASS_PANE = getById("brown_stained_glass_pane");
			GREEN_STAINED_GLASS_PANE = getById("green_stained_glass_pane");
			RED_STAINED_GLASS_PANE = getById("red_stained_glass_pane");
			BLACK_STAINED_GLASS_PANE = getById("black_stained_glass_pane");
			PRISMARINE = getById("prismarine");
			PRISMARINE_BRICKS = getById("prismarine_bricks");
			DARK_PRISMARINE = getById("dark_prismarine");
			PRISMARINE_STAIRS = getById("prismarine_stairs");
			PRISMARINE_BRICK_STAIRS = getById("prismarine_brick_stairs");
			DARK_PRISMARINE_STAIRS = getById("dark_prismarine_stairs");
			SEA_LANTERN = getById("sea_lantern");
			WHITE_BANNER = getById("white_banner");
			ORANGE_BANNER = getById("orange_banner");
			MAGENTA_BANNER = getById("magenta_banner");
			LIGHT_BLUE_BANNER = getById("light_blue_banner");
			YELLOW_BANNER = getById("yellow_banner");
			LIME_BANNER = getById("lime_banner");
			PINK_BANNER = getById("pink_banner");
			GRAY_BANNER = getById("gray_banner");
			LIGHT_GRAY_BANNER = getById("light_gray_banner");
			CYAN_BANNER = getById("cyan_banner");
			PURPLE_BANNER = getById("purple_banner");
			BLUE_BANNER = getById("blue_banner");
			BROWN_BANNER = getById("brown_banner");
			GREEN_BANNER = getById("green_banner");
			RED_BANNER = getById("red_banner");
			BLACK_BANNER = getById("black_banner");
			WHITE_WALL_BANNER = getById("white_wall_banner");
			ORANGE_WALL_BANNER = getById("orange_wall_banner");
			MAGENTA_WALL_BANNER = getById("magenta_wall_banner");
			LIGHT_BLUE_WALL_BANNER = getById("light_blue_wall_banner");
			YELLOW_WALL_BANNER = getById("yellow_wall_banner");
			LIME_WALL_BANNER = getById("lime_wall_banner");
			PINK_WALL_BANNER = getById("pink_wall_banner");
			GRAY_WALL_BANNER = getById("gray_wall_banner");
			LIGHT_GRAY_WALL_BANNER = getById("light_gray_wall_banner");
			CYAN_WALL_BANNER = getById("cyan_wall_banner");
			PURPLE_WALL_BANNER = getById("purple_wall_banner");
			BLUE_WALL_BANNER = getById("blue_wall_banner");
			BROWN_WALL_BANNER = getById("brown_wall_banner");
			GREEN_WALL_BANNER = getById("green_wall_banner");
			RED_WALL_BANNER = getById("red_wall_banner");
			BLACK_WALL_BANNER = getById("black_wall_banner");
			RED_SANDSTONE = getById("red_sandstone");
			CHISELED_RED_SANDSTONE = getById("chiseled_red_sandstone");
			CUT_RED_SANDSTONE = getById("cut_red_sandstone");
			RED_SANDSTONE_STAIRS = getById("red_sandstone_stairs");
			END_ROD = getById("end_rod");
			CHORUS_PLANT = getById("chorus_plant");
			CHORUS_FLOWER = getById("chorus_flower");
			PURPUR_BLOCK = getById("purpur_block");
			PURPUR_PILLAR = getById("purpur_pillar");
			PURPUR_STAIRS = getById("purpur_stairs");
			END_STONE_BRICKS = getById("end_stone_bricks");
			BEETROOTS = getById("beetroots");
			GRASS_PATH = getById("grass_path");
			END_GATEWAY = getById("end_gateway");
			REPEATING_COMMAND_BLOCK = getById("repeating_command_block");
			CHAIN_COMMAND_BLOCK = getById("chain_command_block");
			FROSTED_ICE = getById("frosted_ice");
			MAGMA_BLOCK = getById("magma_block");
			NETHER_WART_BLOCK = getById("nether_wart_block");
			RED_NETHER_BRICKS = getById("red_nether_bricks");
			BONE_BLOCK = getById("bone_block");
			STRUCTURE_VOID = getById("structure_void");
			OBSERVER = getById("observer");
			SHULKER_BOX = getById("shulker_box");
			WHITE_SHULKER_BOX = getById("white_shulker_box");
			ORANGE_SHULKER_BOX = getById("orange_shulker_box");
			MAGENTA_SHULKER_BOX = getById("magenta_shulker_box");
			LIGHT_BLUE_SHULKER_BOX = getById("light_blue_shulker_box");
			YELLOW_SHULKER_BOX = getById("yellow_shulker_box");
			LIME_SHULKER_BOX = getById("lime_shulker_box");
			PINK_SHULKER_BOX = getById("pink_shulker_box");
			GRAY_SHULKER_BOX = getById("gray_shulker_box");
			LIGHT_GRAY_SHULKER_BOX = getById("light_gray_shulker_box");
			CYAN_SHULKER_BOX = getById("cyan_shulker_box");
			PURPLE_SHULKER_BOX = getById("purple_shulker_box");
			BLUE_SHULKER_BOX = getById("blue_shulker_box");
			BROWN_SHULKER_BOX = getById("brown_shulker_box");
			GREEN_SHULKER_BOX = getById("green_shulker_box");
			RED_SHULKER_BOX = getById("red_shulker_box");
			BLACK_SHULKER_BOX = getById("black_shulker_box");
			WHITE_GLAZED_TERRACOTTA = getById("white_glazed_terracotta");
			ORANGE_GLAZED_TERRACOTTA = getById("orange_glazed_terracotta");
			MAGENTA_GLAZED_TERRACOTTA = getById("magenta_glazed_terracotta");
			LIGHT_BLUE_GLAZED_TERRACOTTA = getById("light_blue_glazed_terracotta");
			YELLOW_GLAZED_TERRACOTTA = getById("yellow_glazed_terracotta");
			LIME_GLAZED_TERRACOTTA = getById("lime_glazed_terracotta");
			PINK_GLAZED_TERRACOTTA = getById("pink_glazed_terracotta");
			GRAY_GLAZED_TERRACOTTA = getById("gray_glazed_terracotta");
			LIGHT_GRAY_GLAZED_TERRACOTTA = getById("light_gray_glazed_terracotta");
			CYAN_GLAZED_TERRACOTTA = getById("cyan_glazed_terracotta");
			PURPLE_GLAZED_TERRACOTTA = getById("purple_glazed_terracotta");
			BLUE_GLAZED_TERRACOTTA = getById("blue_glazed_terracotta");
			BROWN_GLAZED_TERRACOTTA = getById("brown_glazed_terracotta");
			GREEN_GLAZED_TERRACOTTA = getById("green_glazed_terracotta");
			RED_GLAZED_TERRACOTTA = getById("red_glazed_terracotta");
			BLACK_GLAZED_TERRACOTTA = getById("black_glazed_terracotta");
			WHITE_CONCRETE = getById("white_concrete");
			ORANGE_CONCRETE = getById("orange_concrete");
			MAGENTA_CONCRETE = getById("magenta_concrete");
			LIGHT_BLUE_CONCRETE = getById("light_blue_concrete");
			YELLOW_CONCRETE = getById("yellow_concrete");
			LIME_CONCRETE = getById("lime_concrete");
			PINK_CONCRETE = getById("pink_concrete");
			GRAY_CONCRETE = getById("gray_concrete");
			LIGHT_GRAY_CONCRETE = getById("light_gray_concrete");
			CYAN_CONCRETE = getById("cyan_concrete");
			PURPLE_CONCRETE = getById("purple_concrete");
			BLUE_CONCRETE = getById("blue_concrete");
			BROWN_CONCRETE = getById("brown_concrete");
			GREEN_CONCRETE = getById("green_concrete");
			RED_CONCRETE = getById("red_concrete");
			BLACK_CONCRETE = getById("black_concrete");
			WHITE_CONCRETE_POWDER = getById("white_concrete_powder");
			ORANGE_CONCRETE_POWDER = getById("orange_concrete_powder");
			MAGENTA_CONCRETE_POWDER = getById("magenta_concrete_powder");
			LIGHT_BLUE_CONCRETE_POWDER = getById("light_blue_concrete_powder");
			YELLOW_CONCRETE_POWDER = getById("yellow_concrete_powder");
			LIME_CONCRETE_POWDER = getById("lime_concrete_powder");
			PINK_CONCRETE_POWDER = getById("pink_concrete_powder");
			GRAY_CONCRETE_POWDER = getById("gray_concrete_powder");
			LIGHT_GRAY_CONCRETE_POWDER = getById("light_gray_concrete_powder");
			CYAN_CONCRETE_POWDER = getById("cyan_concrete_powder");
			PURPLE_CONCRETE_POWDER = getById("purple_concrete_powder");
			BLUE_CONCRETE_POWDER = getById("blue_concrete_powder");
			BROWN_CONCRETE_POWDER = getById("brown_concrete_powder");
			GREEN_CONCRETE_POWDER = getById("green_concrete_powder");
			RED_CONCRETE_POWDER = getById("red_concrete_powder");
			BLACK_CONCRETE_POWDER = getById("black_concrete_powder");
			KELP_PLANT = getById("kelp_plant");
			KELP = getById("kelp");
			DRIED_KELP_BLOCK = getById("dried_kelp_block");
			TURTLE_EGG = getById("turtle_egg");
			VOID_AIR = getById("void_air");
			CAVE_AIR = getById("cave_air");
			DEAD_TUBE_CORAL_BLOCK = getById("dead_tube_coral_block");
			DEAD_BRAIN_CORAL_BLOCK = getById("dead_brain_coral_block");
			DEAD_BUBBLE_CORAL_BLOCK = getById("dead_bubble_coral_block");
			DEAD_FIRE_CORAL_BLOCK = getById("dead_fire_coral_block");
			DEAD_HORN_CORAL_BLOCK = getById("dead_horn_coral_block");
			TUBE_CORAL_BLOCK = getById("tube_coral_block");
			BRAIN_CORAL_BLOCK = getById("brain_coral_block");
			BUBBLE_CORAL_BLOCK = getById("bubble_coral_block");
			FIRE_CORAL_BLOCK = getById("fire_coral_block");
			HORN_CORAL_BLOCK = getById("horn_coral_block");
			TUBE_CORAL = getById("tube_coral");
			BRAIN_CORAL = getById("brain_coral");
			BUBBLE_CORAL = getById("bubble_coral");
			FIRE_CORAL = getById("fire_coral");
			HORN_CORAL = getById("horn_coral");
			DEAD_TUBE_CORAL = getById("dead_tube_coral");
			DEAD_BRAIN_CORAL = getById("dead_brain_coral");
			DEAD_BUBBLE_CORAL = getById("dead_bubble_coral");
			DEAD_FIRE_CORAL = getById("dead_fire_coral");
			DEAD_HORN_CORAL = getById("dead_horn_coral");
			TUBE_CORAL_WALL_FAN = getById("tube_coral_wall_fan");
			BRAIN_CORAL_WALL_FAN = getById("brain_coral_wall_fan");
			BUBBLE_CORAL_WALL_FAN = getById("bubble_coral_wall_fan");
			FIRE_CORAL_WALL_FAN = getById("fire_coral_wall_fan");
			HORN_CORAL_WALL_FAN = getById("horn_coral_wall_fan");
			TUBE_CORAL_FAN = getById("tube_coral_fan");
			BRAIN_CORAL_FAN = getById("brain_coral_fan");
			BUBBLE_CORAL_FAN = getById("bubble_coral_fan");
			FIRE_CORAL_FAN = getById("fire_coral_fan");
			HORN_CORAL_FAN = getById("horn_coral_fan");
			SEA_PICKLE = getById("sea_pickle");
			CONDUIT = getById("conduit");
			DEAD_TUBE_CORAL_WALL_FAN = getById("dead_tube_coral_wall_fan");
			DEAD_BRAIN_CORAL_WALL_FAN = getById("dead_brain_coral_wall_fan");
			DEAD_BUBBLE_CORAL_WALL_FAN = getById("dead_bubble_coral_wall_fan");
			DEAD_FIRE_CORAL_WALL_FAN = getById("dead_fire_coral_wall_fan");
			DEAD_HORN_CORAL_WALL_FAN = getById("dead_horn_coral_wall_fan");
			DEAD_TUBE_CORAL_FAN = getById("dead_tube_coral_fan");
			DEAD_BRAIN_CORAL_FAN = getById("dead_brain_coral_fan");
			DEAD_BUBBLE_CORAL_FAN = getById("dead_bubble_coral_fan");
			DEAD_FIRE_CORAL_FAN = getById("dead_fire_coral_fan");
			DEAD_HORN_CORAL_FAN = getById("dead_horn_coral_fan");
			STRUCTURE_BLOCK = getById("structure_block");
			field_12591.clear();
		}
	}
}
