package net.minecraft.block;

import com.google.common.collect.Sets;
import java.util.Set;
import javax.annotation.Nullable;
import net.minecraft.Bootstrap;
import net.minecraft.util.Identifier;

public class Blocks {
	private static final Set<Block> field_12591;
	public static final Block AIR;
	public static final Block STONE;
	public static final GrassBlock GRASS;
	public static final Block DIRT;
	public static final Block COBBLESTONE;
	public static final Block PLANKS;
	public static final Block SAPLING;
	public static final Block BEDROCK;
	public static final FlowingFluidBlock FLOWING_WATER;
	public static final FluidBlock WATER;
	public static final FlowingFluidBlock FLOWING_LAVA;
	public static final FluidBlock LAVA;
	public static final SandBlock SAND;
	public static final Block GRAVEL;
	public static final Block GOLD_ORE;
	public static final Block IRON_ORE;
	public static final Block COAL_ORE;
	public static final Block LOG;
	public static final Block LOG2;
	public static final LeavesBlock LEAVES;
	public static final LeavesBlock LEAVES2;
	public static final Block SPONGE;
	public static final Block GLASS;
	public static final Block LAPIS_LAZULI_ORE;
	public static final Block LAPIS_LAZULI_BLOCK;
	public static final Block DISPENSER;
	public static final Block SANDSTONE;
	public static final Block NOTEBLOCK;
	public static final Block BED;
	public static final Block POWERED_RAIL;
	public static final Block DETECTOR_RAIL;
	public static final PistonBlock STICKY_PISTON;
	public static final Block COBWEB;
	public static final TallPlantBlock TALLGRASS;
	public static final DeadBushBlock DEADBUSH;
	public static final PistonBlock PISTON;
	public static final PistonHeadBlock PISTON_HEAD;
	public static final Block WOOL;
	public static final PistonExtensionBlock PISTON_EXTENSION;
	public static final FlowerBlock YELLOW_FLOWER;
	public static final FlowerBlock RED_FLOWER;
	public static final PlantBlock BROWN_MUSHROOM;
	public static final PlantBlock RED_MUSHROOM;
	public static final Block GOLD_BLOCK;
	public static final Block IRON_BLOCK;
	public static final SlabBlock DOUBLE_STONE_SLAB;
	public static final SlabBlock STONE_SLAB;
	public static final Block BRICKS;
	public static final Block TNT;
	public static final Block BOOKSHELF;
	public static final Block MOSSY_COBBLESTONE;
	public static final Block OBSIDIAN;
	public static final Block TORCH;
	public static final FireBlock FIRE;
	public static final Block SPAWNER;
	public static final Block WOODEN_STAIRS;
	public static final ChestBlock CHEST;
	public static final RedstoneWireBlock REDSTONE_WIRE;
	public static final Block DIAMOND_ORE;
	public static final Block DIAMOND_BLOCK;
	public static final Block CRAFTING_TABLE;
	public static final Block WHEAT;
	public static final Block FARMLAND;
	public static final Block FURNACE;
	public static final Block LIT_FURNACE;
	public static final Block STANDING_SIGN;
	public static final DoorBlock WOODEN_DOOR;
	public static final DoorBlock SPRUCE_DOOR;
	public static final DoorBlock BIRCH_DOOR;
	public static final DoorBlock JUNGLE_DOOR;
	public static final DoorBlock ACACIA_DOOR;
	public static final DoorBlock DARK_OAK_DOOR;
	public static final Block LADDER;
	public static final Block RAIL;
	public static final Block STONE_STAIRS;
	public static final Block WALL_SIGN;
	public static final Block LEVER;
	public static final Block STONE_PRESSURE_PLATE;
	public static final DoorBlock IRON_DOOR;
	public static final Block WOODEN_PRESSURE_PLATE;
	public static final Block REDSTONE_ORE;
	public static final Block LIT_REDSTONE_ORE;
	public static final Block UNLIT_REDSTONE_TORCH;
	public static final Block REDSTONE_TORCH;
	public static final Block STONE_BUTTON;
	public static final Block SNOW_LAYER;
	public static final Block ICE;
	public static final Block SNOW;
	public static final CactusBlock CACTUS;
	public static final Block CLAY;
	public static final SugarCaneBlock SUGARCANE;
	public static final Block JUKEBOX;
	public static final Block OAK_FENCE;
	public static final Block SPRUCE_FENCE;
	public static final Block BIRCH_FENCE;
	public static final Block JUNGLE_FENCE;
	public static final Block DARK_OAK_FENCE;
	public static final Block ACACIA_FENCE;
	public static final Block PUMPKIN;
	public static final Block NETHERRACK;
	public static final Block SOULSAND;
	public static final Block GLOWSTONE;
	public static final NetherPortalBlock NETHER_PORTAL;
	public static final Block JACK_O_LANTERN;
	public static final Block CAKE;
	public static final RepeaterBlock UNPOWERED_REPEATER;
	public static final RepeaterBlock POWERED_REPEATER;
	public static final Block TRAPDOOR;
	public static final Block MONSTER_EGG;
	public static final Block STONE_BRICKS;
	public static final Block BROWN_MUSHROOM_BLOCK;
	public static final Block RED_MUSHROOM_BLOCK;
	public static final Block IRON_BARS;
	public static final Block GLASS_PANE;
	public static final Block MELON_BLOCK;
	public static final Block PUMPKIN_STEM;
	public static final Block MELON_STEM;
	public static final Block VINE;
	public static final Block OAK_FENCE_GATE;
	public static final Block SPRUCE_FENCE_GATE;
	public static final Block BIRCH_FENCE_GATE;
	public static final Block JUNGLE_FENCE_GATE;
	public static final Block DARK_OAK_FENCE_GATE;
	public static final Block ACACIA_FENCE_GATE;
	public static final Block BRICK_STAIRS;
	public static final Block STONE_BRICK_STAIRS;
	public static final MyceliumBlock MYCELIUM;
	public static final Block LILY_PAD;
	public static final Block NETHER_BRICKS;
	public static final Block NETHER_BRICK_FENCE;
	public static final Block NETHER_BRICK_STAIRS;
	public static final Block NETHER_WART;
	public static final Block ENCHANTING_TABLE;
	public static final Block BREWING_STAND;
	public static final CauldronBlock CAULDRON;
	public static final Block END_PORTAL;
	public static final Block END_PORTAL_FRAME;
	public static final Block END_STONE;
	public static final Block DRAGON_EGG;
	public static final Block REDSTONE_LAMP;
	public static final Block LIT_REDSTONE_LAMP;
	public static final SlabBlock DOUBLE_WOODEN_SLAB;
	public static final SlabBlock WOODEN_SLAB;
	public static final Block COCOA;
	public static final Block SANDSTONE_STAIRS;
	public static final Block EMERALD_ORE;
	public static final Block ENDERCHEST;
	public static final TripwireHookBlock TRIPWIRE_HOOK;
	public static final Block TRIPWIRE;
	public static final Block EMERALD_BLOCK;
	public static final Block SPRUCE_STAIRS;
	public static final Block BIRCH_STAIRS;
	public static final Block JUNGLE_STAIRS;
	public static final Block COMMAND_BLOCK;
	public static final BeaconBlock BEACON;
	public static final Block COBBLESTONE_WALL;
	public static final Block FLOWER_POT;
	public static final Block CARROTS;
	public static final Block POTATOES;
	public static final Block WOODEN_BUTTON;
	public static final SkullBlock SKULL;
	public static final Block ANVIL;
	public static final Block TRAPPED_CHEST;
	public static final Block LIGHT_WEIGHTED_PRESSURE_PLATE;
	public static final Block HEAVY_WEIGHTED_PRESSURE_PLATE;
	public static final ComparatorBlock UNPOWERED_COMPARATOR;
	public static final ComparatorBlock POWERED_COMPARATOR;
	public static final DaylightDetectorBlock DAYLIGHT_DETECTOR;
	public static final DaylightDetectorBlock DAYLIGHT_DETECTOR_INVERTED;
	public static final Block REDSTONE_BLOCK;
	public static final Block NETHER_QUARTZ_ORE;
	public static final HopperBlock HOPPER;
	public static final Block QUARTZ_BLOCK;
	public static final Block QUARTZ_STAIRS;
	public static final Block ACTIVATOR_RAIL;
	public static final Block DROPPER;
	public static final Block STAINED_TERRACOTTA;
	public static final Block BARRIER;
	public static final Block IRON_TRAPDOOR;
	public static final Block HAY_BALE;
	public static final Block CARPET;
	public static final Block TERRACOTTA;
	public static final Block COAL_BLOCK;
	public static final Block PACKED_ICE;
	public static final Block ACACIA_STAIRS;
	public static final Block DARK_OAK_STAIRS;
	public static final Block SLIME_BLOCK;
	public static final DoublePlantBlock DOUBLE_PLANT;
	public static final StainedGlassBlock STAINED_GLASS;
	public static final StainedGlassPaneBlock STAINED_GLASS_PANE;
	public static final Block PRISMARINE;
	public static final Block SEA_LANTERN;
	public static final Block STANDING_BANNER;
	public static final Block WALL_BANNER;
	public static final Block RED_SANDSTONE;
	public static final Block RED_SANDSTONE_STAIRS;
	public static final SlabBlock DOUBLE_STONE_SLAB2;
	public static final SlabBlock STONE_SLAB2;
	public static final Block END_ROD;
	public static final Block CHORUS_PLANT;
	public static final Block CHORUS_FLOWER;
	public static final Block PURPUR_BLOCK;
	public static final Block PURPUR_PILLAR;
	public static final Block PURPUR_STAIRS;
	public static final SlabBlock DOUBLE_PURPUR_SLAB;
	public static final SlabBlock PURPUR_SLAB;
	public static final Block END_BRICKS;
	public static final Block BEETROOTS;
	public static final Block GRASS_PATH;
	public static final Block END_GATEWAY;
	public static final Block REPEATING_COMMAND_BLOCK;
	public static final Block CHAIN_COMMAND_BLOCK;
	public static final Block FROSTED_ICE;
	public static final Block MAGMA;
	public static final Block NETHER_WART_BLOCK;
	public static final Block RED_NETHER_BRICK;
	public static final Block BONE_BLOCK;
	public static final Block STRUCTURE_VOID;
	public static final Block OBSERVER;
	public static final Block WHITE_SHULKER_BOX;
	public static final Block ORANGE_SHULKER_BOX;
	public static final Block MAGENTA_SHULKER_BOX;
	public static final Block LIGHT_BLUE_SHULKER_BOX;
	public static final Block YELLOW_SHULKER_BOX;
	public static final Block LIME_SHULKER_BOX;
	public static final Block PINK_SHULKER_BOX;
	public static final Block GRAY_SHULKER_BOX;
	public static final Block SILVER_SHULKER_BOX;
	public static final Block CYAN_SHULKER_BOX;
	public static final Block PURPLE_SHULKER_BOX;
	public static final Block BLUE_SHULKER_BOX;
	public static final Block BROWN_SHULKER_BOX;
	public static final Block GREEN_SHULKER_BOX;
	public static final Block RED_SHULKER_BOX;
	public static final Block BLACK_SHULKER_BOX;
	public static final Block WHITE_GLAZED_TERRACOTTA;
	public static final Block ORANGE_GLAZED_TERRACOTTA;
	public static final Block MAGENTA_GLAZED_TERRACOTTA;
	public static final Block LIGHT_BLUE_GLAZED_TERRACOTTA;
	public static final Block YELLOW_GLAZED_TERRACOTTA;
	public static final Block LIME_GLAZED_TERRACOTTA;
	public static final Block PINK_GLAZED_TERRACOTTA;
	public static final Block GRAY_GLAZED_TERRACOTTA;
	public static final Block SILVER_GLAZED_TERRACOTTA;
	public static final Block CYAN_GLAZED_TERRACOTTA;
	public static final Block PURPLE_GLAZED_TERRACOTTA;
	public static final Block BLUE_GLAZED_TERRACOTTA;
	public static final Block BROWN_GLAZED_TERRACOTTA;
	public static final Block GREEN_GLAZED_TERRACOTTA;
	public static final Block RED_GLAZED_TERRACOTTA;
	public static final Block BLACK_GLAZED_TERRACOTTA;
	public static final Block CONCRETE;
	public static final Block CONCRETE_POWDER;
	public static final Block STRUCTURE_BLOCK;

	@Nullable
	private static Block getById(String id) {
		Block block = Block.REGISTRY.get(new Identifier(id));
		if (!field_12591.add(block)) {
			throw new IllegalStateException("Invalid Block requested: " + id);
		} else {
			return block;
		}
	}

	static {
		if (!Bootstrap.isInitialized()) {
			throw new RuntimeException("Accessed Blocks before Bootstrap!");
		} else {
			field_12591 = Sets.newHashSet();
			AIR = getById("air");
			STONE = getById("stone");
			GRASS = (GrassBlock)getById("grass");
			DIRT = getById("dirt");
			COBBLESTONE = getById("cobblestone");
			PLANKS = getById("planks");
			SAPLING = getById("sapling");
			BEDROCK = getById("bedrock");
			FLOWING_WATER = (FlowingFluidBlock)getById("flowing_water");
			WATER = (FluidBlock)getById("water");
			FLOWING_LAVA = (FlowingFluidBlock)getById("flowing_lava");
			LAVA = (FluidBlock)getById("lava");
			SAND = (SandBlock)getById("sand");
			GRAVEL = getById("gravel");
			GOLD_ORE = getById("gold_ore");
			IRON_ORE = getById("iron_ore");
			COAL_ORE = getById("coal_ore");
			LOG = getById("log");
			LOG2 = getById("log2");
			LEAVES = (LeavesBlock)getById("leaves");
			LEAVES2 = (LeavesBlock)getById("leaves2");
			SPONGE = getById("sponge");
			GLASS = getById("glass");
			LAPIS_LAZULI_ORE = getById("lapis_ore");
			LAPIS_LAZULI_BLOCK = getById("lapis_block");
			DISPENSER = getById("dispenser");
			SANDSTONE = getById("sandstone");
			NOTEBLOCK = getById("noteblock");
			BED = getById("bed");
			POWERED_RAIL = getById("golden_rail");
			DETECTOR_RAIL = getById("detector_rail");
			STICKY_PISTON = (PistonBlock)getById("sticky_piston");
			COBWEB = getById("web");
			TALLGRASS = (TallPlantBlock)getById("tallgrass");
			DEADBUSH = (DeadBushBlock)getById("deadbush");
			PISTON = (PistonBlock)getById("piston");
			PISTON_HEAD = (PistonHeadBlock)getById("piston_head");
			WOOL = getById("wool");
			PISTON_EXTENSION = (PistonExtensionBlock)getById("piston_extension");
			YELLOW_FLOWER = (FlowerBlock)getById("yellow_flower");
			RED_FLOWER = (FlowerBlock)getById("red_flower");
			BROWN_MUSHROOM = (PlantBlock)getById("brown_mushroom");
			RED_MUSHROOM = (PlantBlock)getById("red_mushroom");
			GOLD_BLOCK = getById("gold_block");
			IRON_BLOCK = getById("iron_block");
			DOUBLE_STONE_SLAB = (SlabBlock)getById("double_stone_slab");
			STONE_SLAB = (SlabBlock)getById("stone_slab");
			BRICKS = getById("brick_block");
			TNT = getById("tnt");
			BOOKSHELF = getById("bookshelf");
			MOSSY_COBBLESTONE = getById("mossy_cobblestone");
			OBSIDIAN = getById("obsidian");
			TORCH = getById("torch");
			FIRE = (FireBlock)getById("fire");
			SPAWNER = getById("mob_spawner");
			WOODEN_STAIRS = getById("oak_stairs");
			CHEST = (ChestBlock)getById("chest");
			REDSTONE_WIRE = (RedstoneWireBlock)getById("redstone_wire");
			DIAMOND_ORE = getById("diamond_ore");
			DIAMOND_BLOCK = getById("diamond_block");
			CRAFTING_TABLE = getById("crafting_table");
			WHEAT = getById("wheat");
			FARMLAND = getById("farmland");
			FURNACE = getById("furnace");
			LIT_FURNACE = getById("lit_furnace");
			STANDING_SIGN = getById("standing_sign");
			WOODEN_DOOR = (DoorBlock)getById("wooden_door");
			SPRUCE_DOOR = (DoorBlock)getById("spruce_door");
			BIRCH_DOOR = (DoorBlock)getById("birch_door");
			JUNGLE_DOOR = (DoorBlock)getById("jungle_door");
			ACACIA_DOOR = (DoorBlock)getById("acacia_door");
			DARK_OAK_DOOR = (DoorBlock)getById("dark_oak_door");
			LADDER = getById("ladder");
			RAIL = getById("rail");
			STONE_STAIRS = getById("stone_stairs");
			WALL_SIGN = getById("wall_sign");
			LEVER = getById("lever");
			STONE_PRESSURE_PLATE = getById("stone_pressure_plate");
			IRON_DOOR = (DoorBlock)getById("iron_door");
			WOODEN_PRESSURE_PLATE = getById("wooden_pressure_plate");
			REDSTONE_ORE = getById("redstone_ore");
			LIT_REDSTONE_ORE = getById("lit_redstone_ore");
			UNLIT_REDSTONE_TORCH = getById("unlit_redstone_torch");
			REDSTONE_TORCH = getById("redstone_torch");
			STONE_BUTTON = getById("stone_button");
			SNOW_LAYER = getById("snow_layer");
			ICE = getById("ice");
			SNOW = getById("snow");
			CACTUS = (CactusBlock)getById("cactus");
			CLAY = getById("clay");
			SUGARCANE = (SugarCaneBlock)getById("reeds");
			JUKEBOX = getById("jukebox");
			OAK_FENCE = getById("fence");
			SPRUCE_FENCE = getById("spruce_fence");
			BIRCH_FENCE = getById("birch_fence");
			JUNGLE_FENCE = getById("jungle_fence");
			DARK_OAK_FENCE = getById("dark_oak_fence");
			ACACIA_FENCE = getById("acacia_fence");
			PUMPKIN = getById("pumpkin");
			NETHERRACK = getById("netherrack");
			SOULSAND = getById("soul_sand");
			GLOWSTONE = getById("glowstone");
			NETHER_PORTAL = (NetherPortalBlock)getById("portal");
			JACK_O_LANTERN = getById("lit_pumpkin");
			CAKE = getById("cake");
			UNPOWERED_REPEATER = (RepeaterBlock)getById("unpowered_repeater");
			POWERED_REPEATER = (RepeaterBlock)getById("powered_repeater");
			TRAPDOOR = getById("trapdoor");
			MONSTER_EGG = getById("monster_egg");
			STONE_BRICKS = getById("stonebrick");
			BROWN_MUSHROOM_BLOCK = getById("brown_mushroom_block");
			RED_MUSHROOM_BLOCK = getById("red_mushroom_block");
			IRON_BARS = getById("iron_bars");
			GLASS_PANE = getById("glass_pane");
			MELON_BLOCK = getById("melon_block");
			PUMPKIN_STEM = getById("pumpkin_stem");
			MELON_STEM = getById("melon_stem");
			VINE = getById("vine");
			OAK_FENCE_GATE = getById("fence_gate");
			SPRUCE_FENCE_GATE = getById("spruce_fence_gate");
			BIRCH_FENCE_GATE = getById("birch_fence_gate");
			JUNGLE_FENCE_GATE = getById("jungle_fence_gate");
			DARK_OAK_FENCE_GATE = getById("dark_oak_fence_gate");
			ACACIA_FENCE_GATE = getById("acacia_fence_gate");
			BRICK_STAIRS = getById("brick_stairs");
			STONE_BRICK_STAIRS = getById("stone_brick_stairs");
			MYCELIUM = (MyceliumBlock)getById("mycelium");
			LILY_PAD = getById("waterlily");
			NETHER_BRICKS = getById("nether_brick");
			NETHER_BRICK_FENCE = getById("nether_brick_fence");
			NETHER_BRICK_STAIRS = getById("nether_brick_stairs");
			NETHER_WART = getById("nether_wart");
			ENCHANTING_TABLE = getById("enchanting_table");
			BREWING_STAND = getById("brewing_stand");
			CAULDRON = (CauldronBlock)getById("cauldron");
			END_PORTAL = getById("end_portal");
			END_PORTAL_FRAME = getById("end_portal_frame");
			END_STONE = getById("end_stone");
			DRAGON_EGG = getById("dragon_egg");
			REDSTONE_LAMP = getById("redstone_lamp");
			LIT_REDSTONE_LAMP = getById("lit_redstone_lamp");
			DOUBLE_WOODEN_SLAB = (SlabBlock)getById("double_wooden_slab");
			WOODEN_SLAB = (SlabBlock)getById("wooden_slab");
			COCOA = getById("cocoa");
			SANDSTONE_STAIRS = getById("sandstone_stairs");
			EMERALD_ORE = getById("emerald_ore");
			ENDERCHEST = getById("ender_chest");
			TRIPWIRE_HOOK = (TripwireHookBlock)getById("tripwire_hook");
			TRIPWIRE = getById("tripwire");
			EMERALD_BLOCK = getById("emerald_block");
			SPRUCE_STAIRS = getById("spruce_stairs");
			BIRCH_STAIRS = getById("birch_stairs");
			JUNGLE_STAIRS = getById("jungle_stairs");
			COMMAND_BLOCK = getById("command_block");
			BEACON = (BeaconBlock)getById("beacon");
			COBBLESTONE_WALL = getById("cobblestone_wall");
			FLOWER_POT = getById("flower_pot");
			CARROTS = getById("carrots");
			POTATOES = getById("potatoes");
			WOODEN_BUTTON = getById("wooden_button");
			SKULL = (SkullBlock)getById("skull");
			ANVIL = getById("anvil");
			TRAPPED_CHEST = getById("trapped_chest");
			LIGHT_WEIGHTED_PRESSURE_PLATE = getById("light_weighted_pressure_plate");
			HEAVY_WEIGHTED_PRESSURE_PLATE = getById("heavy_weighted_pressure_plate");
			UNPOWERED_COMPARATOR = (ComparatorBlock)getById("unpowered_comparator");
			POWERED_COMPARATOR = (ComparatorBlock)getById("powered_comparator");
			DAYLIGHT_DETECTOR = (DaylightDetectorBlock)getById("daylight_detector");
			DAYLIGHT_DETECTOR_INVERTED = (DaylightDetectorBlock)getById("daylight_detector_inverted");
			REDSTONE_BLOCK = getById("redstone_block");
			NETHER_QUARTZ_ORE = getById("quartz_ore");
			HOPPER = (HopperBlock)getById("hopper");
			QUARTZ_BLOCK = getById("quartz_block");
			QUARTZ_STAIRS = getById("quartz_stairs");
			ACTIVATOR_RAIL = getById("activator_rail");
			DROPPER = getById("dropper");
			STAINED_TERRACOTTA = getById("stained_hardened_clay");
			BARRIER = getById("barrier");
			IRON_TRAPDOOR = getById("iron_trapdoor");
			HAY_BALE = getById("hay_block");
			CARPET = getById("carpet");
			TERRACOTTA = getById("hardened_clay");
			COAL_BLOCK = getById("coal_block");
			PACKED_ICE = getById("packed_ice");
			ACACIA_STAIRS = getById("acacia_stairs");
			DARK_OAK_STAIRS = getById("dark_oak_stairs");
			SLIME_BLOCK = getById("slime");
			DOUBLE_PLANT = (DoublePlantBlock)getById("double_plant");
			STAINED_GLASS = (StainedGlassBlock)getById("stained_glass");
			STAINED_GLASS_PANE = (StainedGlassPaneBlock)getById("stained_glass_pane");
			PRISMARINE = getById("prismarine");
			SEA_LANTERN = getById("sea_lantern");
			STANDING_BANNER = getById("standing_banner");
			WALL_BANNER = getById("wall_banner");
			RED_SANDSTONE = getById("red_sandstone");
			RED_SANDSTONE_STAIRS = getById("red_sandstone_stairs");
			DOUBLE_STONE_SLAB2 = (SlabBlock)getById("double_stone_slab2");
			STONE_SLAB2 = (SlabBlock)getById("stone_slab2");
			END_ROD = getById("end_rod");
			CHORUS_PLANT = getById("chorus_plant");
			CHORUS_FLOWER = getById("chorus_flower");
			PURPUR_BLOCK = getById("purpur_block");
			PURPUR_PILLAR = getById("purpur_pillar");
			PURPUR_STAIRS = getById("purpur_stairs");
			DOUBLE_PURPUR_SLAB = (SlabBlock)getById("purpur_double_slab");
			PURPUR_SLAB = (SlabBlock)getById("purpur_slab");
			END_BRICKS = getById("end_bricks");
			BEETROOTS = getById("beetroots");
			GRASS_PATH = getById("grass_path");
			END_GATEWAY = getById("end_gateway");
			REPEATING_COMMAND_BLOCK = getById("repeating_command_block");
			CHAIN_COMMAND_BLOCK = getById("chain_command_block");
			FROSTED_ICE = getById("frosted_ice");
			MAGMA = getById("magma");
			NETHER_WART_BLOCK = getById("nether_wart_block");
			RED_NETHER_BRICK = getById("red_nether_brick");
			BONE_BLOCK = getById("bone_block");
			STRUCTURE_VOID = getById("structure_void");
			OBSERVER = getById("observer");
			WHITE_SHULKER_BOX = getById("white_shulker_box");
			ORANGE_SHULKER_BOX = getById("orange_shulker_box");
			MAGENTA_SHULKER_BOX = getById("magenta_shulker_box");
			LIGHT_BLUE_SHULKER_BOX = getById("light_blue_shulker_box");
			YELLOW_SHULKER_BOX = getById("yellow_shulker_box");
			LIME_SHULKER_BOX = getById("lime_shulker_box");
			PINK_SHULKER_BOX = getById("pink_shulker_box");
			GRAY_SHULKER_BOX = getById("gray_shulker_box");
			SILVER_SHULKER_BOX = getById("silver_shulker_box");
			CYAN_SHULKER_BOX = getById("cyan_shulker_box");
			PURPLE_SHULKER_BOX = getById("purple_shulker_box");
			BLUE_SHULKER_BOX = getById("blue_shulker_box");
			BROWN_SHULKER_BOX = getById("brown_shulker_box");
			GREEN_SHULKER_BOX = getById("green_shulker_box");
			RED_SHULKER_BOX = getById("red_shulker_box");
			BLACK_SHULKER_BOX = getById("black_shulker_box");
			WHITE_GLAZED_TERRACOTTA = getById("white_glazed_terracotta");
			ORANGE_GLAZED_TERRACOTTA = getById("orange_glazed_terracotta");
			MAGENTA_GLAZED_TERRACOTTA = getById("magenta_glazed_terracotta");
			LIGHT_BLUE_GLAZED_TERRACOTTA = getById("light_blue_glazed_terracotta");
			YELLOW_GLAZED_TERRACOTTA = getById("yellow_glazed_terracotta");
			LIME_GLAZED_TERRACOTTA = getById("lime_glazed_terracotta");
			PINK_GLAZED_TERRACOTTA = getById("pink_glazed_terracotta");
			GRAY_GLAZED_TERRACOTTA = getById("gray_glazed_terracotta");
			SILVER_GLAZED_TERRACOTTA = getById("silver_glazed_terracotta");
			CYAN_GLAZED_TERRACOTTA = getById("cyan_glazed_terracotta");
			PURPLE_GLAZED_TERRACOTTA = getById("purple_glazed_terracotta");
			BLUE_GLAZED_TERRACOTTA = getById("blue_glazed_terracotta");
			BROWN_GLAZED_TERRACOTTA = getById("brown_glazed_terracotta");
			GREEN_GLAZED_TERRACOTTA = getById("green_glazed_terracotta");
			RED_GLAZED_TERRACOTTA = getById("red_glazed_terracotta");
			BLACK_GLAZED_TERRACOTTA = getById("black_glazed_terracotta");
			CONCRETE = getById("concrete");
			CONCRETE_POWDER = getById("concrete_powder");
			STRUCTURE_BLOCK = getById("structure_block");
			field_12591.clear();
		}
	}
}
